### ISSUE TITLE
Zone name not case sensitive

### ISSUE THREAD

**Issue by nicx** [gcobb321/icloud3#10]
I recognized that the zone name is not shown correctly case sensitive.Its always the first letter uppercase, all others lowercase, independently whats configured in the Home Assistant zones.

Example 1:
Zone name configured: HOMEZONE
Shown as state: Homezone

Example 1:
Zone name configured: homezone
Shown as state: Homezone

Could you please correct this small issue that the shown zone name is the same as configured in the HA zones.yaml? Thanks!

**Comment by gcobb321** [comment]
Will look into it.

**Comment by gcobb321** [comment]
Fixed in the Prerelease v0.86.2 in the prerelease directory of the iClouc3 github folder
