### ISSUE TITLE
Authentification every three days

### ISSUE THREAD

**Issue by Lemmings23456** [gcobb321/icloud3#101]
I use the family sharing and I am still not sure, where to put the file config_ic3.yaml. I wrote it in the configuration.yaml 
HA runs on Synology in a docker environment.

Config-File-Problem:

device_tracker:
  - platform: icloud3
    username: !secret icloud_user
    password: !secret icloud_pw
    tracking_method: famshr
    track_devices:
      - iphone_olli > olli.jpeg, Olli
      - iphone_von_julia > julia.jpeg, Julia
      - iphone_von_astrid > astrid.jpeg, Astrid
      - iphone_marc > marc.png, Marc
      - ipad_von_monika > mutter.png, Mutter
      - iphone_von_ann_marie > annmarie.jpeg, Ann-Marie
    unit_of_measurement: km
    time_format: 24
    distance_method: calc
    inzone_interval: '15 min'
    max_interval: '60 min'
    stationary_inzone_interval: '30 min'

there is one in custom_components/icloud3/
and one in the Home-Assistant directory. It would be nice, if the icloud3 log tells me, where it gets its parameters from.

2FA:
Every few days HA tells me to go through the authentification by selecting the trusted device. After doing that, I have to restart HA. Which is not nice to do every few days. What am I doing wrong ?

What about this stationary-zone? What shall I do with that ? Do I have to use it ? Can I delete it ? I don't get the reason, such a zone exists.

**Comment by gcobb321** [comment]
1. The config_ic3.yaml file is optional. It is used to be able to change parameter and restart iCloud3 on the Event Log > Actions. It should be in the /config directory since HACS deletes everything in the iCloud3 directory on an update. The Event Log displays the location of the config_ic3.yaml file being used in Stage 1 of the Initialization. Details about config_ic3.yaml are in the documentation in the Configuration chapter [here](https://gcobb321.github.io/icloud3/#/chapters/2-config-parms?id=config_ic3_file_name). The information should probably be in the Introduction to iCloud3 and I'll add it there to make it easier to find and understand.
2. 2FA - iCloud v2.2 (durrent release) does not support 2FA. That is being supported in v2.3 soon to be released and available as v2.2.2rc9 in the *development directory*. The docs got a little ahead of the actual code. To update to the 2FA version, download the zip file, unzip it into the iCloud3 directory and restart HA. The *development directory* is [here](https://github.com/gcobb321/icloud3/tree/master/development-v2.2.2). The change log shows all the changes from v2.2.1.
3. The Stationary Zone is described in the documentation [here](https://gcobb321.github.io/icloud3/#/chapters/2-special-zones). You can not turn it off but can ignore it if you want.

**Comment by Lemmings23456** [comment]
Thanks for your information ! 
Thanks very much for your work, still it is a great piece of software ;)

Your documentation is quite long, you are so much in the project and it sure is no problem for you but I hope you understand, that - at least I - do read documents only, if it doesn't work ;)

So I have a config_ic3.yaml file in the custom_components/icloud3 directory. In the configuration.yaml there is:

device_tracker:
  - platform: icloud3
    username: !secret icloud_user
    password: !secret icloud_pw
    tracking_method: famshr

and the rest is in the config_ic3-file. Can I do it like that ? Maybe you shouldn't have the possibility to have this in two places because it's irritating where to write what.

<img width="783" alt="Bildschirmfoto 2020-12-30 um 10 12 16" src="https://user-images.githubusercontent.com/59805667/103341533-7fcb4380-4a87-11eb-8c8c-d3c94535e041.png">

I changed the intone interval to 20 minutes and restarted icloud3.

<img width="907" alt="Bildschirmfoto 2020-12-30 um 10 14 48" src="https://user-images.githubusercontent.com/59805667/103341679-dafd3600-4a87-11eb-8ef4-c02746077f76.png">

But the interval did not change, it is still 15 minutes, the value before.

Please tell me what is wrong here ?
<img width="731" alt="Bildschirmfoto 2020-12-30 um 10 15 48" src="https://user-images.githubusercontent.com/59805667/103341730-fe27e580-4a87-11eb-937a-9c04a3432f66.png">

I changed the tracking device in the config_ic3 of my mother from 
  - ipad_von_monika > mutter.png, Mutter
 
to 

  - ipad_von_monika_2 > mutter.png, Mutter

but still after the restart the old device is tracked.

**Comment by gcobb321** [comment]
1. The config _ic3.yaml file is optional. You do not need to use it if you don’t want to. It’s purpose is to be able to restart iCloud3 with parameter changes without restarting Home Assistant.  If you don’t use it, all of the iCloud3 parameters are in the HA configuration.yaml file. The file should be in the /config directory, not the /custom _components/icloud3 directory. If it is In the custom components directory, it will be deleted when you install an update using HACS.
2. If you use the config_ic3.yaml file, the username, password, tracking method, and the exclude/create sensor parameter must be in the configuration.yaml file. All others can be in the config _ic3.yaml file. 
3. The above is all in the documentation. I tried to make the documentation compressive and to Explain how iCloud3 works and how to set it up. With over 1100 users, it is difficult for me to walk everyone through the install and set up process. I hope you understand. 
4. You should not have dashes in front of the parameters. Dashes are meant for multiple items within one parameter track_devices, display_as, etc). The samples parameters in the documentation do not have dashes. 
5. The picture file name should be png or jpg , not jpeg. This was from a prior post. You may have already corrected it but  Acceptable values are found in the Configuration Parameters chapter in the documentation. 
6. The names of the devices you are tracking on the track_devices parameter must match the name on the device itself in the Settings App > General > About screen. The iOS device tracker entity name must start with that and have a suffix. Setting up the device names and how they tie everything together are in the first few chapters in the documentation. iCloud 3 scans the entity registry for mobile app device tracker entities when it starts. Everything it finds are listed in the Event Log.  None are showing on the Event Log so you need to check if they have been set up for each device you are tracking. If you are not using the iOS app on a device, put ‘noiosapp’ in the track device parameter line. 

Good luck and review the example configurations and the first few chapters again to get a better understanding of how all the pieces (iCloud3, iCloud,iOS app and HA) work together.

**Comment by Lemmings23456** [comment]
Thanks a lot for your help. I'm getting closer and try more to read ;)

**Comment by gcobb321** [comment]
iCloud3 v2.3 has been released.
