### ISSUE TITLE
Reauthentication required every day

### ISSUE THREAD

**Issue by eafarris** [gcobb321/icloud3#102]
This integration has been working fine for me for the last few weeks, but suddenly on 1 Jan and each day thereafter, I get a "trusted device" notification each night around midnight and have had to reauthenticate with iCloud every day. Has Apple changed something? How can I assist you in tracking this down?

**Comment by gcobb321** [comment]
What version Of iCloud3  are you running in?

**Comment by jlambert121** [comment]
It looks like this will be resolved in 2.2.2 which is not in HCAS yet.  https://github.com/gcobb321/icloud3/blob/master/docs/CHANGELOG-v2.2.2.md

**Comment by eafarris** [comment]
2.2.1a through HACS. If I do a manual restart from the event log card, I get the "trusted device" notification. If I tap through, iCloud3 authenticates properly. However, it seems the authentication only lasts for a day.

**Comment by gcobb321** [comment]
V2.3 is available in the development-v2.3 directory that supports 2fa and solves this problem. HACS will be updated when the docs are d done but it’s pretty solid at this point. See the install instructions and change Log for more info.

**Comment by eafarris** [comment]
I have updated to v2.3b as per the installation instructions. The updated authentication procedure worked as expected. I'll close this in anticipation of not having to re-authenticate tomorrow. Thanks for your work on this.
