### ISSUE TITLE
Is there an issue with groups and the iCloud3 tracker?

### ISSUE THREAD

**Issue by 26tajeen** [gcobb321/icloud3#104]
I am finding that my iCloud3 device tracker isn't playing nicely with groups but much more likely it's a Home Assistant fault rather than an iCloud3 fault!

[Thread here](https://community.home-assistant.io/t/was-there-a-problem-with-groups-not-working-correctly-on-0-114-4/267207/10)

**Comment by gcobb321** [comment]
It is probably an HA issue. iCloud3 is a device_tracker custom component that tracks devices, not people. Others have reported issues where one person has 2 devices and left home with only one device. iCloud3 is tracking the devices so one will show Home and the device will other will show Away. How these devices are combined by HA to report a person's location in this example can lead to questionable results.
