### ISSUE TITLE
Interval Between Location Check is Way to Long

### ISSUE THREAD

**Issue by lordexorr** [gcobb321/icloud3#105]
This may not actually be an "issue" but I have scoured the documentation and have been unable to figure out how to fix this.

I've got iCloud3 running and tracking devices. I setup a dashboard for my kids so they can see how far mom is from the house. While she's at work (in a work zone) the interval is to check for a location every 2 hours. The problem is that if it checks at, say, 4:00pm, and she's still at work, it won't check again until 6pm (2 hour interval) and by then she's already home.

If it checks at 4:00pm and she happens to be out of work, it will then start updating at shorter intervals which is helpful and seems to be intended.

I'm not sure how I can alter the setup so that when she leaves a zone it starts updating her location every 5 minutes or something like that. I also plan to setup a routine for when she's within a mile of the house (using a zone) that opens her garage door, turns on outside lights, and makes an announcement/notification saying "Mommy is almost home". If I can't get the interval/tracking to be more fine tuned it won't really work for any true automation since it would be a crap shoot if it happens to check when she's close to the house.

I am using the iCloud Family Sharing integration. I tried the HA iOS App for tracking but it sucked and only checked location when you have the app open, so doesn't work for reliable tracking to be used for automation's.

Is there a way to have a time of day based interval. What I mean is between 4pm and 6pm it checks every 5 minutes, but other times it's different? This would allow me to setup a more frequent polling during the times my wife is traveling home from work, but not have it be that way 24/7 and possibly draining her battery (although I'm not sure how much this would really drain a battery).

I see the parameters below in the sample config_ic3 file but am not exactly sure how I need to alter these to make checking locations more frequent.

#--Zone/Tracking Parameters-----------------------------------------
#inzone_interval: '60 min'
#max_interval: '4 hrs'
#center_in_zone: True
#stationary_inzone_interval: '30 min'
#stationary_still_time: '8 min'
#stationary_zone_offset: 1, 0
#travel_time_factor: .6
#distance_method: waze

Edit: Adding a screenshot that may help as this issue happened again today.
- It says "Direction - In Zone" for when it checked at 4:51:30 but that is incorrect. She was not in a zone at that time.
- It also says she's "Stationary" and "21 Minutes" from home but the interval is set to "30 minutes". She was at a grocery store picking up groceries and left a minute or two after it checked her location. Since the interval was set to "30 minutes" (longer than the estimated distance from home) it didn't check again until after she was home already.

![image](https://user-images.githubusercontent.com/38336945/104380766-8632d400-54f9-11eb-89b7-93315ae7b435.png)

**Comment by gcobb321** [comment]
I use the HA iOS App to issue zone enter and exits and do not have any issues about it not locating my phone or entering or exiting a zone. If the iOS App is not on the phone, iCloud3 never knows a zone has been left so the checks the location again when the interval is reached. See [here](https://gcobb321.github.io/icloud3/#/chapters/1.2-getting-started?id=what-happens-if-i-don39t-want-to-use-the-ios-app-or-the-ios-app-is-not-set-on-the-phone) for more info about that.

iCloud3 defaults to an *inzone_interval: 2 hrs* so it will check to see where she is every 2 hrs. If you don't want to use the iOS App, you will need to change the *inzone_interval* time to a smaller value. If the TravTime from work to home is 21 min, Try setting the *inzone_interval: 15 min*. That would get iCloud3 to do a poll somewhere between work and home and it would be accurate from from that poine.

**Comment by lordexorr** [comment]
> I use the HA iOS App to issue zone enter and exits and do not have any issues about it not locating my phone or entering or exiting a zone. If the iOS App is not on the phone, iCloud3 never knows a zone has been left so the checks the location again when the interval is reached. See [here](https://gcobb321.github.io/icloud3/#/chapters/1.2-getting-started?id=what-happens-if-i-don39t-want-to-use-the-ios-app-or-the-ios-app-is-not-set-on-the-phone) for more info about that.
> 
> iCloud3 defaults to an _inzone_interval: 2 hrs_ so it will check to see where she is every 2 hrs. If you don't want to use the iOS App, you will need to change the _inzone_interval_ time to a smaller value. If the TravTime from work to home is 21 min, Try setting the _inzone_interval: 15 min_. That would get iCloud3 to do a poll somewhere between work and home and it would be accurate from from that poine.

Yeah, I attempted to use the HA iOS App first and it never updated locations correctly. It would only update phone/zone information when I would reboot HA or have the app open on the phone. When the app isn't open, its extremely random on when it updates data for the devices. These problems are what led me to your integration 👍 I do have the HA iOS app installed on the devices though.

I will try to update the inzone_interval time but am concerned if iCloud3 always thinks our devices are in a zone it will never start pulling data in a speedier manner. As the screenshot I put says she's in a zone, when she wasn't.

Side note; what's your recommended method of installing iCloud3/iOS App? Should I install iCloud3 first, and then register each device from the App or the other way around? The install documentation says to install iCloud3 after the iOS app and then go in and manually update device.tracker entities for the iOS App items but wondering if I unregistered all the iOS devices first, then installed iCloud3 and then let the iOS App register if that would be a cleaner method since it would then automatically create different entity names. I'm happy to reinstall things if needed, I'm still learning with HA so I apologize if some of my questions are silly.

**Comment by gcobb321** [comment]
Installing iCloud3 and then iOS app will work just fine and be cleaner. The docs assume you have been running the iOS app and then added iCloud3 later. 

The shortened interval will catch when you have left the zone before you get home since you are nothing getting zone exit triggers from the iOS app. 
Check the iOS app settings [here](https://gcobb321.github.io/icloud3/#/chapters/1.4-setting-up-iosapp). 
Check Stage 3 that shows iOS app info during start up [here](https://gcobb321.github.io/icloud3/#/chapters/1.6-configuring-starting-icloud3?id=icloud3-event-log-during-initialization)

**Comment by lordexorr** [comment]
Awesome, I removed the iOS devices from HA and re-added them so it's a bit cleaner now. Updated the polling interval to 15 minutes inside zones and made sure all iOS settings were correct (for the 1,000th time). I'll see how it works out for me tomorrow. I appreciate all the guidance :)

**Comment by lordexorr** [comment]
I have the following configurations in my config file right now. I left a few commented out to leave them at defaults.

#--Zone/Tracking Parameters-----------------------------------------
inzone_interval: '15 min'
max_interval: '20 min'
#center_in_zone: True
stationary_inzone_interval: '15 min'
stationary_still_time: '5 min'
#stationary_zone_offset: 1, 0
#travel_time_factor: .6
#distance_method: waze

However, my wife at work, the interval is 22 min (see screenshot below). Any idea how it's pulling an interval of 22 min when I "think" all my configurations shouldn't allow more than 15 min?

![image](https://user-images.githubusercontent.com/38336945/104463816-3c410100-5580-11eb-9b0c-9279eb8f5941.png)

To add; all my devices in my home zone are correctly using 15 min (screenshot below). Is this related to the work zone not utilizing the config file?

![image](https://user-images.githubusercontent.com/38336945/104463997-701c2680-5580-11eb-9b1b-4e8f01de89f6.png)

**Comment by gcobb321** [comment]
A code is displayed in the Event Log showing how the interval calculation was done. To see it, select Event Log > Actions > Start HA Debug Logging. The code is displayed after the Interval. It will look like *Interval-15 min (4ihz-InHomeZone)*. What does your show ?  Turn the debug logging off the same way you turned it on.

**Comment by lordexorr** [comment]
Below are the logs. They don't look different than when HA Debug logging isn't enabled though.

![image](https://user-images.githubusercontent.com/38336945/104500994-2138b600-55ad-11eb-968a-2651c1c60280.png)

**Comment by lordexorr** [comment]
This seems to be functioning much better since I updated the zones a bit and am allowing iCloud3 to use the iOS App for entering/leaving zones as it's intended. While the iOS App wasn't working well on it's own for tracking, it seems it does function decently for zone leave/enter which is all iCloud3 really needed to start updating intervals at shorter times.

In short; I think this is all set and I appreciate the help @gcobb321 getting this pulled together.
