### ISSUE TITLE
No 2 factors authentification notification and no visual editor

### ISSUE THREAD

**Issue by romaingood** [gcobb321/icloud3#110]
Hi,

I'm completely noob, wasn't even known what yaml or python were a few days ago, and obviously missing something!

I haven't installed the HA app for the moment, wanted icloud3 firstly.
I've installed HACS on my HA supervisor, and immediatly icloud3.
I've created a www/custom_cards file, put icloud3-event-log-card.js in it and restart HA.

I became no notification for 2 factors authentification and have an error message when I try to install the card in Lovelace.

![HA](https://user-images.githubusercontent.com/77360000/104822075-73ddd080-5840-11eb-8e00-fae7818d9fc5.JPG)

I've tried lot's of things, a community file instead of the custom_cards file too, but always had the same result.

What am I doing wrong? 

Thank you

**Comment by lexieke** [comment]
Did you change the configuration.yaml to include the tracker?

**Comment by gcobb321** [comment]
I also posted the following message on the iCloud3 formum since it was a duplicate posting.

@romain7
The Lovelace editor will not highlight the Save/Enregistrer button for you to save the card until you have an entity item.

When you add the card, also add the *sensor: icloud3_event_log* after the *type…*
```
type: 'custom:icloud3-event-log-card'
entity: sensor.icloud3_event_log
```
Then click Save/Enregistrer at the bottom and you should be all set.

**Comment by gcobb321** [comment]
@StijnJans 
There are new configuration parameters to define the devices to be tracked. The [v2.3 Change Log](https://gcobb321.github.io/icloud3/#/CHANGELOG-v2.3) explains the new parameters. The old *track_devices* parameter will still work.

**Comment by romaingood** [comment]
I was doing lot's of beginner mistakes during the process...
The main mistake was not specify "device_tracker:" as it isn't obvious for the noob I am 
It's working now 

Thanks for your answers and sorry for the duplicate posting

**Comment by gcobb321** [comment]
Glad you have it working.

**Comment by gcobb321** [comment]
I updated the example configuration.yaml file to include the device_tracker entry.
