### ISSUE TITLE
Distance values ignore unit of measurement after some time

### ISSUE THREAD

**Issue by Radushka** [gcobb321/icloud3#113]
Hi @gcobb321,

Many, many thanks for all the hard work that goes into this. Much appreciated!

Here is an issue I've noticed happening. Initially after a restart of iCloud3 the distances are displayed correctly, in kilometres (as per my config_ic3.yaml). However, after a while, not sure how long, all distance values (wazedist, homedist and calcdist) change. The location of the devices is about the same and as far as I can tell those values are correct, but ... in miles.

My guess is that the change happens during the next update of the location. Thanks for looking into it.

**Comment by gcobb321** [comment]
I'm not aware of any problems. No changes have been made to those routines for a very very long time. 

What version of iCloud3 are you running?

**Comment by Radushka** [comment]
iCloud3 v2.3 - I have a video of what's happening - link sent to your gmail address.

**Comment by Radushka** [comment]
v2.3.1 takes care of this this issue, thank you!
