### ISSUE TITLE
icloud3 not updated when I leave home

### ISSUE THREAD

**Issue by kevtuning** [gcobb321/icloud3#116]
I have configured icloud3 and it seems like to work fine since it detects my iOS app and see that I am home...

Nevertheless, when I leave home, it does not change anything and the interval polling stays at 2 hours... 

Any idea what could I do ?

P.S: my HA server is not accessible from outside... but I imagine that it could not be the issue...
<img width="364" alt="2021-02-03_15-48-43" src="https://user-images.githubusercontent.com/5998776/106763784-79585a80-6637-11eb-8ca0-cb1c1f0993a6.png">

**Comment by gcobb321** [comment]
iCloud3 relies on the iOS App for zone enter/exit triggers. If the iOS App can not connect to your HA server, no triggers will be received and iCloud3 will not detect a zone change. If you do not want to use the iOS App, you will need to shorten the *inzone_interval* value which will probably eat your battery. Another option is to create an automation that triggers when you loose the iosApp _ssid network nameindicating you are no longer connected to your network and use the *iCloud3_update* service with a *zone: not_home* parameter to change the zone. Look in the icloud3 docs [here](https://gcobb321.github.io/icloud3/#/chapters/3.4-services?id=icloud3_update-service) for more info on the service call.

** I have not using that ios app ssid change to trigger a zone change so it may not work.

**Comment by gcobb321** [comment]
Closing this issue for now. Reopen it if the problem still exists.
