### ISSUE TITLE
Check Configuration hangs after installing and configuring the integration

### ISSUE THREAD

**Issue by jayscovill** [gcobb321/icloud3#123]
I'm probably missing something obvious here but I've installed the Integration through HACS and configured the it but when I try to do a check config before a reboot the check configuration in HASS just hangs and never completes.  If I comment out the iCloud3 lines in device_tracker.yaml it checks fine so I know it's something to do with iCloud3.

My configs:

configuration.yaml

`device_tracker: !include device_tracker.yaml`

device_tracker.yaml

          
    - platform: icloud3
      tracking_method: iosapp
      username: !secret appleid
      password: !secret applepassword
    

config_ic3.yaml

    devices:
       - device_name: JiPhone
         name: Jay iPhone
         email: someone@someone.com
       - device_name: JayWatch
         name: Jay Watch`

This is logged in HASS:

`Error handling request
1:15:08 PM – loader.py (ERROR) - message first occurred at 12:44:09 PM and shows up 7 times`

**Comment by gcobb321** [comment]
I can't tell if the loader.py error comes from the icloud3 parameters. The only way to tell is to comment out the `device_tracker: !include device_tracker.yaml` statement and see if you still get the error. But I assume you have done that.

The format of the `devices:...` statements may be a little off. It looks like there are 3-spaces before the `- device_name` statement when there should be 2-spaces. Also, the Jay Watch ends with a single ` mark. But that could just be the formatting for posting this issue.

Has it ever loaded and run? Or is this an initial setup? Make sure all the icloud3 files are installed in the *custom_configuration/icloud3* directory.

`

**Comment by jayscovill** [comment]
Hi, yes those are just formatting errors with the code blocks in Github.

This is the first time I've tried the integration.  Commenting out the include for device_tracker.yaml fixes it so it's definitely the icloud3 integration causing it.

**Comment by gcobb321** [comment]
Are all the files installed in *config/custom_components/icloud3*? They are:

```
config
  custom_components
    icloud3
      device_tracker.py
      pyicloud_ic3.py
      __init__.py
      manifest.json
      services.yaml
```

You will also have:
```
icloud3-event-log-card.js
config_ic3_sample.yaml
--other sample automation, script and lovelace files
```

Are there any other errors in the HA log? You might look in the home-assistant.log file to see what is leading up to the error.

**Comment by gcobb321** [comment]
**v2.3.4 has been uploaded to the *icloud3/development v2.3.4 directory.***

- Download it [here](https://github.com/gcobb321/icloud3/tree/master/development%20v2.3.4)
- Unzip the *device_tracker.zip* file into *config/custom_component/icloud3* directory.
- Restart HA

**Change log:**
* Corrected the 'selwf' spelling error.
* Fixed a problem setting up the *track_from_zone* parameter. The zone(s) specified are now verified. Also, the *track_from_zone* zone name can now be either the zone name or the zone's friendly name.
* The *config_ic3.yaml* configuration parameters are now being validated. Errors are displayed in the Event Log and ignored.- Added a check for a mismatched quote (') in the *config_ic3* parameter file. An error message is displayed in the Event Log showing the line number with the error.
* Fixed a problem where the 'True/False' configuration parameters were not being handled correctly.
* Removed all iCloud '2-factor-authentication' code.

**Comment by jayscovill** [comment]
Oddly, it started working for me all of the sudden. Not sure why as I didn’t change anything.  But all good one.

**Comment by gcobb321** [comment]
Glad it's working now. Have you loaded v2.3.4 and installed it or were you referring to v2.3.3 working? As you could see from the change log, v2.3.4 did fix a few things.

**Comment by jayscovill** [comment]
V2.2.3. I’ve still got some problems but I think I just need to go over the docs again.  I have basic functionality and the event log showing up so most of the way there.  Thanks for the great work!

**Comment by gcobb321** [comment]
The docs are for v2.3.4. The major change is the iCloud authentication, plus numerous other changes and enhancements. The v2.3 Change log is [here](https://gcobb321.github.io/icloud3/#/CHANGELOG-v2.3).

If you upgrade now, do HACS v2.3.3 install, then unzip the device_tracker.zip file. But I plan on creating a v2.3.4 release probably Tuesday or Wednesday on HACS.

**Comment by jayscovill** [comment]
Awesome, thanks.  I’ll hold off till you have the HACS install ready.

**Comment by gcobb321** [comment]
#### v2.3.4 Bug Fix Update (2/23/2021) is available on HACS and on the iCloud3 GitHub Repository
