### ISSUE TITLE
Typo in device_tracker.py, line 1410

### ISSUE THREAD

**Issue by Snuffy2** [gcobb321/icloud3#124]
iCloud3 v2.3.3

There appears to be a typo:

device_tracker.py, line 1410: selwf._display_info_status_msg(devicename, "Initialize Event Log")

Home Assistant Log:
2021-02-19 21:47:03 ERROR (SyncWorker_3) [custom_components.icloud3.device_tracker] name 'selwf' is not defined
Traceback (most recent call last):
File "/config/custom_components/icloud3/device_tracker.py", line 1410, in _start_icloud3
selwf._display_info_status_msg(devicename, "Initialize Event Log")
NameError: name 'selwf' is not defined

**Comment by poudenes** [comment]
Same error here.

**Comment by chrisbl01** [comment]
Yup, same

**Comment by timota** [comment]
```
selwf._display_info_status_msg(devicename, "Initialize Event Log")
```

should be `self.`

**Comment by gcobb321** [comment]
That one is the easy fix. The other 3 issues are a little harder, 2 are done, 1 to go . I should have a v2.3.4 update Sunday.

**Comment by gcobb321** [comment]
**v2.3.4 has been uploaded to the *icloud3/development v2.3.4 directory.***

- Download it [here](https://github.com/gcobb321/icloud3/tree/master/development%20v2.3.4)
- Unzip the *device_tracker.zip* file into *config/custom_component/icloud3* directory.
- Restart HA

**Change log:**
* Corrected the 'selwf' spelling error.
* Fixed a problem setting up the *track_from_zone* parameter. The zone(s) specified are now verified. Also, the *track_from_zone* zone name can now be either the zone name or the zone's friendly name.
* The *config_ic3.yaml* configuration parameters are now being validated. Errors are displayed in the Event Log and ignored.- Added a check for a mismatched quote (') in the *config_ic3* parameter file. An error message is displayed in the Event Log showing the line number with the error.
* Fixed a problem where the 'True/False' configuration parameters were not being handled correctly.
* Removed all iCloud '2-factor-authentication' code.

**Comment by gcobb321** [comment]
#### v2.3.4 Bug Fix Update (2/23/2021) is available on HACS and on the iCloud3 GitHub Repository
