### ISSUE TITLE
Format for multiple zones in track_from_zone:

### ISSUE THREAD

**Issue by jayscovill** [gcobb321/icloud3#129]
What is the correct format/delimiter for specifying multiple zones for track_from_zone:

I have tried using semi-colons, commas and spaces but the log throws an error with an invalid configuration.

**Comment by gcobb321** [comment]
I think the track_from_zone will only allow 1 zone. I'll look at adding the ability to track from more than one zone. When that happens, a comma will be used to separate the zone names.

**Comment by gcobb321** [comment]
I have updated the  iCloud3 development version (v2.3.6a) in the *development v2.3.x* directory to support multiple zones. 

Format: *track_from_zone: zone1, zone2, etc.* where zone# is the zone’s entity name or friendly name. 
Example: *track_from_zone: The Point, Warehouse* or *track_from_zone: the_point, whse*

Download the zip file, unzip it into the icloud3 directory and restart HA.

**Comment by gcobb321** [comment]
Reopen this issue if you have any problems with the v2.3.6b1 update that supports tracking from multiple zones.
