### ISSUE TITLE
ignore_gps_accuracy_inzone in 0.86.1 pre-release

### ISSUE THREAD

**Issue by klovatt** [gcobb321/icloud3#13]
Hi, I observed some strange behaviour last night while inzone, and looked through the code.

I believe there is a typo in line 1905.

You have "self.ignore_gps_accuracy_inzone", where everywhere else it is "self.ignore_gps_inzone_flag".

**Comment by gcobb321** [comment]
Good catch. Fixed.

------ Original Message ------
