### ISSUE TITLE
Waze distance parameters in the docs are confusing

### ISSUE THREAD

**Issue by 0x0a11c0de** [gcobb321/icloud3#131]
The documentation for `waze_min_distance` and `waze_max_distance` have me confused. First, the documentation doesn't say what the units are. The defaults are 1 and 1000, respectively. Is that miles, feet, km, meters?

Second, this paragraph seems to contradict itself:

> The Waze distance becomes less accurate when you are close to home. The calculation method is better when the distances less than 1 mile or 1 kilometer.

The first sentence says it's less accurate when close, but the second sentence seems to say it works better when close. What is this paragraph trying to tell me?

**Comment by gcobb321** [comment]
The value is in your unit_of_measurement. That is 1mi-1000mi if um=mi, 1km-1000km if um=km.

It really doesn't contradict itself. What it means is the calc method is used if the distance to home is less than 1mi/km and waze methoc if distance to home > 1mi/km. The reason if you are close to home (say .3mi), the interval time will be small anyway (15 sec). The difference between waze distance/travel time and the calc distance is small and not worth the delay in response time it takes to call waze, especially if you are in a poor cell phone area and waze has to be called several times before a valid response is returned.

**Comment by 0x0a11c0de** [comment]
I figured I was misunderstanding it somehow. Thanks for the clarifications!
