### ISSUE TITLE
does anyone get emails from Apple like this?

### ISSUE THREAD

**Issue by 26tajeen** [gcobb321/icloud3#133]
"Your apple ID was used to sign in to iCloud from a web browser"

No device given, no location given.

The email itself isn't a scam, it's come from Apple for sure and there's no dodgy link to click...

I have a feeling it's iCloud3 but not sure. When I login to icloud there are no suspicious devices.

<a href="https://www.imgur.com/a/P5KQXtI">pic here</a>

**Comment by gcobb321** [comment]
Yes, iCloud will send out an email that someone logged into your account when it was iCloud3 doing an account authentication. The time frame is not specific. It is nothing to be concerned about. When developing the 2fa routines, we would get them to.

I receive them and have set up a filter in my email program (gmail) to delete them and not send them to the inbox.
