### ISSUE TITLE
Authorize the configuration file in package mode

### ISSUE THREAD

**Issue by barto95100** [gcobb321/icloud3#134]
Hi, I test to configure the icloud3 with package mode but don't work, maybe I configure wrong parameter

but if I configure in configuration.yaml and put the config_ic3.yaml on same folder of my configuration.yaml is work but if i put config_ic3.yaml in older folder (package) don't work...

thank's

**Comment by gcobb321** [comment]
What parameters are in your configuration.yaml and config _ic3.yaml files?
What are the names of the directories you are using for the files?

It is impossible to help solve your problem without detailed information on how you have everything set up. Also, I do not understand what you mean by ’package mode’. Is it the icloud3 directory?
