### ISSUE TITLE
HASS complaining about lack of version key in manifest file

### ISSUE THREAD

**Issue by derekoharrow** [gcobb321/icloud3#135]
Every time I start HASS I get this error:

`2021-03-08 14:37:02 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'icloud3'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'icloud3'`

I'm using iCloud 3 v2.3.5

Thanks

**Comment by gcobb321** [comment]
I posted [this update note](https://community.home-assistant.io/t/icloud3-v2-3-update-advanced-device-tracker-and-ios-app-location-monitor/267554/91) yesterday afternoon in the iCloud3 forum,
