### ISSUE TITLE
enhancement of date time format for last_located/last_update/next_update

### ISSUE THREAD

**Issue by rodpayne** [gcobb321/icloud3#136]
Gary,
Is there any way that we could get a date time format for `last_located`/`last_update`/`next_update` that is like `zone_timestamp`/`timestamp`/`authenticated`?  Getting time intervals and comparing time is difficult with a 12-hour time without AM/PM.

**Comment by gcobb321** [comment]
iCloud3 v2.4.0 was just uploaded to HACS which supports this request.

**Comment by rodpayne** [comment]
Thank you.  I have installed v2.4.0 and updated [my integration](https://github.com/rodpayne/home-assistant_person_location) to use the new format.  So far, it is working great.
