### ISSUE TITLE
'No version' warning

### ISSUE THREAD

**Issue by lolongan** [gcobb321/icloud3#138]
I update to HASS version 2021.3.3 and get a warning message in the logs:
```
Logger: homeassistant.loader
Source: loader.py:802 
First occurred: 8:16:05 AM (1 occurrences) 
Last logged: 8:16:05 AM

No 'version' key in the manifest file for custom integration 'icloud3'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'icloud3'
```

**Comment by gcobb321** [comment]
See [this note](https://community.home-assistant.io/t/icloud3-v2-3-update-advanced-device-tracker-and-ios-app-location-monitor/267554/89)  in the iCloud3 forum.

**Comment by lolongan** [comment]
> See [this note](https://community.home-assistant.io/t/icloud3-v2-3-update-advanced-device-tracker-and-ios-app-location-monitor/267554/89) in the iCloud3 forum.

Thanks. Looks like HACS does not detect that my installed icloud3 version is not the most recent one (2.3.5)

**Comment by gcobb321** [comment]
The one before that. It’s about the iCloud3 update and the error. GitHub sometimes does not scroll to the beginning of a referenced note.
