### ISSUE TITLE
Waze_region: AU error

### ISSUE THREAD

**Issue by scottwilliamsinaus** [gcobb321/icloud3#143]
Up until v2.2 (I think), using a config parameter waze_region: AU had worked flawlessly here in Australia. With v 2.3 and now 2.4 there is a constant error saying that AU is not a valid value, and hence I have lost my much-appreciated waze distance and travel time entities. Separately, the underlying Waze travel time platform works fine with region: AU.
Any chance of bringing AU back to play nicely in icloud3?

**Comment by hillsdweller** [comment]
Setting Waze region to EU is working for me in Australia, counter-intuitive but it works!

**Comment by gcobb321** [comment]
Glad it worked. I have not made any changes to how Waze interacts with route requests but will do so when I get a chance.
