### ISSUE TITLE
name 'www' is not defined

### ISSUE THREAD

**Issue by niceboygithub** [gcobb321/icloud3#146]
small bug

https://github.com/gcobb321/icloud3/blob/2b7ec83833564b9c0e001fd90b208ea86315a267/custom_components/icloud3/device_tracker.py#L8901

.homeassistant/custom_components/icloud3/device_tracker.py", line 8901, in _check_ic3_event_log_file_version
    www.beta_version = 0
NameError: name 'www' is not defined

**Comment by gcobb321** [comment]
Fixed in iCloud3 v2.4.1 just uploaded to HACS and the iCloud3 GitHub repository.
