### ISSUE TITLE
Is it likely that air tags could be supported ?

### ISSUE THREAD

**Issue by B-Hartley** [gcobb321/icloud3#148]
Is it likely that air tags could be supported ?

Anything in the APIs you use that would allow them to be added ?

thanks.

**Comment by bjeanes** [comment]
Probably not unless somebody reverse engineers how the Find My app looks up the locations. They don't even show up in icloud.com

https://apple.stackexchange.com/questions/420123/how-do-you-find-an-airtag-on-the-web
https://stackoverflow.com/questions/67911557/what-is-the-apple-developer-api-to-access-apple-airtag-data

**Comment by gcobb321** [comment]
Air tags do not transmit their location to your iCloud account like an iPhone does so they can’t be used as a device tracker. For more info about air tags and how they work, go [here](https://github.com/picklepete/pyicloud/issues/338).

**Comment by Cybersmurfen** [comment]
Check the new share functions in 18? Ive tried to play a little with it but have too many other things to do.

**Comment by SoCuul** [comment]
Do you think it would be feasible to implement [FindMy.py](https://github.com/malmeloo/FindMy.py/blob/main/examples/airtag.py) support in iCloud3? They've managed to reverse engineer the protocol for interacting with the Find My servers directly.

**Comment by gcobb321** [comment]
@SoCuul 
Interesting. I’ll look into it after I finish a few things.
