### ISSUE TITLE
No Tracked Devices Error

### ISSUE THREAD

**Issue by dearthymcstain** [gcobb321/icloud3#152]
Name of my phone (General -> About -> Name): **TylerPhone**
Device Name in HA App (Sidebar -> App Configuration -> General -> DeviceName): **TylerPhone**
Name of device in HA (HA Sidebar -> Configuration -> Entities -> sort by "Mobile app" -> Name): **TylerPhone-App**
Entity id in HA (HA Sidebar -> Configuration -> Entities -> sort by "Mobile app" -> Entity Id) **device_tracker.tylerphone_app**
Name of device in iCloud3 config (/config_ic3.yaml): - device_name: **TylerPhone**

_No Tracked Devices Error_

I have alos tried by removing the "-App" and "_app" from the HA entity name and device ID, respectively.

_No Tracked Devices Error_

It does manage to connect to the icloud API and download my fmf list. I think it's a separate issue, but the function _setup_tracked_devices_for_fmf looks for "friend_emails" in friend.get('invitationAcceptedHandles'). In my case, two of my friends in fmf have phone numbers, not emails, in the 'invitationAcceptedHandles'. This, of course, will fail in the function _extract_fmf_email_id (which looks for the "@" symbol in what it presumes is an email address).

**Comment by gcobb321** [comment]
When iCloud3 starts, te phones in the FmF list, the FamShr list and the HA mobile_app device tracker entities are listed. A check mark is next to a phone that matches the device_name parameter. iC3 uses the email address to match phones in the FmF list, not the phone number. Try not specifying the iosapp_suffix or iosapp_entity parameters. They are normally only used if there are duplicate entities caused by installing the mobile app several times.

**Comment by dearthymcstain** [comment]
Thank you for your reply!

1. I am NOT using iosapp_suffix nor iosapp_entity in config_ic3.yaml nor configuration.yaml.
2. In the case of my fmf list, I invited two of my friends knowing only their phone number. I don't know their email address. Hence, 'invitationAcceptedHandles' is a phone number. I think this may be a feature request.
3. I thought that it would at least be able to find **TylerPhone**, based on the data that I had supplied, though it's beginning to sound (and look) like the error message "Setup aborted, no devices to track. Verify the devicename on the `devices/device_name: [devicename]` parameters. They must be the same as `Settings > General > About > Name` on the phones being tracked." is a red herring. Meaning, it's all about the FmF list, the FamShr list, and the HA mobile app matching what's in config_ic3.yaml. Is this correct?

**Comment by gcobb321** [comment]
If your email in the HA device_name parameter matches the username of the iCloud account, you will end up tracking yourself with FamShr. not FmF.  The only way to track yourself is to check the "Use this Device as Me" (or something like it) box. This ties it the phone to the FamShr account using their internal Id your phone. (It wookd me a while to figure this out.) You can still put your email in but it will be ignored.

You should be able to track yourself. It would help me to see what is being displayed in the Event Log for the HA mobile apps that were found, the FamShr and DmD list. Post a screenshot or Export the Event Log (Event Log > Actions > Export Event Log) and send the \config\icloud3_event_log.txt file to geekstergary@gmail.com.

**Comment by dearthymcstain** [comment]
All is well. As it turns out, the problem was that I had a tab character (\t) in config_ic3.yaml. Perhaps I'll create a pull request to account for that. Thank you for your attention.

**Comment by gcobb321** [comment]
A pull request won’t fix the problem. Ic3 uses the standard yaml import libraries to parse the config_ic3.yaml file. Plus the next version is being completely restructured to use Object Oriented Programming to store and process everything. At over 10,000 lines of code, it was getting too large to maintain and needed to be broken into modules supporting individual devices, zones, functions, etc.

I’m glad you got it working.

**Comment by dearthymcstain** [comment]
"The problem" was merely the error message. If the yaml cannot be imported because there is a tab character, then I think the error message should relay as much so that the user can address the correct problem. Thank you for all your hard work!
