### ISSUE TITLE
iCloud3 present in HACS repositories as installed , but does not appear in HA Integrations

### ISSUE THREAD

**Issue by YoSafeguard** [gcobb321/icloud3#155]
Immediately I apologize - I'm a beginner!
I have HA Core installed on my Synology NAS without using Docker. 
iCloud3 installed via HACS. It is present in HACS repositories as installed, but does not appear in HA Integrations. 
What I just didn’t do! 
HA rebooted both in itself and by means of Synology. There are files in the `custom_components/icloud3` directory, but Even Log is not installed. 
Help me please!!!
Thank you!

**Comment by gcobb321** [comment]
iCloud3 is not an integration so it will not be listed in the HA integrations. It is a custom component. 

The documentation explains the steps that will help you get started using iCloud3. Find it [here](https://gcobb321.github.io/icloud3/#/).
