### ISSUE TITLE
Blocked from losing due to Missing valid version key

### ISSUE THREAD

**Issue by tmchow** [gcobb321/icloud3#156]
I'm seeing this in logs

> The custom integration 'icloud3' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details

I don't understand why this is showing up because in the manifest.json I see the `version` key:

![image](https://user-images.githubusercontent.com/517103/120593093-d13f7c00-c3f3-11eb-89d4-c7552ce8abb0.png)

**Comment by gcobb321** [comment]
I am out of town so I have not updated to 2021.6.1 yet and Am running 2021.5.2.  That is the same file I’m using and it is working fine for me. I would suggest fiddling with the file and moving the version line to somewhere else, changing the number, changing the double quotes to single quotes, etc.  and see what happens. Ill be home late next week and will upgrade then. 

Also, you could reinstall the previous version of HA
