### ISSUE TITLE
Travel Time Minutes

### ISSUE THREAD

**Issue by broyuken** [gcobb321/icloud3#159]
Not an issue, but a small feature request. Could you please add the number of minutes in the travel time sensor as an attribute? I want create a template sensor for if we’re more than 30 mins from our house, and would prefer not to have to build out the logic to convert 1.5 hours into minutes only if travel time > 59 and whatnot. It would make that sensor much more usable for automations instead of just being useful for Lovelace. 

Thanks, and LOVE ic3!

**Comment by broyuken** [comment]
Just checking in on this to see if it would be a quick addition. I'm assuming you already have the minutes value and convert it to a more human readable format for the sensor. Would it be possible to have the raw data available to us?

Edit: I think I'd have to create a separate sensor for the raw data using something like the following. Then use that value in my automations or additional sensors. I'm trying to create a sensor that is true if my wife and I are "far away from the house" meaning more than 30 mins away. 

I turn our ACs off when we leave, and would like to turn the air conditioners back on if we are no longer "far away from the house" to give it some time to cool the house down so we walk into a nice cool house instead of the AC turning back on when we get home and walk into a hot box. 


```
{% if ((states.sensor.my_iphone_travel_time.state.split(" ")[1]) == "hrs")%}
  {{(states.sensor.my_iphone_travel_time.state.split(" ")[0]|float*60) | round(0)}}
{% else %}
  {{(states.sensor.my_iphone_travel_time.state.split(" ")[0])|int }}
{% endif %}
```

**Comment by gcobb321** [comment]
Hi,
I am currently working on v3 and had planned to incorporate this feature in it. 

It had become quite large, somewhat disorganized (probably more than somewhat), was becoming difficult to add new features and did not use the latest programming concepts that would give it flexibility. Plus I needed something to do this summer. So I took it apart and then put it back together. I have it working pretty well and am now taking care of some of the finer points. It is much faster, is more sensitive to iOSApp location updates, can handle both FamShr & FmF tracking methods dynamically by looking all of the location data available and selecting the best one. It also greatly enhances tracking from multiple zones and fixes some problems with multi-zone tracking I didn't  know about. I have 3 things still to do - improve the HA interaction and performance, on-line configuration parameter entry and adding a waze history database to reduce the delay getting routing data from waze.

I'll take a look at v2.4 and see if it will be easy to add this feature to it. If so, I'll put up a development version and let you know.

I hope to have a good v3 beta version out in September. It actually works good now but I still see minor things here-and-there. Let me know if you are interested in doing some early testing.

Gary

**Comment by broyuken** [comment]
That’s great news, and I am absolutely interested in some early testing as long as it is fairly stable and not missing any major features. Let me know what I could do to help.

**Comment by broyuken** [comment]
No rush, just checking if you’ve had a chance to look at it yet.

**Comment by gcobb321** [comment]
I got it working in iCloud3 v3 yesterday. Should have it in v2.4 today or tomorrow.

**Comment by broyuken** [comment]
Sweet, I’ll grab the dev version as soon as it’s available. Thank you!

**Comment by gcobb321** [comment]
I just updated it into the *development-v2.4.3* directory [here](https://github.com/gcobb321/icloud3/tree/master/development-v2.4.3). Download *icloud3 v2.4.3.zip* and unzip it into the */custom_components/icloud3* directory.

**Comment by broyuken** [comment]
Thank you! It's installed, and I'll test it out as I leave my house.

**Comment by broyuken** [comment]
So far so good

**Comment by broyuken** [comment]
Seems to work great, however I think it would be cleaner if you could add it as an attribute to the travel time sensor instead of having another sensor added. Just my .02
