### ISSUE TITLE
History not getting created for most sensors in icloud3

### ISSUE THREAD

**Issue by nmsousa76** [gcobb321/icloud3#160]
No history is being created for zone and distance sensors (battery Sensors are fine).   State is being correctly identified in teh sensor, but it does not seem to be writing to the history DB.   (these sensors re the only ones not creating history.

![image](https://user-images.githubusercontent.com/65356035/125841220-4deb3857-54f9-403e-bdf4-9f25b6e64d0f.png)

**Comment by nmsousa76** [comment]
this issues seems to only happen with External MariaDB (internal SQLITE works fine).  Here is the result of the log error.

Logger: homeassistant.components.recorder
Source: components/recorder/__init__.py:818
Integration: Recorder (documentation, issues)
First occurred: 4:14:21 PM (1 occurrences)
Last logged: 4:14:21 PM

Error in database connectivity during commit: Error executing query: (MySQLdb._exceptions.OperationalError) (1366, "Incorrect string value: '\\xE2\\x97\\x8F\\xE2\\x97\\x8F...' for column `hassio_prod`.`states`.`state` at row 1") [SQL: INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created, old_state_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)] [parameters: ('sensor', 'sensor.nunos_iphone_pro_max_info', '●● Define Sensors ●●', '{"icon": "mdi:information-outline", "friendly_name": "NoneInfo"}', 81252629, datetime.datetime(2021, 7, 15, 20, 12, 52, 367071, tzinfo=datetime.timezone.utc), datetime.datetime(2021, 7, 15, 20, 12, 52, 367071, tzinfo=datetime.timezone.utc), datetime.datetime(2021, 7, 15, 20, 12, 52, 367071, tzinfo=datetime.timezone.utc), None)] (Background on this error at: http://sqlalche.me/e/14/e3q8). (retrying in 3 seconds)



Logger: homeassistant.components.recorder
Source: components/recorder/__init__.py:841
Integration: Recorder (documentation, issues)
First occurred: 4:14:24 PM (1 occurrences)
Last logged: 4:14:24 PM

SQLAlchemyError error processing event <Event time_changed[L]: now=2021-07-15T16:13:40.100929-04:00>: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (MySQLdb._exceptions.OperationalError) (1366, "Incorrect string value: '\\xE2\\x97\\x8F\\xE2\\x97\\x8F...' for column `hassio_prod`.`states`.`state` at row 1") [SQL: INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created, old_state_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)] [parameters: ('sensor', 'sensor.nunos_iphone_pro_max_info', '●● Define Sensors ●●', '{"icon": "mdi:information-outline", "friendly_name": "NoneInfo"}', 81252629, datetime.datetime(2021, 7, 15, 20, 12, 52, 367071, tzinfo=datetime.timezone.utc), datetime.datetime(2021, 7, 15, 20, 12, 52, 367071, tzinfo=datetime.timezone.utc), datetime.datetime(2021, 7, 15, 20, 12, 52, 367071, tzinfo=datetime.timezone.utc), None)] (Background on this error at: http://sqlalche.me/e/14/e3q8) (Background on this error at: http://sqlalche.me/e/14/7s2a)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 632, in _process_one_event_or_recover
    self._process_one_event(event)
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 752, in _process_one_event
    self._commit_event_session_or_retry()
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 815, in _commit_event_session_or_retry
    self._commit_event_session()
  File "/usr/src/homeassistant/homeassistant/components/recorder/__init__.py", line 841, in _commit_event_session
    self.event_session.commit()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1428, in commit
    self._transaction.commit(_to_root=self.future)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 827, in commit
    self._assert_active(prepared_ok=True)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 601, in _assert_active
    raise sa_exc.PendingRollbackError(
sqlalchemy.exc.PendingRollbackError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (MySQLdb._exceptions.OperationalError) (1366, "Incorrect string value: '\\xE2\\x97\\x8F\\xE2\\x97\\x8F...' for column `hassio_prod`.`states`.`state` at row 1")
[SQL: INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created, old_state_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('sensor', 'sensor.nunos_iphone_pro_max_info', '●● Define Sensors ●●', '{"icon": "mdi:information-outline", "friendly_name": "NoneInfo"}', 81252629, datetime.datetime(2021, 7, 15, 20, 12, 52, 367071, tzinfo=datetime.timezone.utc), datetime.datetime(2021, 7, 15, 20, 12, 52, 367071, tzinfo=datetime.timezone.utc), datetime.datetime(2021, 7, 15, 20, 12, 52, 367071, tzinfo=datetime.timezone.utc), None)]
(Background on this error at: http://sqlalche.me/e/14/e3q8) (Background on this error at: http://sqlalche.me/e/14/7s2a)

**Comment by nmsousa76** [comment]
This can be closed, I ended up create a new external MAriaDB and issue went away.

**Comment by gcobb321** [comment]
As I remember from some similar issues a couple of years ago, it has to do with the encoding of the sql data base. Data bases encoded in ascii had this problem. Changing the encoding to utf-8 solved it. There are some special characters (dots, arrows, check marks, etc) that ascii does not support. 

Glad you have it working
