### ISSUE TITLE
Detecting "tracking paused" and taking action

### ISSUE THREAD

**Issue by cerebrate** [gcobb321/icloud3#161]
Occasionally, when I'm out and about - most commonly, I think, in areas where service is not so good - this error shows up in the icloud3 log:

![image](https://user-images.githubusercontent.com/371623/129487750-b0c0acf5-6e3e-4979-97c9-42e603b5183f.png)

Is there a good/official way to detect when this has happened from an automation (other than trying to parse the text of the _sensor.icloud3_event_log_ value, which seems like a fairly terrible method), and if not, could there be?

I'd like to set up a system to notify me when and if this happens, and an automatic unpause, if possible, should I not have manually taken care of it after a few hours. It would also be useful to have other automations treat location data as appropriately unreliable when this has happened.

**Comment by gcobb321** [comment]
When iCloud3 is paused, I think the next update time sensor is set to PAUSED. The info sensor also has PAUSED in it. Do Event Log > Actions > Pause Tracking and check the state of these sensors to be sure. You might be able to check these values in an automation trigger. Then issue an icloud3 update service call to resume tracking of the devices that are paused.

see [here](https://gcobb321.github.io/icloud3/#/chapters/3.4-services?id=icloud3_update-service) for more info and examples on the resume command.

**Comment by cerebrate** [comment]
Thanks!

I've set up a couple of binary_sensor templates and automations based on them and tested them with manual pausing, and that seems to work, so guess I'm just waiting for another error to happen for real. I'll go ahead and close this now, though.
