### ISSUE TITLE
Unable to login via app specific iCloud password

### ISSUE THREAD

**Issue by shailyglobal83** [gcobb321/icloud3#162]
I dont want to share my password i am trying it to login via app specific iCloud password but i am unable to do the needful getting error missing apple id field

**Comment by gcobb321** [comment]
The app specific password is used for apps from the Apple App Store. iCloud3 is a program, not an app,  that accesses the iCloud account location data using a different interface than apps do so the app specific password will not work. Your real password is used by iCloud3 to log into your account but it is not stored anywhere and is not available in any Log files that can be printed.

**Comment by shailyglobal83** [comment]
Thanks for responding. Is it possible to make the provision of login via app specific password as it is done in HA iCloud integration where i have logged in using app specific password.

**Comment by gcobb321** [comment]
I will add it to the list of things to look into for v3.0 that I’m working on now

**Comment by shailyglobal83** [comment]
When are you planning to release v3.0 i am eagerly waiting for the new version 😊

**Comment by gcobb321** [comment]
I don’t have a date yet. I still have a bunch of things to work on before I start the beta phase. What is done is looking good but I keep coming up with improvements, better ways of doing things, new features, etc. I’ll keep you posted.

**Comment by gcobb321** [comment]
v3 is working prety goon on my devices and I hope to release it to beta in November. I'll let you know when it is ready.
