### ISSUE TITLE
Documentation Error [Bug]

### ISSUE THREAD

**Issue by pickerin** [gcobb321/icloud3#17]
Both Example 1 and Example 2 of the  Lovelace examples share the same code, so would not produce the cards shown in the images (they all appear to be the code to render Example 2 (5x2), found at:
https://gcobb321.github.io/icloud3/#/chapters/3-sample-lovelace

Additionally, the code has an error, where in Lillian's section, the code is:
     - entity: device_tracker.lillian_iphone
                name: Gary

Finally, it appears that the custom-lovelace-card is listed as a type "js" when in fact it should be a "module"?  At least that was the only way I could get it operational when installed via HACS.

**Comment by gcobb321** [comment]
I've corrected the documentation. Thanks for finding the error.
