### ISSUE TITLE
icloud3_find_iphone_alert only works for the main icloud account devices

### ISSUE THREAD

**Issue by nayefag** [gcobb321/icloud3#171]
Hi,

I have family sharing enabled (with Find My on all devices) and the icloud3_find_iphone_alert seems to only work on the main icloud account devices (not the family icloud account devices).

Tried it on family member devices and it does not work. What could be the issue?  (I can alert all family devices using the "Find My" app on the iphone, so I do not think it is an icloud setting issue).

Using latest icloud3 version (2.4.2).

Thanks.

**Comment by TonyOneZero** [comment]
Same issue.

**Comment by gcobb321** [comment]
I’ll look into it

**Comment by qiuyuxuan1999** [comment]
anyning new？I have the same issue

**Comment by gcobb321** [comment]
The Find-my-Friends tracking method does not support sending a list phone alert. The Interface program used to request the Location from iCloud only supports this feature on devices in the Family Sharing list. This may be an Apple limitation.
