### ISSUE TITLE
Waze Route Failure

### ISSUE THREAD

**Issue by broyuken** [gcobb321/icloud3#174]
I just updated icloud3 and now my Waze tracking isn’t working. I’m getting “no response from Waze servers , Calc distance will be used.” In my ic3 event log card. 

Did the url change or is there some other issue?

**Comment by gcobb321** [comment]
Probably the waze servers are down. Restart iCloud3 in a while From the Event Log > Actions and see what happens. There were no changes to Waze routines and I’m not having any problems.

**Comment by broyuken** [comment]
Dang, it’s been like this all day and I have restarted ic3

**Comment by gcobb321** [comment]
I’m now getting this error on the v2.4.4 you are using and the v3.0 in development and will let you know or what I find later today.

**Comment by broyuken** [comment]
thank you, I appreciate you still looking into it. My buddy just verified that he's seeing it as well.

**Comment by gcobb321** [comment]
Found out the version of the Wave Route Calculator in the HA Python library is the issue. Even the HA Waze Integration doesn’t work. The official Python one does work so I’ve downloaded it and will mod it to tie into iCloud3 easier than it does now (like pyicloud_ic3). I’ll let you know when v2.4.5 is ready to check out, probably later today.

**Comment by gcobb321** [comment]
The code is updated. Download *iCloud3-v2.4.5.zip* and unzip it into the */custom_components/icloud3* directory. The zip file is in the Development-v2.4.5 directory [here](https://github.com/gcobb321/icloud3/tree/master/development-v2.4.5).

**Comment by broyuken** [comment]
Not sure if I'm doing something wrong, but the event log card still shows 2.4.4. I unzipped the files into the right dir, and restarted HA. 

```
➜  icloud3 ls -lat
total 624
drwxr-xr-x    2 root     root          4096 Oct  5 13:32 __pycache__
drwxr-xr-x    4 root     root          4096 Oct  5 13:30 .
-rwxrwxrwx    1 42949672 42949672     44275 Oct  5 13:29 pyicloud_ic3.py
-rwxrwxrwx    1 42949672 42949672    477472 Oct  5 13:29 device_tracker.py
-rwxrwxrwx    1 42949672 42949672      4523 Oct  5 13:29 waze_route_calc_ic3.py
drwxr-xr-x   18 root     root          4096 Oct  4 09:35 ..
-rw-r--r--    1 root     root            30 Oct  4 09:35 __init__.py
-rw-r--r--    1 root     root          1918 Oct  4 09:35 config_ic3_sample.yaml
-rw-r--r--    1 root     root         73474 Oct  4 09:35 icloud3-event-log-card.js
-rw-r--r--    1 root     root           293 Oct  4 09:35 manifest.json
drwxr-xr-x    2 root     root          4096 Oct  4 09:35 sample-lovelace-cards
-rw-r--r--    1 root     root          1876 Oct  4 09:35 services.yaml
➜  icloud3 pwd
/config/custom_components/icloud3
➜  icloud3
```

![image](https://user-images.githubusercontent.com/1593391/136074432-abb6ea9a-12f9-431d-a98d-09cdb752400f.png)

**Comment by gcobb321** [comment]
I forgot to change the iCloud3 version number. I created a customized waze_route_calc_ic3.py to handle the waze stuff to bypass the HA one. It’s in your directory so you should be ok.

**Comment by broyuken** [comment]
Ok cool, I’ll test it when I go out later this afternoon. Thank you!

**Comment by pauly7300** [comment]
I was seeing the error too so i'm going to try as well.  I assume waze_rout_calc_ic3.py is a new mainstay in the root of the icloud3 directory?

**Comment by gcobb321** [comment]
The module WazeRouteCalculator by Kovács Bálint, Budapest, Hungary, is in the standard Python library and is used to interface to the www.waze.com for real time route distance & time info. This had been part of the HA Library for years without any issues. He updated the module in September, 2021 and it was uploaded to the Python Standard Library. Who knows what happened but the HA version now has a problem which was causing the 'Waze is not available' in iCloud3. The HA libraries are compiled and in another docker container (I think) so I could not see what the HA code was doing wrong.

Kovács Bálint's version was working so I got that code, stripped out all the stuff I did not need and that will be the interface from now on.

**Comment by pauly7300** [comment]
Excellent.  Looks like it's working now for me.  Also, wanted to make sure you saw my email on the other subject...

**Comment by gcobb321** [comment]
@pauly7300 
I did see it. I am deep into v3.0 at the moment and have little (no) experience with venv, docker, linux, etc. and the 'under the cover' stuff. I'm more of an applications guy but find your search interesting and will continue to follow it and contribute as I can.

**Comment by broyuken** [comment]
Looks like it worked for me as well. Thanks for the prompt fix.

**Comment by gcobb321** [comment]
We’ll release it on HACS tomorrow afternoon after I go running around

**Comment by broyuken** [comment]
Looks like this may have popped up again. Getting the “No response from Waze servers” error again.

**Comment by broyuken** [comment]
This could have just been related to the aws outage yesterday, I think it’s working today. Will check when I go out later. 

Edit: nope still broken.

**Comment by larronni** [comment]
This error originated from a custom integration.

Logger: custom_components.icloud3.device_tracker
Source: custom_components/icloud3/waze_route_calc_ic3.py:145
Integration: icloud3 (documentation, issues)
First occurred: 7 December 2021, 08:59:45 (1119 occurrences)
Last logged: 07:31:45

'result'
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 8359, in _get_waze_distance
    self.WazeRouteCalc.calc_route_info(from_lat, from_long, to_lat, to_long)
  File "/config/custom_components/icloud3/waze_route_calc_ic3.py", line 145, in calc_route_info
    route_time, route_distance = self._add_up_route(route['result'])
KeyError: 'result'

**Comment by gcobb321** [comment]
That error is caused by no route time and distance data being returned from Waze. The problem is on the Waze end. iCloud3 didn’t catch the error and display a friendly error message.

**Comment by broyuken** [comment]
Figured as much. Do you know if they’re having an issue or did they change something? Or are you not able to check because you said you wouldn’t be available to fix anything for a few weeks?

**Comment by gcobb321** [comment]
I was connecting yesterday so I’m not sure what was going on. I’ve restarted HA several times and that might have reset something.

**Comment by broyuken** [comment]
I’ve reset multiple times but still don’t have Waze working.

**Comment by gcobb321** [comment]
HA has a Waze Integration. I wonder if that works.

**Comment by lordexorr** [comment]
I'm having the same issue. Wave distance isn't functioning. Have the newest version available in HACS (2.4.6).

The message I'm seeing in the logs is;

Waze Route Failure > No Response from Waze Servers, Calc distance will be used

**Comment by broyuken** [comment]
@gcobb321 The Waze integration works fine, I just installed it and tested with a random address and it calculated the route correctly. This seems to be only affecting iC3 at this time. I think you mentioned you changed the Waze integration and included your own instead of using the HA one a version or two back.

**Comment by gobigdave** [comment]
First, thank you for a fantastic component! I was using life360 before, but then I heard about their willingness to sell my kid's location data to anyone. Your component is a great replacement.

I'm seeing the same issue (Waze Route Failure). I'm on version 2.4.6.

I use the Waze integration for commuting times and such elsewhere in HA, and those are all working fine. That tells me it's something in ic3.

**Comment by gcobb321** [comment]
I looked at the Waze code in the Python Standard Library last night and a change was made a couple of weeks ago. It looks like the new version returns several times/distance results in one route request rather than only  the primary (shortest) time/distance. That requires changes the code iCloud3 uses to extract the time/distance info from Waze. 

 I need  to update the iCloud3 interface to support the changes Waze made.  Right now, I am on a cruise ship in Antarctica so the changes that are needed are going to wait until I return after Christmas.

**Comment by broyuken** [comment]
No I demand that you end your vacation early and fix your integration that you provide for free to a bunch of strangers on the internet!

enjoy the cruise and we can test when you get back and have time to look at it.

**Comment by gcobb321** [comment]
I have been busy interviewing potential team members. So far, 1 candidate is outstanding but I still have 3-days to go.


————————
Gary Cobb

**Comment by broyuken** [comment]
I wish I had the coding skills to help out in any way but unfortunately I don’t. But I’ll gladly help test whenever needed.

**Comment by broyuken** [comment]
Just saw the update, looks like it’s working again! Thank you so much!!

**Comment by lordexorr** [comment]
Working here as well. Thanks so much!
