### ISSUE TITLE
Driving Sensors - Sample Card

### ISSUE THREAD

**Issue by kingy444** [gcobb321/icloud3#175]
https://gcobb321.github.io/icloud3/#/chapters/3.1-sample-lovelace?id=example-2-two-people-4x3-format

I have two questions about the above sample card - i do not appear to have a input_boolean to match
input_boolean.NAME_driving_flag
is this something we need to setup manually? and if so how? 

IS there a way to make the TravTime and WazeDist display a default value when a user is home? this will help keep it all nicely in line instead of dropping down slightly

**Comment by kingy444** [comment]
I have found this in the documentation - but am i meant to manually declare a driving flag boolean for the script?

https://gcobb321.github.io/icloud3/#/chapters/3.2-sample-automation-scripts?id=setclear-driving-flags

**Comment by gcobb321** [comment]
Yes. You have to create the input Boolean , scripts and automations yourself. The examples in the docs are just meant to get you started
