### ISSUE TITLE
Missing sensor codes for customizing created sensors

### ISSUE THREAD

**Issue by calebmah** [gcobb321/icloud3#18]
In [this documentation](https://gcobb321.github.io/icloud3/#/chapters/2-sensors?id=customizing-sensors-that-are-created-by-icloud3), a list of codes are provided to customize which sensors are created through the use of the `create_sensors` or `exclude_sensors` attributes. However, this list does not directly correspond to all the sensors created, as documented [earlier on in the page](https://gcobb321.github.io/icloud3/#/chapters/2-sensors?id=how-the-sensors-are-used).

Digging into `device_tracker.py`, I found that these codes are defined in `SENSOR_ID_NAME_LIST`, whereas the full list of sensors are actually found in `SENSOR_DEVICE_ATTRS`. In particular, the `battery_status` and `badge` sensors are missing from the list of codes, meaning that these sensors cannot be explicitly included. This makes the `create_sensors` attribute useless for anyone who wants to include these sensors, since they cannot be explicitly included. Similarly, `exclude_sensors` cannot be used if we want these sensors with missing codes to be excluded. 

Hope the code list can be updated to include all available sensors. Alternatively, the codes could be removed and the actual sensors in `SENSOR_DEVICE_ATTRS` (eg. `battery_status` or `badge`) could be used in the configuration instead, which would be clearer and cause less confusion.

**Comment by gcobb321** [comment]
Will add on the next release

**Comment by gcobb321** [comment]
I've added the codes to the development version of iCloud3.

The next version of iCloud3 that is under development is in the [iCloud3 GitHub repository here](https://github.com/gcobb321/icloud3/tree/master/development).
