### ISSUE TITLE
Add step and distance

### ISSUE THREAD

**Issue by jflefebvre06** [gcobb321/icloud3#181]
The documentation say `iCloud3 does all of the tracking activities included in the HA iCloud Integration, plus a lot more so it is not needed and should be removed` but i cannot find sensor.xxx_distance and sensor.xxx_steps
Could you please add them ?

**Comment by gcobb321** [comment]
The `steps` and `distance` sensors are created by the HA iOS app, not the iCloud app. iCloud3 creates a `[devicename]_zone_distance` sensor that is the Waze route distance to the zone or the straight-line calculated distance based on the `distance_method` configuration parameter.

**Comment by gcobb321** [comment]
The `steps` and `distance` sensor entities are provided by the iOS app Integration so there is no need for iCloud3 to repeat them. iCloud3 provides a `zone_distance` entity that is the distance from the device to the tracked zone. It will be the waze route distance or a straight line distance depending on the `distance_method` config parameter.
