### ISSUE TITLE
Tracking paused

### ISSUE THREAD

**Issue by tom-roger** [gcobb321/icloud3#182]
Hi,

Tracking is paused occasionally for my wife's phone. I see this error message in iCloud3.  

Tracking paused - Excessive errors Encountered
Old location errors-#24
Discarded updates-#12
----------------------------------------------------------
Event log > Actions > Resume polling to restart

What is causing this error?

Br,
T-R

**Comment by gcobb321** [comment]
I’ve seen the same thing when I’m at a doctor’s office who is in a building with very poor to no phone service and real slow internet. The problem iCloud loses track of the phone so it keeps reporting the last location. The location time gets older and older so tracking is paused. The polling Interval increases when this happens to to extend the time between location request. The Event Log shows what it’s going on and the errors/old location time/good accuracy problems.

**Comment by UnbridledGames** [comment]
Can we configure the timeout for this? Every time my wife is at work her tracking pauses and I have to manually restart it. It's absurdly annoying and a feature I absolutely HATE.

**Comment by gcobb321** [comment]
This can not be configured. Also, you do not need to do a restart to resume polling. All you need to do is resume using an Action command on the Event Log. `Event Log > Actions > Resume` 

 There it’s something you might try, however. 
1. Set up a zone for her work location. 
2. Make sure you are ignoring gps accuracy when in a zone using `ignore_gps_accuracy_inzone: true`
3. Set up an automation that will resume her polling around the time she usually leaves if she in in that zone and the `sensor.[her-devicename]_next_update_time` is `PAUSED`. A script do that is in the iCloud3 docs [here](https://gcobb321.github.io/icloud3/#/chapters/3.4-services?id=example-automations-or-scripts) and below:
 
 ```
icloud3_command_resume_polling:
  alias: 'Resume Polling'
  sequence:
    - service: device_tracker.icloud3_update
      data:
        devicename: [her-devicename]
        command: resume
```

I’m not at my computer so I can not put one together to try out but that might give you something to try.
