### ISSUE TITLE
Authentication trouble

### ISSUE THREAD

**Issue by kgarz** [gcobb321/icloud3#183]
When I input the password field in the configuration.yaml file and then check the configuration, I get the following error: "Invalid config for [device_tracker.icloud3]: string value is None for dictionary value @ data['password']. Got None. (See ?, line ?)". I may be missing something very simple but am at a loss. Whenever I comment out the password field iCloud3 works fine with the iosapp but I would like to use the icloud configuration. What am I missing? Thank you

**Comment by gcobb321** [comment]
Have you tried putting the password in quote marks? 

Without seeing your exact complete configuration, it is hard to advise what to do.

**Comment by kgarz** [comment]
The quotations worked for it. Thank you, knew it was something simple I was missing. Another quick question, is there any way to get Apple airtags added to icloud3? or will it be coming in the future?

**Comment by gcobb321** [comment]
Air tags are different than the other devices and can not be tracked.

————————
Gary Cobb
