### ISSUE TITLE
Custom element doesn't exist: icloud3-event-log-card.

### ISSUE THREAD

**Issue by FabioEight** [gcobb321/icloud3#185]
Hello,
I'm following the guide to install iCloud3 via HACS on my HAOS (RPi 4, last version up to date) but I'm stuck on configuring the Event Log dashboard.
If I insert the component:

`type: custom:icloud3-event-log-card`
I receive the error _Custom element doesn't exist: icloud3-event-log-card._.
I checked the resources, and I tried to configure with the following:

/config/www/custom_cards/icloud3-event-log-card.js (file exists, checked via File Editor)

But also:

/local/www/custom_cards/icloud3-event-log-card.js (file does not exists) 

Still, I'm unable to proceed with this step.
Could you please assist?

**Comment by FabioEight** [comment]
Issue solved with host restart, not only HA restart.

**Comment by varenc** [comment]
I'm getting this same problem now.

Per the docs:
> The Event Log card is a Lovelace custom card. In order to set it up, it must be added to the Lovelace Resources. iCloud3 automatically adds it to the Lovelace Resources when it starts so nothing should need to be done. **Manual instructions on doing this are at the end of this chapter in case it is not added correctly or an error occurs**.

So I guess this didn't happen automatically for me but also i can't find the manual instructions for this anywhere.

I'm just following the guide laid out here: https://gcobb321.github.io/icloud3_v3_docs/#/chapters/1.1-tracking-results-screen?id=creating-the-tracking-results-screen-lovelace-yaml-code
