### ISSUE TITLE
Event Log empty but still works

### ISSUE THREAD

**Issue by NPC-112** [gcobb321/icloud3#187]
I'm getting back into home assistant and wanted to try icloud3 again, but after the recent hass updates the event log card stopped showing the log.
The action buttons still work, and I can tell from viewing the event log sensor's state attributes that it's still logging and doing location updates, but the card is blank except for the action and title bars.

I've tried rolling back to before the updates, reinstalling through hacs, manually installing, resetting and restarting through the card, and deleting all the related configuration.yaml entries, ic3_config.yaml, and the /config/.storage/icloud/ folder but its still blank.

It's not just blank on my desktop but my mobile app and browser as well.
Any input on this?

I've attached here my [icloud3-event-log.txt](https://github.com/gcobb321/icloud3/files/7739775/icloud3-event-log.txt)

**Comment by gcobb321** [comment]
1. The Event Log data is stored in sensor.icloud3_event_log. Use the Developer Tools to see if any data and control fields are there. 
2. Make sure there are no javascript errors in your browser. 
3. Reset the browser cache and refresh HA. 
4. Refresh the iOS app cache using a pull down. You should see a spinning wheel. 
5. Make sure you do not have a quote mark in the phones name. That can sometimes screw up javascript. (Gary’s iphone vs Gary iPhone) 
6. 
I didn’t see anything strange in the log

**Comment by NPC-112** [comment]
#5 worked. I had some display_text_as: parameters that used apostrophes, after removing them and restarting its working again. Thanks for the help!
