### ISSUE TITLE
device_tracker shows all icloud devices per device?

### ISSUE THREAD

**Issue by ethanopp** [gcobb321/icloud3#19]
When using more than one icloud account, each device shows all the devices under the tracking attribute. 

For example I have two icloud accounts, Ethan and Emily. 

On device_tracker.ethans_iphone, "Tracking" shows:
 `tracking:  ethans_iphone(ethans_iphone_ha_app), emilys_iphone(emilys_iphone_ha_app)`

and on device_tracker.emilys_iphone, "Tracking" shows the same thing:
`tracking:  ethans_iphone(ethans_iphone_ha_app), emilys_iphone(emilys_iphone_ha_app)`

Is this normal?

**Comment by gcobb321** [comment]
Yes, this is normal. The tracking attributes show all devices being tracked for all iCloud accounts.

**Comment by ethanopp** [comment]
Okay - so if I wanted to make a `group.household` to show when everyone is home/away, should I be using the zone1’s or just the ‘name’_iphone’s?

**Comment by gcobb321** [comment]
I'd set up a Boolean sensor that is true when all devicename_zone1 = Home

**Comment by ethanopp** [comment]
Okay great thanks!
