### ISSUE TITLE
iCloud calendar

### ISSUE THREAD

**Issue by gieljnssns** [gcobb321/icloud3#19]
Since you're now an expert in the iCloud component (pyicloud) :wink: .
Do you have some time for making a custom component for the iCloud calendar (native)?

**Comment by gcobb321** [comment]
I'm not an 'expert' on pyicloud. All I did was use the original program as a starting point and make it a lot better. I have too many other things I want to do so someone else will have to tackle that project. Sorry.

I am glad you are using iCloud3 and hope it's working well for you. They'll be a new release in the next few days that fixes everything I know about and adds some new features. The biggest is that iCloud3 now uses data from the HA IOS app (Manual push, Background Fetch) to immediately update the devices location without calling the Apple iCloud Find-my-Friends service, even if the next polling interval has not been reached.


———
Gary Cobb
