### ISSUE TITLE
near_zones - bit of help please

### ISSUE THREAD

**Issue by townsmcp** [gcobb321/icloud3#190]
Hi, I have been looking over the documentation [here](https://gcobb321.github.io/icloud3/#/chapters/2.3-special-zones?id=the-near_zone-zone) and can see the near_zone might be helpful to my setup - mobile reception is not great when getting near home due to living on a new build estate and I think this might be able to help overcome the problems.

The problem Im having is where to start - I see the document mentions adding 'near_zone' into zones.yaml - I have searched my HA setup and cant find a zones.yaml.
Im happy to create it but where should it go? 
Can the 'near_zone' go into config_ic3.yaml instead? 
Is there an example of what the section should look like?

Thanks in advance

**Comment by gcobb321** [comment]
Actually, the near_zone function worked sometimes but was not really reliable in poor cell phone areas and has been removed in the next release. Make sure you have the iOS app installed on your phone. It can help in these situations.

**Comment by townsmcp** [comment]
@gcobb321 thanks for the info. Out of curiosity, my config is the following; can you suggest any changes/additional changes to help compensate for poor cell phone? I do have the iOS Companion App installed on all iPhones.

devices:
  - device_name: James iPhone
    name: James
    picture: James.png
  - device_name: Cheryl iPhone
    name: Cheryl
    picture: Cheryl.png
  - device_name: Dylan iPhone
    name: Dylan
    picture: Dylan.png
  - device_name: Tiffany iPhone
    name: Tiffany
    picture: Tiffany.png
  - device_name: James Apple Watch
    name: James Watch
    iosapp_installed: False
  - device_name: Cheryl Apple Watch 6
    name: Cheryl Apple Watch
    iosapp_installed: False
  - device_name: Dylan Apple Watch
    name: Dylan Apple Watch
    iosapp_installed: False
  - device_name: Tiffany Apple Watch
    name: Tiffany Apple Watch
    iosapp_installed: False

# --Accuracy Parameters-------------------------------------
gps_accuracy_threshold: 20

**Comment by gcobb321** [comment]
The gps_accuracy_threshold is too low and will lead to many retries.  I use 65. The iOS app uses a ‘sphere of accuracy’ of 100m. That means that it will trigger a zone enter when it gets within 100m of a zone, not inside the zone itself. A higher threshold will be close enough to where you really are.

**Comment by townsmcp** [comment]
@gcobb321 thank you so much for your advice. I thought the lower figure would be mean 20m from the house rather than 20m from the edge of the 100m zone. I have upped the value to 65 as you suggested. Thanks
