### ISSUE TITLE
Tracking multiple devices for one person.

### ISSUE THREAD

**Issue by rainbowkillah** [gcobb321/icloud3#194]
Hello,

So I've been working to fine-tune my settings for a couple of days now and I just can't figure this one little piece out. Tracking multiple devices for **ONE** person.

So background. I have several iOS devices that are allowed to track my location;
Family Sharing List devices that can be tracked >, 
• rainbow_killahs_airpods_pro > Rainbow Killah’s AirPods Pro, Accessory,   
• de_havillands_apple_watch_5 > De Havilland’s Apple Watch 5, Watch, , 
• de_havillands_iphone_12_pro_max_p > De Havilland’s iPhone 12 Pro Max (P), iPhone, 
• de_havillands_apple_watch_6 > De Havilland’s Apple Watch 6, Watch, 
• de_havillands_iphone_12_pro_max_b > De Havilland’s iPhone 12 Pro Max (B), iPhone
• de_havillands_ipad_pro > De Havilland’s iPad Pro, iPad, 
• kstadmins_macbook_pro_2 > KSTAdmin’s MacBook Pro (2), MacBookPro, 

Preferably I would like the iPhone and their watch pairs to be enabled. The preferred phone/watch pair to be tracked is phone (b)/watch_6. I'm currently using the below config

"# --Track Devices Parameters for De Havilland-----#"
devices:
- device_name: de_havillands_iphone_12_pro_max_b
  name: De Havilland
  email: djfox8705@gmail.com
  tracked_devices:
   - device_name: de_havillands_iphone_12_pro_max_p
   - device_name: de_havillands_apple_watch_5
   - device_name: de_havillands_apple_watch_6
error: 
-- sys event --	23:49:11	-	-	-	-	-	iCloud3 Error > Invalid configuration parameter > , • Parameter .. - tracked_devices: [OrderedDict([(`device_name`, `de_havillands_iphone_12_pro_max_p`)]), OrderedDict([(`device_name`, `de_havillands_apple_watch_5`)]), OrderedDict([(`device_name`, `de_havillands_apple_watch_6`)]), OrderedDict([(`device_name`, `de_havillands_ipad_pro`)])] , • Valid values - device_name, email, picture, name, inzone_interval, track_from_zone, iosapp_suffix, iosapp_entity, iosapp_installed, noiosapp, no_iosapp, • Resetting to - 

Ok so went back and reread the config guide and then I tried with the following and still no luck
"# --Track Devices Parameters for De Havilland-----#"
devices:
- device_name: de_havillands_iphone_12_pro_max_b
  name: De Havilland
  email: djfox8705@gmail.com
  tracked_devices:
   - iPhone
   - Watch

I've searched through the issues and read over #62 #92 #24 I really feel like the answer is right in front of my face but just hasn't bit me yet. Any assistance would be greatly appreciated. 

-Thanks

**Comment by gcobb321** [comment]
The `tracked_devices` parameter is an old parameter that has been depreciated/deleted. It was a single line parameter that was replaced by the ` devices ` parameter with the `- device_name` parameters below it. The `device _name` Specifies the iCloud and iCloud3 devices to be tracked. iCloud3 is not set up to track multiple physical devices tied to one iCloud3 device. 

I’m in the middle of rewriting iCloud3 to turn it into a full Integration and working in that area now. I’ll give some thought to tracking a watch and phone together.
