### ISSUE TITLE
iCloud authorization

### ISSUE THREAD

**Issue by ahartman** [gcobb321/icloud3#20]
I know of a authorisation method in iCloud that you do not discuss and that is much easier to use. A user can generate a 'app-specific password' in iCloud; username plus app-specific password give access to the iCloud API avoiding all hassle with 2fa.

I use Home Assistant in combination with Node-Red; I have beenusing a Node-Red plugin that access my iCloud calendars for many months ago based on this 'app-specific-password' access without any problems.

Hope this helps in making your plugin better and easier to us.
Regards, ahartman

**Comment by gcobb321** [comment]
I checked out the app specific authorization a long time ago and found out that it only interfaces with iOS apps, not python programs running on a computer. I haven't used Node Red but would like to check it out when I get a chance. What is the Node-Red plug in name that does the interface?

**Comment by ahartman** [comment]
Dear Gary,
The name of the Node-Red plug in is node-red-contrib-ical-events.
It used to give access to 'unsafe' shared calendars only, but I cooperated with the author and he coded secure access, i.e., with the app-specific password successfully. It works perfectly.
Regards, ahartman, belgium

**Comment by SaturnusDJ** [comment]
@gcobb321 
Any update on this?

App-specific passwords should work for any AppleID sign in I think. I used it with their own iCloud for Windows, as well as in the native Windows Mail/Calendar programs. But I do not know how much access it gives.

**Comment by gcobb321** [comment]
No thing has been done on this.

**Comment by SaturnusDJ** [comment]
Okay. I found Apple and another site mentioning it can be used for ‘mail, contacts, and calendar’. Seems like it does not give enough access.

Trying/Tried to get it working without having to tell friends to add ‘a weird new account’ to their fmf list haha.

**Comment by gcobb321** [comment]
The latest beta v2.2.0 Release Candidate 11b supports 2fa accounts and lets you set up fmf on your regular account without adding a non-2fa one. 

Download the installation zip file [here ](https://github.com/gcobb321/icloud3/tree/master/v2.2.0-Release%20Candidate)
Full Change Log is [here](https://github.com/gcobb321/icloud3/blob/50dd0d9c46f4832864eb695be1916d221ca3354c/v2.2.0-Release%20Candidate/CHANGELOG-RELEASE%20CANDIDATE.md)
v2.2.0 Documentation is [here ](https://gcobb321.github.io/icloud3_docs/#/)
Installation instructions are [here ](https://github.com/gcobb321/icloud3/blob/700b9cc5d2208f02d14a39df616fe6a742ec9af4/v2.2.0-Release%20Candidate/CHANGELOG-RELEASE%20CANDIDATE.md)

**Comment by SaturnusDJ** [comment]
Thanks. Things are happening now.
The 2fa code that iPhone shows should not be entered somewhere?
And I am trying to set it up so that the person to be added to the system can be added without linking to any existing app or device tracker entry.

**Comment by gcobb321** [comment]
This is the link to the v2.2.0 docs that explains it. Go [here](https://gcobb321.github.io/icloud3_docs/#/chapters/1-getting-started?id=authenticating-your-icloud-account). The rest of the docs are close but not completely done yet. Ignore the part about the iOS App device name. It no longer applies.

**Comment by SaturnusDJ** [comment]
Thanks.

So I should get a 6 digit code by text. Not getting it, also no notification in HA.
Log:
```
custom_components.icloud3.pyicloud_ic3.PyiCloud2SARequiredException: Two-Step Authentication (2SA) Required for Account bla@icloud.com
```

But in the lovelace card it says:
```
iCloud Account Authentication Successful
```
So maybe that is good, but it does keep asking for the login on iPhone every HA restart.


```
  - platform: icloud3
    username: bla@icloud.com
    password: 'realpass'
    tracking_method: fmf
    track_devices:
      - Contact_Name_As_Appears_In_FMF_App > friendsrealmail@icloud.com
```

Error given:
```
iCloud3 Setup Error > > The iOS App device_tracker entity was not found in the Entity Registry.CRLFDevice_tracker entities (suffixes) found -
```
which makes sense bc not a HA user.

**Comment by ahartman** [comment]
Hallo all,

I am a using an app-specific password to give a Node_Red node access to one of my iCloud calendars securely.
You should NOT get the 6-digit code for an app-specific password, the iCloud account owner got the 6-digit thing when login in to generate there app-specific password. You also do not use a user name, just the app-specific password.

Regards, ahartman, belgium

**Comment by SaturnusDJ** [comment]
@ahartman 
Yes thanks, we are past the app specific passwords now as they can only be used for email, contacts and calendar.
