### ISSUE TITLE
"Discarded > No location data" error

### ISSUE THREAD

**Issue by leonvdbeek** [gcobb321/icloud3#200]
I have an issue where a phone that seems to be correctly set up according to the logs using the FmF method throws an "Discarded > No location data" error.

I worked a couple of weeks ago but seems to have stopped working randomly.

Here are the logs, I subtracted some email addresses and names:
[icloud3-event-log.txt](https://github.com/gcobb321/icloud3/files/8178964/icloud3-event-log.txt)

I hope someone is able to help me with my issue.

**Comment by gcobb321** [comment]
This message indicates that the iPhone is not providing location updates to your iCloud account, which is retrieved by iCloud3. 

Change the tracking method from Find-my friends to Family Sharing. The FmF method for the iCloud Account owner actually passes the location data back through the Family Sharing list.

For the FmF info...

Setting App - 
--------------
1. Make sure Settings > Privacy > Location Services > Home Assistant is set to 'Always'

Find My App - 
--------------
1. People Tab - Make sure you are listed.
2. Devices Tab - Make sure your device is listed.
3. Make sure your device is showing on the displayed map and make sure it can be located. 
4. Me Tab - Make sure My Location is set to this device and make sure Share My Location is on.

iCloud Account -
1. Make sure you are in the Family Sharing List ( Event Log shows you are but verify anyway).

**Comment by leonvdbeek** [comment]
Thanks for the info!

I actually had 2 phones with the exact same name on the account, which (as stated in the docs) doesn't work.
So after changing the name in the phone and moving to Family Sharing it works again.
