### ISSUE TITLE
Stationary zone name

### ISSUE THREAD

**Issue by groenmarsmannetje** [gcobb321/icloud3#201]
When a device is stationary for a while then a stationary zone is created.
Other (non iCloudv3) devices in that same zone will get that zone name too.

The name of the zone is generated by iCloudv3, but I would prefer to customize that name.

Reasons for that is:
1. It get's a name that is not in the local language
2. It get's a technical name that is good enough fo a system developer but not for an end-user
3. When you use tts notifications when a device enters or leaves a zone then these names cannot be pronounced well in local language

Is this possible? I was not able to find this in the documentation.

I also tried to set it up in customize.yaml like below, but that didn't work either.

```
zone.iphone_nelleke_stationary:
  friendly_name: iPhone Nelleke zone
```

**Comment by gcobb321** [comment]
It is not possible to change the stationary zones name. However, I am working on the next major release of iCloud3 and will add this to the feature list. 

1. The zone name is the device name (iphone_nelleke) + ‘_stationary’ (iphone_nelleke_stationary). Does that work for you? There is a lot of code that looks for ‘stationary’ in the name that would be difficult to change. 
2. If not, would changing the ‘_stationary’ text to some other text and was customizable work? It would have to be the same on all phones or devices.
3. Would just being able to customize the stationary zone Friendly Name that is displayed on the Event Log for each phone be ok? That might be the easiest to do.

**Comment by gcobb321** [comment]
v3 lets you customize the Stationary Zone name that is displayed
