### ISSUE TITLE
Icloud3 not showing up 

### ISSUE THREAD

**Issue by jwiltjer** [gcobb321/icloud3#202]
When downloading the icloud3 repository via the HACS UI it will never show up in the list of available integrations. 

-Icloud V2.4.7 installed
-hacs V1.23.0 installed
-rebooted and cleared cache + cookies

Other custom integrations do show up and are available for installation.

As a last resort I've flashed the PI with a new image from HA, installed HACS then downloaded icloud3 on a 'fresh' HA instance. But this showed same behavior; not showing up for installation

Any ideas how to get the icloud3 installed?

**Comment by gcobb321** [comment]
iCloud3 is not yet set up as an integration and is configured using the configuration.yaml file. Go to the iCloud3 documentation [here](https://gcobb321.github.io/icloud3/#/README) for information on how to set up and use iCloud3.

I am working on rewriting iCloud3 as a full integration and hope to have it release this summer.
