### ISSUE TITLE
Doesn't receive two step Account Authentication Configurator

### ISSUE THREAD

**Issue by lhlxx2010** [gcobb321/icloud3#207]
I can't receive the two step Account Authentication Configurator. It didn't appear in the notice column. I try my another apple ID, it work well... So I don't know what happen by my own apple id. I try to find the apple genius bar. They can not solve this problem...
When i use the icloud in HA (not icloud 3), the issue is "unknwon error occurred". Kindly find it in attachment.
PS: I can receive the two step Account Authentication Configurator on my iphone. Just i don't have any place to fill in.

![657c96b2fc06ba09797b8a8dd401c7a](https://user-images.githubusercontent.com/74414383/159442311-34d6596e-371b-479b-9450-17d28d5fa29d.png)

**Comment by gcobb321** [comment]
This screen shot is for the iCloud integration, n not iCloud3. In iCloud3, use the `Reset iCloud Interface’ option to clear all cookies, close the iCloud account session and request a new verification code. It’s at the bottom of the Event Log > Actions list. See the iCloud3 docs [here](https://gcobb321.github.io/icloud3/#/chapters/1.2-getting-started?id=how-to-force-an-immediate-authentication-request for more info. )

**Comment by Xavier9896** [comment]
> This screen shot is for the iCloud integration, n not iCloud3. In iCloud3, use the `Reset iCloud Interface’ option to clear all cookies, close the iCloud account session and request a new verification code. It’s at the bottom of the Event Log > Actions list. See the iCloud3 docs [here](https://gcobb321.github.io/icloud3/#/chapters/1.2-getting-started?id=how-to-force-an-immediate-authentication-request for more info. )

I used to be able to use it normally (around May 2021), but now I have the above problem after reinstalling homeassistant. I tried installing using HACS or Releases, I also followed the documentation to clear cookies and restarted HA, unfortunately the problem was not resolved.
Finally, I tried to log in to my account at `https://www.icloud.com/`, I received the second verification, but the page prompted me to log in at `https://www.icloud.com.cn/`.
I tried to modify the domain name in `pyicloud_ic3.py`, but the problem remains, and I don't know how to solve it.
<img width="500" alt="image" src="https://user-images.githubusercontent.com/34981520/161295014-f43467a6-9986-48af-b9e2-97700ca25ec7.png">

---- Translated from Google

**Comment by zhxiaoping** [comment]
> 

I got same problem, bro, I think it just because our app id is for china, when I switch to America app id,
 the two step Account Authentication displayed at notification on HA, it work well

**Comment by Xavier9896** [comment]
> > 
> 
> I got same problem, bro, I think it just because our app id is for china, when I switch to America app id, the two step Account Authentication displayed at notification on HA, it work well

兄弟，在另一个issues中有我尝试解决的一些方案，另一位朋友似乎已经解决了，我这边一直不生效，我暂时已经放弃使用这个库了，给你指个路https://github.com/gcobb321/icloud3/issues/211
------------------
Brother, there are some solutions I tried to solve in another issue. Another friend seems to have solved it. It has not been effective on my side. I have given up using this library for the time being. Let me show you the way https://github .com/gcobb321/icloud3/issues/211

**Comment by gcobb321** [comment]
v3 identifies the location as Shina and automatically adds the .cn to the apple endpoint url's. I hope to have it out as a beta in November. and will let you know when it is available to make sure it works correctly.

**Comment by lhlxx2010** [comment]
> > > 
> > 
> > 
> > I got same problem, bro, I think it just because our app id is for china, when I switch to America app id, the two step Account Authentication displayed at notification on HA, it work well
> 
> ## 兄弟，在另一个issues中有我尝试解决的一些方案，另一位朋友似乎已经解决了，我这边一直不生效，我暂时已经放弃使用这个库了，给你指个路#211
> Brother, there are some solutions I tried to solve in another issue. Another friend seems to have solved it. It has not been effective on my side. I have given up using this library for the time being. Let me show you the way https://github .com/[/issues/211](https://github.com/gcobb321/icloud3/issues/211)

兄弟，你放弃这个库改用什么了，ha自带的app吗？

**Comment by Xavier9896** [comment]
> > > > 
> > > 
> > > 
> > > I got same problem, bro, I think it just because our app id is for china, when I switch to America app id, the two step Account Authentication displayed at notification on HA, it work well
> > 
> > 
> > ## 兄弟，在另一个issues中有我尝试解决的一些方案，另一位朋友似乎已经解决了，我这边一直不生效，我暂时已经放弃使用这个库了，给你指个路#211
> > Brother, there are some solutions I tried to solve in another issue. Another friend seems to have solved it. It has not been effective on my side. I have given up using this library for the time being. Let me show you the way https://github .com/[/issues/211](https://github.com/gcobb321/icloud3/issues/211)
> 
> 兄弟，你放弃这个库改用什么了，ha自带的app吗？

是的，并且使用ha也只是为了让不支持home kit的设备能够桥接进去，只要在iphone家庭里面能操作设备就好了，实在是懒得折腾了。如果这个库11月份的测试版解决了两步验证的问题，我也是乐意使用的。期待11月份的测试版本。
