### ISSUE TITLE
[Request] Multiple zones for travel time factor?

### ISSUE THREAD

**Issue by KairuByte** [gcobb321/icloud3#216]
I've got two distinct zones that I have automations connected to, that requires more accurate arrival times. Unfortunately, one of the devices associated with the "other" zone does not have the app installed, so I can't rely on zones.

Is it possible to add a second zone to the calculation of the travel time factor, so the closer that device gets to the zone, the more often it refreshes?

As things are, they are many hundreds of miles away from "home", so the current method of calculation when away is pretty useless.

**Comment by gcobb321** [comment]
Another travel_time_factor is not possible. Have you looked at the track_from_zone parameter that can be added to the “other” device. That will let you track from another zone like it tracks from the ‘home’ zone. It sorta works. See the docs [here](https://gcobb321.github.io/icloud3/#/chapters/1.6-configuring-starting-icloud3)

**Comment by KairuByte** [comment]
~~I had taken a look at that, the issue I had with that is that the device has automations in both zones.~~

~~I suppose I could choose the more important zone, and have an automation that kicks off update requests based on the closeness to the other.~~

~~Ultimately the issue is a parent that I want to keep track of to a certain extent, but they are resistant to the app. However I have automations at both their home and my own for when they visit.~~

~~I suppose I could manually change the track_from_zone when I know they are on their way here, or look into having a duplicate device involved....~~

I had completely misunderstood the intent of this config option, I think this might work. Thank you for the advice.
