### ISSUE TITLE
[Problem] Not Show Track List

### ISSUE THREAD

**Issue by sinoon** [gcobb321/icloud3#219]
## First of All

Big Thank for this Powerful Integration ! This is a very complete tool, especially since anyone can learn a lot from the documentation, even without using the Integration.

## Env

- MacOS Monterey 12.3.1 (21E258)
- Docker 4.7.0 (77141)
- Home Assistant Core 2022.5.5
- iCloud3 Device Tracker: v2.4.7

## Problem

I am experiencing a failure to launch iCloud3 Device Tracker with a message that the tracked device cannot be found.

I'm not quite sure what the cause is, I've checked that the device_name provided is correct and there are no conflicts with the iOS App.

I'd like to see a list of devices that I might see via Event Log, as described in the documentation.

However, in the end, I don't see the relevant list from the log message, so I can't tell what I'm doing wrong.

I hope this information will help you determine this, and if you need any information, please feel free to let me know.

Here is a screenshot of the Event Log

![问题截图](https://user-images.githubusercontent.com/6065488/170221129-1fe21d3f-3f00-4086-8c2c-4125b09229d5.png)

I would be very happy if you help me, thanks!

**Comment by gcobb321** [comment]
See Trouble Shooting Startup Errors in the iCloud3 docs [here](https://gcobb321.github.io/icloud3/#/chapters/1.8-troubleshooting-problems?id=troubleshooting-startup-errors) to see if that helps. Check the iCloud account to make sure ‘sinoon’ is in devices listed in the Family Sharing list. It looks like might not be. Maybe it is ‘xiu-yu-xing-zhi’ instead of ‘sinoon’?

**Comment by sinoon** [comment]
Thank you for response!

The device name of `xiu-yu-xing-zhi` is the iOS App read name, not the device name, and I have tryed the `xiu-yu-xing-zhi` name as device name in config_ic3.yaml and got error as screenshot in first commet.

I followed this documentation(Trouble Shooting Startup Errors in the iCloud3) to check for possible errors on my part, and I found that in the log, a missing `iCloud Account Authenticated (#1) > username ...`

this is the demo in document
<img width="928" alt="image" src="https://user-images.githubusercontent.com/6065488/170393834-e0ba48ba-e849-4aae-9d15-f356ab571698.png">

As a comparison, here is the log message in my failure case
![image](https://user-images.githubusercontent.com/6065488/170393965-34369bed-bd46-4715-8cc8-208576e85ed9.png)

Only the underlined parts of them are co-occurring.

I guess maybe there is something wrong with the login part

**Comment by sinoon** [comment]
I guess maybe there is something wrong with the login part.

First, reboot HA, then this prompt will appear on my computer, this point in time and the underlined part of the picture above is basically the same moment
<img width="592" alt="image" src="https://user-images.githubusercontent.com/6065488/170394893-1290d13e-71d3-443a-8c54-0744dab9702f.png">

After that, whether I clicked "Allow" or not, iCloud3's logs showed a failure, meaning that in the few seconds it was waiting for me to authorize, iCloud3 wasn't waiting for an Apple Account to authorize the login, but seemed to skip the process of waiting for authorization and went straight to the stage of getting the list of shared devices.

After that, whether I clicked "Allow" or not, iCloud3's logs showed a failure, meaning that in the few seconds it was waiting for me to authorize, iCloud3 wasn't waiting for an Apple Account to authorize the login, but seemed to skip the process of waiting for authorization and went straight to the stage of getting the list of shared devices

<img width="602" alt="image" src="https://user-images.githubusercontent.com/6065488/170395177-01b1a3c9-34b7-4b55-8fa6-2ca0b505b40b.png">

The whole process is inconsistent with what is described in the documentation, so I speculate that there may be a problem here with login authentication.

Hope this information helps, thanks!

**Comment by sinoon** [comment]
When I went into the code to research and learn, I found that I would encounter errors reported here, with the message

```
  File "/config/custom_components/icloud3/device_tracker.py", line 6607, in _is_authentication_2fa_code_needed
    self._save_event_halog_error(event_msg)
TypeError: _save_event_halog_error() missing 1 required positional argument: 'log_msg'
```

https://github.com/gcobb321/icloud3/blob/3cd83c0a502c3fde92af0de87228e7c923137ebf/development-v2.4.7/device_tracker.py#L6595-L6624

When I changed the code to just run

```py
self._save_event_halog_error("*", event_msg)
```

I'm not sure I'm making the right changes. However, even if I make this change, I still can't log in properly.

**Comment by gcobb321** [comment]
ICloud3 will not wait for the code to be entered and will continue with the set up process. When it detects the iCloud account needs to be authenticated, it issues a notice to HA to display an authentication is needed notification (Orange dot next to the HA notifications in the HA Sidebar).. That allows entry of the code and the actual authentication process then continues. So you have to click HA notifications and then open the verification code entry window to enter the code.

**Comment by sinoon** [comment]
Yep, However, there is no alert message in the HA notification...sad...

**Comment by gcobb321** [comment]
There was another user that had the same problem in April. See issue #211 [here](https://github.com/gcobb321/icloud3/issues/211). Scroll down to around April 11. There was an issue about the Apple end point being used in China has changed. I don’t know if this applies to you but it might be helpful.

**Comment by sinoon** [comment]
Yes, I got this idea with other people, and it works. however, But other people can't log in the same way, so it seems that the problem is not only related to this network request address.

I will close this issue and Thank you for the great works!

**Comment by gcobb321** [comment]
I am working on the next release of iCloud3 and it detects the China country code (cn) and automatically selects the correct iCloud server up address. `https://www.icloud.com.cn/`. Thanks for verifying that it works
