### ISSUE TITLE
Feature request: Change battery icons based on battery level and status

### ISSUE THREAD

**Issue by GizmoGoody** [gcobb321/icloud3#221]
The iOS app integration changes the battery_level and battery_state icons to most closely match the respective states (e.g. mdi:battery-charging-80 at 83% and charging). Can you make iCloud3 do this as well?

Also, can you add a dedicated sensor for the battery status (i.e. pull the battery_status attribute out as a dedicated sensor)?

**Comment by gcobb321** [comment]
These items have been added to the next version of iCloud3.

————————
Gary Cobb
