### ISSUE TITLE
Feature Request: only_track_from_zone or default_zone

### ISSUE THREAD

**Issue by bladecoates** [gcobb321/icloud3#222]
Hi, 

I currently use iCloud3 to track not only members of my household but also my parents who live out of state. It would be nice to set be able to set a default_zone or a only_track_from_zone that will only track my parents from their home. 

Use Case: 

Parents are retired and travel cross country on their motorcycle. They keep their location shared with me for emergencies so I can check on their location without having to call them. They rarely travel my way unless it's a holiday. Currently, I'm using track_from_zone to specify to track from their house for their two phones but it would be nice to tell iCloud3 to ignore my home completely and only track them from their home. 

Thanks for the hard work on this Gary, and for anyone else reading: This is a great solution for anyone that has older parents traveling. They have the ios_app installed as well, with shortcuts setup to trigger a location update/notification when they stop for the night and other automation. My dad will get me to send him a report of the location updates and gps coordinates after their trip so he can mark spots he wants to revisit in the future or routes he really wants to avoid. I have input_booleans setup for driving/not driving, so he even gets an idea of how long they ride vs stop. 

P.S. If you need a tester for the next version I read you posting about it on the forum, please feel free to @ me. I just started digging into the current code base.

**Comment by bladecoates** [comment]
I have considered setting up a separate HA instance at their location or at my location just for this purpose tailored to them, however, I believe there is a good use case for this. My daughter will be going off to college out of state next year so it has applications for that situation as well. I consider this technology similar to the SOS feature already included in IOS, you hope to never have used it, but you'll be glad to have it when you do. My daughter, parents, etc have complete access to track me as well and my daughter appreciates the ability to know I'm ok when I'm traveling for work.

**Comment by gcobb321** [comment]
Right now, v3 always has the home zone as a track from zone   There are a lot of things that go on behind the scenes that require this. Since it will be a true integration, it may be possible to disable your home zone for their  phones thru HA even though iCloud3 still has it as one of their zones. 

Glad it’s working in your situation and keep tuned for the first beta.

**Comment by gcobb321** [comment]
I'll let you know when v3 is available for beta testing. Probably November
