### ISSUE TITLE
Ability to disable GPS tracking for device

### ISSUE THREAD

**Issue by jippi** [gcobb321/icloud3#224]
Hey!

It would be great if there was a way to disable the GPS / zone tracking for a device to avoid a HA iOS zone enter/exit tracking for it. 

**Use-case:** I have my iPhone, Watch and Laptop all tracked by icloud3, but I only need my iPhone to be location tracked, my watch and laptop are just tracked to get sensors like battery status and such for other automations. This doubles as my wife have similar number of devices tracked. 

Having all the `stationary` zones and such created and tracked is noisy and seem to put some battery drain on the iPhone devices to keep track of all of them.

I think the HA iOS app also have 10 as an upper limit of zones to track for, so this limit our own usage of these zones for other stuff

Having an option to simple manage basic sensors and import data from iCloud would be fantastic 

Thanks

**Comment by gcobb321** [comment]
In  iCloud3 v3 under development, you will be able to monitor a device instead of tracking it. That device’s info will be updated When a tracked device is updated.

**Comment by jippi** [comment]
That sounds like it would suit my use-case perfectly if it doesn't create device zones and such - but simply just pull iCloud data into sensors and nothing more :) 

Do you have a rough idea of a timeline for that release?

**Comment by gcobb321** [comment]
In February, I thought it would be ready for beta in May. In April, maybe June. Its now, June and maybe July or august. It’s getting close but I have a couple of troubling issues related to iOS app not responding when in error recovery, finalizing the monitor devices code and a handful of other issues. Plus the documentation updates to explain a few things (all new online configuration). It will go into the development directory of the iCloud3 repository first and I’ll probably post an issue sometime asking for people to try it out. Stay tuned and watch the forum for more info.

**Comment by gcobb321** [comment]
In v3, you can set a device to Tracking, Monitoring or an Inactive mode.
