### ISSUE TITLE
icloud3-event-log-card.js not installed automatically to /config/www/custom_cards

### ISSUE THREAD

**Issue by d-d** [gcobb321/icloud3#225]
The custom card was not installed automatically when installing iCloud3 2.4.7. 
The log showed the error No such file or directory: '/config/www/custom_cards'

**Analysis:**
 /config/www missing

**Workaround solution:** manually create /config/www as an empty subdirectory using the VS code editor then restart HA. When /config/www existed the custom_cards directory was created and the custom card js installed.

**Versions tested:**

iCloud3 v2.4.7 
Home Assistant Core 2022.6.6
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.2

**Comment by d-d** [comment]
![Screenshot 2022-06-15 at 13 59 00](https://user-images.githubusercontent.com/873550/173827306-5d1bae73-acc3-40bd-9075-7a78fee93ec2.png)

**Comment by gcobb321** [comment]
Fixed in v3
