### ISSUE TITLE
ICloud stop working

### ISSUE THREAD

**Issue by giugit** [gcobb321/icloud3#227]
I tried to remove it but know when i reinstall the integration the validation code is not send and i can’t complete it!
Any Idea?

Thanks

**Comment by gcobb321** [comment]
Try Event Log > Actions > Reset iCloud Interface to delete all cookie and icloud session files and force a reauthentication of the phone. But, if the phone was authenticated before the reinstall, you might not have to do it again. If the trackage devices are listed in the Event Log, you should be ok.

**Comment by giugit** [comment]
I removed icloud from .storage now it work again Thanks

**Comment by JuhaFIN1** [comment]
> Try Event Log > Actions > Reset iCloud Interface to delete all cookie and icloud session files and force a reauthentication of the phone. But, if the phone was authenticated before the reinstall, you might not have to do it again. If the trackage devices are listed in the Event Log, you should be ok.

Sorry, but where is this "Event Log > Actions > Reset iCloud Interface". I cannot find this from HA

**Comment by gcobb321** [comment]
The `Event Log > Actions > ` refers to the Event Log that s part of iCloud3. It shows what is going on while tracking a device, tracking errors, iCloud3 start up operations, etc. The iCloud3 docs describe it in several places. The Actions command is a top down button on the Event Log screen and can be seen in the upper right corner. See [here](https://gcobb321.github.io/icloud3/#/chapters/2.5-event-log?id=event-log-locating-devices) for its description.  The Reset iCloud interface is the selection a the bottom of the list and described [here](https://gcobb321.github.io/icloud3/#/chapters/2.5-event-log?id=the-actions-command).
