### ISSUE TITLE
Feature Request: Ignore Locations

### ISSUE THREAD

**Issue by mehhhhhhhhhhhhhhhhhhhhhhhhhh** [gcobb321/icloud3#228]
Upon starting iCloud3, some devices being polled via FmF will appear within Home Assistant's "Home" zone if they don't successfully acquire accurate GPS coordinates.  It would be beneficial to ignore the invalid location data, rather than have the device misreport where it is located.

<img width="464" alt="image" src="https://user-images.githubusercontent.com/63381275/183256516-1e6826ba-0e1a-4822-9d76-c327b24d22ee.png">
This image shows "Dad" located in Washington, where my Home Assistant instance is located.  
This is due to iCloud3 unsuccessfully acquiring the device's location at startup.  Actual location is in Florida.

**Comment by gcobb321** [comment]
iCloud3 v3 under development saves the state of all of the sensors every time they are updated and restores them to that state when it is restarted. It will not reset it to Home before it determines the correct location.
