### ISSUE TITLE
I hope the plug-in can support custom ICloud domain names so that it can be used in China

### ISSUE THREAD

**Issue by Seifon** [gcobb321/icloud3#229]
I hope the plug-in can support custom ICloud domain names so that it can be used in China

Domain used in China:

/confg/custom_components/icloud3/pyicloud_ic3.py
```
AUTH_ENDPOINT = "https://idmsa.apple.com/appleauth/auth"
HOME_ENDPOINT = "https://www.icloud.com.cn"
SETUP_ENDPOINT = "https://setup.icloud.com.cn/setup/ws/1"
```

**Comment by gcobb321** [comment]
iCloud3 v3 determines your location and automatically adds the `cn` suffix to the `HOME_ENDPOINT` In pyicloud_ic3.py
