### ISSUE TITLE
Update docs to reflect applicable device types

### ISSUE THREAD

**Issue by cryogenx** [gcobb321/icloud3#23]
Would it be possible to update the docs with a list of available device types.

e.g. I have , iPad, iPhone,apple watch, MacBook Pro, iMac. etc. what would you call the different devices in the config?

**Comment by gcobb321** [comment]
I'll need your help. I only have an iPhone, iPad and watch so don't know device types for the Macbook, etc. When you start HA, the devices in your iCloud account are gone through to see which ones are tracked based on the include/Exclude filters.  I write entries to the log file for each one with info on if it will be tracked or not. Will you look at your log file to see what the device types they are?

**Comment by cryogenx** [comment]
I can try to do that, after thinking about it I just ended up using iPad and iPhone.
