### ISSUE TITLE
Can you start find my phone  alarm with this plugin?

### ISSUE THREAD

**Issue by MattL0** [gcobb321/icloud3#23]
Thanks

**Comment by gcobb321** [comment]
You might want to post the message again since all it said was "thanks". But the answer is probably "No"

**Comment by MattL0** [comment]
Thank you !

**Comment by gcobb321** [comment]
On second thought, there is a 'Lost Phone' service call that will play an alert on your phone. See [here](https://gcobb321.github.io/icloud3/#/chapters/3-services?id=icloud3_lost_iphone-service) in the iCloud3 docs for information.

**Comment by MattL0** [comment]
Thanks this is what i was wondering

Sent from an Iphone
________________________________

**Comment by MattL0** [comment]
Sorry, juste another question about this. 
I read the section you juste posted to me. It talks about family sharing. So I understand from that, that Send a ‘’lost phone’’ service call to any phone in my family.

My question is :

Can I add a second account to this script? 
So I could use that fonction from the two Iphones without using the family sharing thing?
