### ISSUE TITLE
Problems installing / setting up icloud3

### ISSUE THREAD

**Issue by VentusGallus** [gcobb321/icloud3#230]
Hi guys - I am having trouble setting up the icloud3 integration. I've looked into the reported issues and I see that most issues are a result to 'user-error' (as in: users not reading the instruction manual correctly). I have gone through the installation three times and I am running this on a clean flashed version of Home Assistant to avoid problems with previous installed (icloud) tracking related services. Still, I cannot get it to work.

A short summary of what I have done:

- Clean flashed Home Assistant. No add-ons/ integrations installed other than: DuckDNS, Google Drive Back-up, SSH & Terminal (to install HACS) and File Editor (to edit configuration.yaml). HACS installed and linked to Github account. I successfully downloaded Icloud3 through that. File Editor shows that files are added to config/custom_components. So far so good!

- My issues start at 1.5 of the manual ([https://gcobb321.github.io/icloud3/#/chapters/1.5-installing-icloud3](https://gcobb321.github.io/icloud3/#/chapters/1.5-installing-icloud3)) when I need to install the Event Log card. The folder config/www/custom_cards/ does not exist on my system. So I have manually added these folders. The instruction manual says that if I restart HA, the file 'icloud3-event-log-card-js' will automatically be copied to this folder. However, that does not happen. I have therefore manually copied it to the folder. **Any help here?**

- I have added the 'icloud3-event-log-card-js' as a resource in the dashboard function. I get no feedback whether this has worked but I cannot find the 'card' when setting up a new dashboard. Not sure if this is OK as the manual is not clear on this. **Any feedback is appreciated here!**

- Next issue (also at 1.5 of the manual) is in relation to the additions to 'configuration.yaml' to prevent the recording of the 'sensor.icloud3_event_log'. Manual stipulates to include the following: 

```
recorder:
  purge_keep_days: 3
  exclude:
    entities:
      - sensor.icloud3_event_log 

```
- When I add the wording as listed in the manual, the following pops up in my log:

```
Logger: homeassistant.components.http
Source: helpers/config_validation.py:831
Integration: HTTP (documentation, issues)
[...]
The 'base_url' option near /config/configuration.yaml:14 is deprecated, please remove it from your configuration

```

http and #14 are part of the DuckDNS settings in my confirigutation.yaml and they work fine. They are however, are listed directly above the 'record' additions so I suspect that the error message is related to the 'record'additions. Also, when I remove the recorder test, the log reports no errors. **Any help here?**

 
- 1.6 is about setting up the configuration.yaml file with iCloud username data, etc. I followed the manual here as well but no verification code is sent to my devices. Given the errors that have already popped up, I suspect there error is earlier in the installation so I will pause here.

Many thanks in advance for helping me out. I tried to follow the manual meticulously so do let me know if I interpreted something incorrectly!

**Comment by gcobb321** [comment]
1. The Event Log card ends with `.js`, not `-js`. I looked in the docs and saw a `-js` but that was a typo that has been there for a long time. 
2. The default directory for the Event Log card is `www/custom_cards`.   Verify the directory structure and make sure it’s with an underscore `_`, not a dash `-`. The directory can be changed in the config _ic3.yaml file. Verify it is not something else. You can remove this parameter so it uses the default value. 
3. About the ` recorder ` error. You probably have indented  it so the the http statement is picking it up and giving you the error. It should not be invented at all and the ` recorder ` statement should be on the level as `http`. See the HA divers for info about the ` recorder ` parameter. 
4. The verification code entry is controlled by iCloud. You will get one after you have successfully logged into your account. Check the HA logs to see if you have any other errors.
