### ISSUE TITLE
Where can I find the installation instruction?

### ISSUE THREAD

**Issue by wbarber69** [gcobb321/icloud3#232]
I see in other issues others point out their issues by pointing to specific parts of the installation instructions.  That’s where I’m stumped.  I can’t find any installation instructions.  There’s miles and miles and miles of features, and pages talking about all the wonderful things this integration can do, but I see no documentation in the HACs page, I see nothing in my own installation other than a single example ic3 config file where literally every single line is commented out.  So I have not one single clue where to start with this integration.  And I’m getting pretty frustrated with the built in iCloud integration and it’s nonstop re-authorization pop ups. So if anyone would be so kind as to point to the actual installation instructions I’d be very thankful.

**Comment by gcobb321** [comment]
Go [here](https://gcobb321.github.io/icloud3/#/chapters/1.1-quick-start-guide) installation instructions. It’s in the Getting Started section of the docs
