### ISSUE TITLE
No devices to track even though names match returned icloud family sharing list

### ISSUE THREAD

**Issue by Perkinje** [gcobb321/icloud3#233]
I've checked and rechecked that the names are the same between my config.yml and the icloud family sharing list. Same error.

I've removed all but 1 name to try to simplify finding where I've screwed up to get it matched. Still same error.

This is my config.yml setup
```  
device_tracker:
  - platform: icloud3
    username: !secret icloud_username
    password: !secret icloud_password
    devices:
       - device_name: el_capitan_iphone
         name: El Capitan
         email: !secret icloud_username
```
I was able to authenticate my icloud account without issue.
This is the system log output after restarting icloud3.

```
-- sys event --	10:27:15p	 - Service Call Command Received > `restart`
-- sys event --	10:27:15p	 - Initializing iCloud3 v2.4.7 > Thursday, Sep 15
-- sys event --	10:27:15p	 - Event Log Version Check > Current release is being used. Version-2.4.0 (4/8/2021), /config/www/custom_cards
-- sys event --	10:27:15p	 - iCloud3 Directory > /config/custom_components/icloud3
-- sys event --	10:27:15p	 - iCloud3 Configuration File > iCloud3 Configuration File > config_ic3.yaml not used
-- sys event --	10:27:15p	 - Stage 1 > Prepare iCloud3 for ***@mac.com
-- sys event --	10:27:15p	 - inZone Intervals > inzone_interval-2 hrs, 
-- sys event --	10:27:15p	 - Set up Zones (zone/name) > 
-- sys event --	10:27:15p	 - Set Initial Stationary Zone Location > 
-- sys event --	10:27:15p	 - Set Up Waze > Region-US, MinDist-1 mi (1.61km), MaxDist-1000 mi (1609.35km), Realtime-False
-- sys event --	10:27:15p	 - Stage 2 > Set up tracked device parameters
-- sys event --	10:27:15p	 - Stage 2a > Authenticate iCloud Account, List Trackable Devices
-- sys event --	10:27:15p	 - iCloud Web Services interface (pyicloud_ic3.py) > Verified
-- sys event --	10:27:16p	 - iCloud Account Authenticated (#13) > LastAuth-Never (Initializing), Method-TrustToken/ServiceLogin
-- sys event --	10:27:16p	 - Friends in the FindMy app data that can be located > 
-- sys event --	10:27:17p	 - Family Sharing List devices that can be tracked >, • el_capitan_iphone > El Capitan iPhone, iPhone, 
-- sys event --	10:27:17p	 - Stage 3 > Identify iOS App entities, Verify tracked devices
-- sys event --	10:27:17p	 - Entity Registry mobile_app device_tracker. entities found >, • el_capitans (El Capitan iPhone)
-- sys event --	10:27:17p	 - iCloud3 Error for ***@mac.com > Setup aborted, no devices to track. Verify the devicename on the `devices/device_name: [devicename]` parameters. They must be the same as `Settings > General > About > Name` on the phones being tracked.
```
I saw one other post have a similar problem and it was an error in their config_ic3.yml file. Any help would be appreciated.

**Comment by gcobb321** [comment]
The setup looks ok but Try putting in the actual names instead of using `!secret`. You said they are in `config.yml`.  Are the parameters actually in `configuration.yaml`?

**Comment by Perkinje** [comment]
Tried with the actual usernames/emails and password with no change. Yes, they're in configuration.yaml. I've also tried multiple iterations of the names without success. Where do I look for additional log/debug info?

**Comment by gcobb321** [comment]
Put `log_level: debug+rawdata` into the config file. That will dump the raw data received from iCloud to the HA log file. That data is used to identify the devices that can be tracked. 

Try putting quotes around the device name parameter in Case of a indisputable character somewhere.

**Comment by Perkinje** [comment]
So it's working now. I found an error in the HA.log stating 
```
homeassistant.exceptions.HomeAssistantError: Secrets not supported in this YAML file
```
When you suggested not using secrets, I forgot to restart HA after swapping out the secrets in the configuration.yaml file. Without using secrets, everything seems to be working. I'm confused why secrets don't work on my setup but other people report being able to use them with icloud3.

**Comment by marceloaf** [comment]
Hi. I noticed you used secrets on username, password and email. Try to use it just in username and password. That's how I currently use and works fine.

**Comment by gcobb321** [comment]
Glad it’s working now. 

In iCloud3 v3, there is no configuration file, all the parameters are updated using configuration screens.  You  create an iCloud3 device to be tracked or monitored with any name you want.  Then select the family sharing, find-my friends and the iOS app device to be used for it from a drop down list of devices extracted from the iCloud account and the HA entity registry. Also, the iCloud account username and passwords are obscured and encrypted.

**Comment by Perkinje** [comment]
marceloaf - I put the secrets back in the configurationl.yaml file but not the config_ic3.yaml file and it's still working. Thanks

gcobb321 - Thanks for the help. Looking forward to v3 when it's available.
