### ISSUE TITLE
Two factor authentication user error - how to fix?

### ISSUE THREAD

**Issue by dcerny1** [gcobb321/icloud3#234]
I received a notice this morning on my iPhone that someone is trying to use my iCloud account and it displayed a verification number to enter on the device that's trying to authenticate. I couldn't figure who could be trying to access my iCloud account so I just clicked OK and the verification code went away. I then noticed that it was HA trying to authenticate and I needed that code to enter in HA. I now don't have the code and HA still wants me to enter the verification code. I tried to get another code on the iPhone, but it's not recognizing that code.

How do I get Apple to provide a new code? I restarted iCloud3 hoping it would help, but it didn't seem to do anything to help. 

Any help would be appreciated.

Thanks, David

P. S. Got a new notification with a new verification code tonight. When I entered it in HA, it told me that the code is not valid. I checked and double checked that the code rec'd was the one entered, but no dice. So now I did get a new code, but can't get past the configurator in Notifications.

**Comment by gcobb321** [comment]
`Event Log > Actions > Reset iCloud Interface` will reset the icl session and Apple should send you a new code. See iCloud3 docs [here](https://gcobb321.github.io/icloud3/#/chapters/2.5-event-log)

**Comment by dcerny1** [comment]
Thank you Gary. That worked. I restarted 

 

Awesome interface. Appreciate all your work on it.

 

David
