### ISSUE TITLE
Hi, is it possible to support the "items" in the iCloud, like Airtag etc.

### ISSUE THREAD

**Issue by goxofy** [gcobb321/icloud3#239]
Thanks @gcobb321 !

is it possible to support the "items" in the iCloud, like Airtag etc.

![image](https://user-images.githubusercontent.com/1695416/201864645-b2cff518-2194-41ca-ba42-1930b08d13fb.png)

**Comment by gcobb321** [comment]
No. They are not accessible through the icl account
