### ISSUE TITLE
Location outside is always showing as NotSet

### ISSUE THREAD

**Issue by groenmarsmannetje** [gcobb321/icloud3#242]
Since December 9th iCloud3 device tracker sensor of the tracked iPhone always give state "NotSet" when phone user is outside of home. The actual location or zone is not reflected anymore.

When I use the "FindMy" app I can still see the actual location of this iPhone device without any issue.

What is causing this?

**Comment by gcobb321** [comment]
Did you get a new phone?

**Comment by groenmarsmannetje** [comment]
No same phone

**Comment by gcobb321** [comment]
Hmm NotSet is the value of the zone and location fields when starting up.
1. Does anything show on the Event Log? 
2. Do any errors show up in the HA log file?
3. Any errors in the HA notification s?
4. Have you restarted HA?
5. Add `log_level: debug` to the iCloud3 parameters to get more info added to the HA log file and see if anything unusual shows up.

**Comment by groenmarsmannetje** [comment]
It seems to be working now. All I did was a restart of HA and on the iPhone device the new iCloud conditions needed to be accepted. It might be that that blocked this.
