### ISSUE TITLE
"Geocoded_Location" stuck? Does not reflect actual location.

### ISSUE THREAD

**Issue by SimoHDK** [gcobb321/icloud3#249]
Currently experiencing an odd issue, where the HASS 'Map' Tab and 'sensor.(device) _geocoded_location do not update, or do so sparodically.

However, the actual device tracking using the lovelace 'Map' card, and Waze distances etc all work just fine! So no issues tracking the devices, it just seems that the _geocoded_location is not updating in alignment with device movements.

Is this because the mobile app controls _Geocoded_location and not iCloud3?

**Comment by gcobb321** [comment]
Yes, the _geocoded_location sensor is an iOS App (mobile_app) sensor, not an iCloud3 sensor. I think there are parameters in the mobile app where you can select the sensors it should update. Maybe that one is off.

**Comment by SimoHDK** [comment]
Hi Gary, thanks.

Is there a way to derive current location from iCloud3? E.g. match lat/long to nearest address?

Cheers!

**Comment by gcobb321** [comment]
No. That is not something I was planning on doing since it’s available with the iOS app. There must be some issue with the iOS app.

**Comment by SimoHDK** [comment]
Hi Gary - I've been playing with the app settings and the likes, very clear that the geocoded location performance is quite poor, even after attempting to force updates via push notifcations and the likes.

If you could consider adding this in as a feature under iCloud3, that would be awesome. Then there would be 100% alignment and no doubts.

Thanks.
