### ISSUE TITLE
Conflict between device_trackers on HA reboot

### ISSUE THREAD

**Issue by manonstreet** [gcobb321/icloud3#25]
I have two device trackers setup for my iPhone (device_tracker.maximus & device_tracker.maximus_2).  The base maximus device is created with the Mobile App integration and the maximus_2 device is created by iCloud3 via the ioapp tracking method.  The GPS data is captured on the maximus_2 device initially, and then the coordinates along with other iCloud3 specific attributes are written to the base maximus device_tracker entity.  So far, I believe I am describing the standard behavior.

The problem I run into is when Home Assistant is restarted when my iPhone is not in the Home zone.  The maximus_2 device will recognize the device as not_home with accurate coordinates; whereas the maximus device will always show the device as home.  This status will not be corrected for some period of time -- I'm not entirely sure what causes it to eventually synchronize.

**Comment by gcobb321** [comment]
Reopen the issue if it still exists in v2.1
