### ISSUE TITLE
I switched over to icloud3, battery is still an issue

### ISSUE THREAD

**Issue by cryogenx** [gcobb321/icloud3#25]
After switching over to icloud3 from the standard iCloud component, im still seeing severe battery drain on all iCloud connected devices. any ideas on how to lessen this?

**Comment by gcobb321** [comment]
Is your phone doing a lot of polling? Look at the poll count. 
Are you getting a lot of poor gps messages with high counts? Watch the info attribute. 
Retries from old locations info?
Do you have device filters ar tracking all the devices on iCloud  account?
Is the interval small all the time? 15-secs, 30-secs, etc?
Bad cell phone reception?  Or dead zones?
Home or other zones set up? Should set interval to 2 hours when home. 

Those are the first things I would look at.

**Comment by cryogenx** [comment]
Here is a snapshot from the device tracker.

![screen shot 2019-03-05 at 4 13 38 pm](https://user-images.githubusercontent.com/731595/53837877-b0acc100-3f61-11e9-8d6c-43af9fbd9884.png)

**Comment by cryogenx** [comment]
I did notice this though: 
![screen shot 2019-03-05 at 4 14 48 pm](https://user-images.githubusercontent.com/731595/53837922-cfab5300-3f61-11e9-99fc-ca0338b78709.png)

that seems to be the old tracker from the original iCloud integration. any idea how to remove it?

**Comment by jebeke65** [comment]
![screenshot 2019-03-05 22 42 05](https://user-images.githubusercontent.com/47870698/53839556-2764b100-3f98-11e9-9fe7-74a13b52d835.png)

**Comment by gcobb321** [comment]
Several ways...
1. You can have an "include_device: device name" for only the devices you want to track.
Or
2. You can have an " include_device_type: iphone" and "exclude_device: iphone_gw" for example..

**Comment by cryogenx** [comment]
I managed to get rid of that old tracker by removing it from known_devices.yaml and restarting HA. I'll test this and see if it goes any better this evening, I'm currently in a "George Work" zone as I have been most of the day. I went from 100% to 12% from 7am - noon and my Apple Watch which normally last 1.5 days minimum was at 27% by noon.. 

ill keep updating this as I find more

**Comment by cryogenx** [comment]
another note, I did expand my "work" zone by about 100 meters as I was popping in and out due to wandering around the office complex.

**Comment by cryogenx** [comment]
So when I was home last night the battery deception was minimal. hoping to see the same trend at work today

**Comment by cryogenx** [comment]
antlers question, I have three iPads for my kids that im tracking: 

![image](https://user-images.githubusercontent.com/731595/53885680-5442b380-3fec-11e9-9b68-342f9fa1f5ac.png)

will these need the HA app installed?

**Comment by gcobb321** [comment]
The biggest be benefit of using the iOS app is the zone enter and zone exit notifications that are sent to HA and processed by iCloud3. There are also Background Fetch and Significant Location Change notifications which also update the location of the devices. This reduces the need to request the devices location from the iCloud account, which reduces the battery usage.

**Comment by cryogenx** [comment]
so after testing today, when im "in zone" the battery drainage is MUCH LESS, however between zones when it switches to 15sec polling the battery tanks VERY quickly

**Comment by gcobb321** [comment]
Thought you'd like to know...

v1.0 of iCloud3 is now available for download

Go here  <https://github.com/gcobb321/icloud3>to download the latest 
version of iCloud3 and to review the documentation on the github.

A full list of changes enhancements since 0.86 are described in the 
ChangeLog.The Readme describes the functions and features of iCloud3 and 
contains many examples on how it provides a complete presence detection 
solution for Home Assistant.

Good luck. Let me know if you run into problems.

Gary



------ Original Message ------

**Comment by gcobb321** [comment]
See if it still persists in v1.0
