### ISSUE TITLE
Battery level goes to zero when updating location too often

### ISSUE THREAD

**Issue by myMartek** [gcobb321/icloud3#251]
When I use the service to update a devices position multiple times in a row with just waiting a few seconds I get an error message like the following:

```
Discarded > Requesting iOSApp Location #1 > LastLocTime-23:53:04 (59 sec ago), LastRequested-23:53:30 (34 sec ago), OldLocThreshold-10 sec, GPS-(49.713949, 8.699313), NextUpdt-23:54:30, OldLocPoorGpsCnt-#0, DiscardCnt-#12
```

In general this is correct but the battery level for this device also goes to zero but should simply stay at its old value I guess.

**Comment by gcobb321** [comment]
This has been addressed in version 3, now in beta testing. See [here](https://github.com/gcobb321/icloud3_v3/issues/2) for more info and links to the beta releases and documentation.

**Comment by myMartek** [comment]
Thanks for the info. I tried v3 but for now I switched back to 2 since I had too much issues with the new version.
