### ISSUE TITLE
Failed to enter apple 2fa authentication code in the configurator

### ISSUE THREAD

**Issue by jainpj** [gcobb321/icloud3#252]
iClould3 setup with apple id and password., restarted iCloud3 and ir prompted on my apple device with a code. I eneterd the code in HA, Notification, but i receive this error
**configurator.apple_id_verification_code: this entity is unavailable**

On the iCloud Log following alert was found:
**iCloud Alert > FmF or FamShr tracking method is disabled until verification has been completed. iOS App tracking method will be used.**

I looked into the HA logs and found this:
```
This error originated from a custom integration.

Logger: custom_components.icloud3.device_tracker
Source: custom_components/icloud3/pyicloud_ic3.py:239
Integration: icloud3 (documentation, issues)
First occurred: 08:33:13 (4 occurrences)
Last logged: 19:46:43

Authentication needed for Account (Status Code 421)
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 6779, in _setup_tracked_devices_for_fmf
    self._log_rawdata("iCloud FmF Raw Data - (api_friends.data)", api_friends.data)
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 1079, in data
    self.refresh_client()
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 1006, in refresh_client
    req = self.session.post(self._friend_endpoint, data=mock_payload, params=params)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 177, in request
    return self.request(method, url, **kwargs)
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 179, in request
    self._raise_error(response.status_code, response.reason)
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 239, in _raise_error
    raise api_error
custom_components.icloud3.pyicloud_ic3.PyiCloudAPIResponseException: Authentication needed for Account (Status Code 421)

```

Please help. Thanks

**Comment by stsch83** [comment]
Can you explain, how to enter the apple code

**Comment by jainpj** [comment]
Well once you see your apple code on your apple device, click on the notification on the last side bar on home assistant. A link with the name configurator will be appearing there. Click on it and it will allow to enter the code. But it is not working for me. Let me know if it works for you. You need to enable the debug log (iCloud3 Log -> actions -> Enable Debug Log) and start upward to see if it says 2fa verification successful or not.

**Comment by stsch83** [comment]
i get no notification to enter the code in ha

**Comment by stsch83** [comment]
now it gone, but i can not enable to debug log. is it possible to do this in yaml?

**Comment by jainpj** [comment]
**First click on the side and click on Notifications**

board<img width="289" alt="Screenshot 2023-02-09 at 20 27 06" src="https://user-images.githubusercontent.com/40053567/217929552-f88d3c7e-bfbd-4891-b2c1-5fedb2bd190d.png">

<br>**Then you see should see the Configurator. Click o Configure.**

<img width="495" alt="Screenshot 2023-02-09 at 20 27 15" src="https://user-images.githubusercontent.com/40053567/217929576-3b9c555e-3baf-4bf7-a25c-2011ff2c1292.png">

<br> **You should now see this to enter**
<img width="620" alt="Screenshot 2023-02-09 at 20 27 36" src="https://user-images.githubusercontent.com/40053567/217929591-a7eb3682-cc96-4c22-9f68-e4642626dc64.png">

<br><br>If you are not seeing this option, can you conform if you are receiving 2fa notification on your trusted apple device and a code is displayed on that device. if not check your apple login credentials. Otherwise I have no clue.

**Comment by stsch83** [comment]
thx, for your answer. it seams to work for me. i get no error from the integration after entering the 2-fact-code

**Comment by jainpj** [comment]
Yeah not sure what a I getting this.

**At 8:27:45 It says 2f2a  completed successfully**<br>
<img width="523" alt="Screenshot 2023-02-09 at 20 42 09" src="https://user-images.githubusercontent.com/40053567/217934752-7dde65bc-e578-4252-9e68-a5a45779c156.png">

**Then at 8:27:49 it says, verification not completed**

<img width="507" alt="Screenshot 2023-02-09 at 20 43 50" src="https://user-images.githubusercontent.com/40053567/217935083-aeb0412b-bd3d-4800-926a-d3d1c3102d4b.png">

And its definitely not updating the iPhone status

**Comment by gcobb321** [comment]
If all else fails, you can reset the iCloud interface and start all over. This will delete all cookies and session trust tokens and ask for a reverification. 

Event Log > Actions > Reset iCloud Interface (at the bottom). 

You should see the 6-digit verification alert on the phone and the notification bell. Then do donfigure, enter the code, submit like you have been doing again.

**Comment by jainpj** [comment]
I have reset the iCloud3 at least 10 times, it succeed but then fails and devices doesn't get updated.

**Comment by gcobb321** [comment]
It’s hard to know why the code is being accepted. That’sall under Apple control. Try opening the iOS app on the phone that is getting the code. Bring up the notifications > configuration, etc and enter it on that device.

————————
Gary Cobb

**Comment by jainpj** [comment]
Nothing on the iOS app. it gives a code, i enter it in the HA, and the first log says (not in exact words)

entered code xxxxx
code send to apple ...
Verification true

And then later it says 2f2f failed reverting to iOS App tracking method.

**Comment by gcobb321** [comment]
The iOS app will display the HA menu icons on the left edge, just like the browser connected to your HA machine the notification icon is on the bottom left.

It’s this a new install? What device are you running HA on? Does it sit behind a firewall, proxy server, virtual machine or is it a plain Rpi running hass. What version of HA are you on?

————————
Gary Cobb

**Comment by jainpj** [comment]
I have installed it onto an QNAP NAS within virtual containers. So it is basically the HAOS VirtualBox (.vdi) virtual image. I only installed it few weeks ago. It works fine and I do not have much installed, I installed iCloud integration but removed it before installing iCloud3. I followed the instructions for iCloud3 installation as throughly as I could.

Nothing on the IOS app's notification.

If I want to rollback iCloud3, what is the process?

**Comment by gcobb321** [comment]
The last guy that had similar problems was running HA in a VM on Proxmox, (HAOS 9.5). You can find his experience [here](https://github.com/gcobb321/icloud3_v3/issues/63). I have no experience with using your type of environment (I’m on a RPi with Nabu Casa for away from home access. I suspect the posting of the session messages with the 2fa code is not getting back to Apple so the session tokens are never updated permanently. That’s why I suggested you enter the verification code through the iCloud3 configuration screens on a device that is not going through your vm and network setup. You can enter the code of the iCloud3 Configurator > iCloud Account setup screen or through the Action screen without getting the notification from HA. 

To roll back, reinstall iCloud3 from HACS

**Comment by jainpj** [comment]
Thanks Gary
Really appreciate your efforts and its a good add on for iphone based location service. Installation is a bit difficult, but I am fine with that, only needs to be done one :-).

I read the thread and I think the setup and issue are similar to mine.

What I think I need to do is instead of adding the authentication code from our laptop browser, i access the configurator from the iPhone and give it a go.

But looking at the solution proposed by @townsmcp

> Think I have fixed the issue. I uninstalled the integration, removed the iCloud3 directory from custom_components, removed the HACS iCloud3 integration from HACS store, rebooted, created the iCloud3 directory, populated with all beta 11 files, rebooted, added integration, rebooted and then went into the config. 2 hours now and no iOS pop up on watch, iPad, iPhone or OSX apart from the initially pop up to setup authorisation

So, my questions are

>  I uninstalled the integration?

- Do you have any idea what integration he removed?

> Removed the HACS iCloud3 integration from HACS store

- I can't find a way to remove iCloud3 installation. How do i remove the iCloud3 integration?

I think I want to start refresh again.

Many thanks

**Comment by townsmcp** [comment]
@jainpj the iCloud3 integration from Settings -> Devices and Services. Click the 3 dots and select Delete. 

To start fresh, also remove the custom_components directory and HACS install

**Comment by jainpj** [comment]
Okay reinstalled and I think it is working.

<img width="500" alt="Screenshot 2023-02-11 at 12 40 40" src="https://user-images.githubusercontent.com/40053567/218258687-4a374f96-72fb-4afb-b199-fae8a9f4f9c9.png">

And there is no messages later saying Failed to authorise, revert back to IOS App tracking
Must have been a crapy install before.

Juts to be noted, I didn't need an Phone to enter the code. I just used the laptop to enter the authentication code and it worked.

**One last issue**
So I have configured all my devices with email id
```
  - device_name: person1s_iphone
    email: person1@email.com
    name: "Person1's iPhone"
  - device_name: person1s_apple_watch
    email: person1@email.com
    name: "Person1's Apple Watch"
    iosapp_installed: False
  - device_name: person12s_iphone
    email: person2@email.com
    name: "Person2's iPhone"

```

All these devices are in FindMy. I was expecting them to be tracked using fmf, but in the log I am seeing them tracked via famshr method.

<img width="481" alt="Screenshot 2023-02-11 at 13 02 38" src="https://user-images.githubusercontent.com/40053567/218259561-34f49f59-ca1b-4912-b4a3-eab29af81e4c.png">



Is "Find My Friend" different from people available on FindMy?

**Comment by gcobb321** [comment]
Glad you have it working. FmF (for people not in the Family Sharing list) is different than  FamShr (for those that are in the list). FamShr is given priority, is a little faster and gives location data that's a little newer. If there is a phone using FmF and not FamShr, the FmF data is returned for the FamShr phones and would be used then. Otherwise, it’s not

**Comment by jainpj** [comment]
Okay got it. Thank you.

**Two last questions** 

- If the iOSApp is not disabled in the iCloud3 device config, I am assuming the iCloud3 is not polling the iOSApp separately. Rather it uses the data pushed by iOS app  in HA server. Is this assumption right?
-  The iCloud authentication will require a refresh in say 2-3 months. is there a way in HA to send me an email when this happens?

**Comment by gcobb321** [comment]
1. iCloud3 monitors the iOS app device tracker and last update entities for changes. It does not normally ask for the location
2. No

**Comment by jainpj** [comment]
Thank you
