### ISSUE TITLE
Question: What's new in V3?

### ISSUE THREAD

**Issue by filikun** [gcobb321/icloud3#255]
Hi! I just found this project and it really looks awesome! As I see there is beta testing (on a smaller scale) going on for V3 so I was just curious to what's new or is it a complete rewrite? Should one hold out for V3 or jump on V2 and will it be easily to migrate to V3  when the time is done? 

Thanks!

**Comment by gcobb321** [comment]
See some notes about trying the beta [here](https://github.com/gcobb321/icloud3_v3/issues/2#issue-1501595845)
The v3 docs, which need to be updated, are [here](https://gcobb321.github.io/icloud3_v3/#/)
There 
There is a v2 to v3 migration that happens on the first install
