### ISSUE TITLE
Not receiving a code for 2FA authentication

### ISSUE THREAD

**Issue by sandernaus** [gcobb321/icloud3#256]
When setting up icloud3 in HA and configuring my Apple ID, I'm not receiving a notification which contains a code for 2FA.

Only receiving a notification about the weblogin using my Apple ID. This notification only gives me to option to approve/deny.

Already tried the following:

- Reset iCloud interface
- Removed the .storage/icloud folder
- Reinstalled icloud3 in HACS

Any suggestions are welcome :)

**Comment by gcobb321** [comment]
The 2fa request is sent from HA which is a web app. Click allow and you will get the code.

**Comment by sandernaus** [comment]
Unfortunately I don't get any code.

This is the pop-up I get, translates to: "Your Apple ID '******' is used to log in to your account. -> OK/Not Me
After that, I don't receive any code whatsoever.

![IMG_6081](https://user-images.githubusercontent.com/714779/223380895-b634fa91-6860-4fe1-8a15-a90f8ad8c9e7.jpg)

**Comment by gcobb321** [comment]
That code may have expired since Apple controls all of that. Try doing a Event Log > Actions > Reset iCloud interface again

**Comment by sandernaus** [comment]
Already tried that, also removing the icloud folder and even re-installing icloud3 completely.

Suspect it's some kind of cache issue, but not sure where to look or what to clean up.

**Comment by everdrift** [comment]
You can generate a code on your device; go to apple ID->password and security-> on the very bottom "receive verificationcode"

**Comment by sandernaus** [comment]
Just realized, I'm using physical security keys for 2fa, which was recently added to Apple ID.

Tried creating an app password but that did not work as well.

Any other ideas, besides removing the physical security key setup?

**Comment by gcobb321** [comment]
No, that is the only option.

**Comment by belangp** [comment]
I have the exact same problem using physical keys. Only get the notification and no way to authenticate icloud3

**Comment by gcobb321** [comment]
Physicals keys do not work with iCloud3, HA or the HA iCloud integration.

**Comment by sandernaus** [comment]
After removing the physical keys, I was able to authenticate.
