### ISSUE TITLE
Not seeing how to add icloud3 Lovelace card

### ISSUE THREAD

**Issue by ifuchs** [gcobb321/icloud3#257]
I added the dashboard resource of /config/custom_components/icloud3/icloud3-event-log-card.js. However the documentation for icloud3 says after adding the resource "You will now be able to add the Event Log to your Lovelace cards." How exactly do I do that?
If there is a better place to ask this sort of installation question, please let me know.

**Comment by gcobb321** [comment]
See [here](https://gcobb321.github.io/icloud3/#/chapters/1.7-setup-lovelace-event-log-card?id=add-the-event-log-to-a-lovelace-card) in the iCloud3 Docs on setting up a lovelace card with the Event Log
