### ISSUE TITLE
message:"Invalid handler specified"

### ISSUE THREAD

**Issue by DvdEnde** [gcobb321/icloud3#259]
after copying the icloud3_v3 files to the custom_components/icloud3 folder, I tried to install the integration from "Add Integration" and select icloud3 v3.  After this the message "Config flow could not be loaded: {"message":"Invalid handler specified"}" show up.  

Version 2.4 was installed before. Have I overlooked something?

**Comment by gcobb321** [comment]
1. What beta version of v3 did you install?
2. Did you restart HA after copying the files to the icloud3 directory? and then add the integration?

Beta 15 is the latest. [Find it here](https://github.com/gcobb321/icloud3_v3/releases)

**Comment by DvdEnde** [comment]
In installed beta version 15 (3/18/2023) and restarted HA.

FYI I first deleted the old icloud3 folder in config before copying the new files.

**Comment by gcobb321** [comment]
That’s some type of HA error message I have not seen before. 
Were you able to get into the Configuration?
Does it give you that error every time? Or just that one time after the I install?
Did it go away and work normal after the restart?
Can you look at Settings > System > Logs and see the error message? select it to get more detail. 
Is code displayed with error info? If yes, copy and paste here so I can see where it is coming from. If not, look at any errors above and below that one. 

can you delete the iCloud3 integration? And add it again after an HA restart?

**Comment by DvdEnde** [comment]
It was not possible to add the integration. It shows up in the integration menu (see below). After selecting this the error message shows up (see below).  

I have rebooted home assistant and checked the log. There the following message shows up:
![image](https://user-images.githubusercontent.com/114862353/229153109-85ea0786-1fdc-417a-8901-9eb6abdbf8dd.png)

The files installed in custom_components/icloud3 folder are: 
![image](https://user-images.githubusercontent.com/114862353/229153822-be4ffb17-272c-4d8c-9c25-f9564dd50e75.png)

**Comment by gcobb321** [comment]
The file list and error message did not show up. 

I just deleted iCloud3, restarted HA and readded without any problems. The message is coming from HA trying to tie icloud3/config_flow into HA (that is the Integration configured module). 

What version of HA are you running?

**Comment by DvdEnde** [comment]
Version 2023.3.6

![image](https://user-images.githubusercontent.com/114862353/229154485-72d1a49c-ede3-4b61-bd5e-d92d0babc9e5.png)

**Comment by gcobb321** [comment]
Your email replies are not showing anything. Rather than replying via email go to the github issue you opened [here](https://github.com/gcobb321/icloud3/issues/259) and reply directly. Otherwise, I have no information to go on.

Also, give me several integrations you have already installed so I can look at their setup code. By comparing a successful install and what I am doing will help identify the problem and what needs to be done to correct it.

**Comment by DvdEnde** [comment]
See image for overview of integrations
![image](https://user-images.githubusercontent.com/114862353/229154945-8624d927-bc11-4946-a79e-68c7b086a271.png)

**Comment by DvdEnde** [comment]
I have found the solution!  It seems that not all files (and subfolders) were copied. After copying all folders the integration started flawlessly. It also required to copy to custom cards to the correct folder and overwriting the old custom cards.
Thank you for your prompt responses and support!

**Comment by gcobb321** [comment]
Perfect. Glad it is now operational.
