### ISSUE TITLE
Friend list is empty

### ISSUE THREAD

**Issue by sandernaus** [gcobb321/icloud3#262]
In the icloud3 logs in HA, the FmF list is empty, not returning any e-mail/devices.
However, in the find my app on the phone I'm able to track someone, with whom I share locations.

Already tried re-adding each other, remove, re-share, but no success so far.

Enable debug en raw logging from the UI doesn't provide my with more info. 

Any pointers?

**Comment by gcobb321** [comment]
No. The FmF data is not being returned from iCloud using the FmF url request address that we all have been using for years. Apple did something on their end. I have no idea what or how to fix it. FmF appears dead for the time being. FamShr is still available.
