### ISSUE TITLE
iCloud3 Not Working For Past Month

### ISSUE THREAD

**Issue by Colorado4Wheeler** [gcobb321/icloud3#265]
Over the past month my iCloud3 integration has completely stopped working, I don't get locations or device stats (battery level, etc).  Looking at the logs I get constant "Failed to send message" when trying to get locations:

```Requesting iOSApp Location #1 > LastLocTime-3:22:38 (-21263 sec ago), LastRequested-9:28:10 (5 sec ago) > Failed to send message```

and in the HA logs I get this for every device:

```iPhone (iphone) Requesting iOSApp Location #13 > LastLocTime-12:00:11 (-10810 sec ago), LastRequested-7:00:00 (2 hrs ago), May be offline/asleep```

and I also get the following when I go to Settings -> System -> Logs:

```This error originated from a custom integration.

Logger: custom_components.icloud3.device_tracker
Source: custom_components/icloud3/pyicloud_ic3.py:239
Integration: icloud3 (documentation, issues)
First occurred: 9:19:37 AM (2 occurrences)
Last logged: 9:22:37 AM

(Status Code 501)
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 6779, in _setup_tracked_devices_for_fmf
    self._log_rawdata("iCloud FmF Raw Data - (api_friends.data)", api_friends.data)
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 1079, in data
    self.refresh_client()
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 1006, in refresh_client
    req = self.session.post(self._friend_endpoint, data=mock_payload, params=params)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 179, in request
    self._raise_error(response.status_code, response.reason)
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 239, in _raise_error
    raise api_error
custom_components.icloud3.pyicloud_ic3.PyiCloudAPIResponseException:  (Status Code 501)
```

As per some other posts on here, I've removed any reference to "email" in my config file, they are pretty basic.

And this happens pretty much all day every day.  I'm using iCloud3 2.4.7 on HAOS 2023.5.2 (but it's been failing since 2023.3).  This has been rock solid since I installed the very first release of this and I'm not really sure what else I can do to troubleshoot this.  I have reset "iCloud Interface" more times than I can count and it always authenticates fine and I can see that the app can log  into iCloud and seems to get my list of devices without issue, it just doesn't do anything after that.

**Comment by gcobb321** [comment]
The 501 status code indicates the url used to get the fmf data is invalid. I am not able to test this at the moment but try this. 

Edit the _device_tracker.py_ file in the _icloud3_ directory. You will be commenting out the line of code that sets up up fmf. 

Add an asterisk to line 1214 so it looks like this:
```
1213                if self.api:
1214                    #self._setup_tracked_devices_for_fmf()
1215                    self._setup_tracked_devices_for_famshr()
1216                    self._tune_tracked_devices_fmf_famshr()
```
Save the file and restart HA

**Comment by Colorado4Wheeler** [comment]
Gary, thanks for the tip.  My installation doesn't look like that, I don't have an _icloud3 directory nor a _device_tracker_py.  Under custom components I have an icloud3 directory and device_tracker.py, no leading underscores.  Also, that line shows on mine at 1214.  Do I have an incorrect package?

Other than that, it did fix the problem, thank you!

**Comment by gcobb321** [comment]
GitHub uses  underscores for italics. I guess they ended up in the wrong place. I was looking at a 
_device_tracker.py_ On my computer rather than the one on HACS.  I’ll edit my comments in case someone else reads it. 

Glad it’s working now.

**Comment by edautz** [comment]
Got the same issue, and this solves it at once.

Thanks. 

 I wonder should ICloud3 not been modified to deal with it.
Cause the commenting of the line not other issue’s in the future?

**Comment by gcobb321** [comment]
FmF as we know it is dead. Any modifications to support it, if there are any, will require a recode of the complete FmF handler, not just uncommenting this line. Also, they will be only added to v3 (currently in the final beta stages) and not v2.4.7 you are running.

**Comment by edautz** [comment]
Ok. Fair enough.

It would be good to mention this solution in capitals in the readme.

I think other users will be in trouble too.

Great integration you made. One of the only working iCloud device tracking solutions.

I wonder when V3 will be out of beta?

Is there any chance AirTags could be supported?

**Comment by gcobb321** [comment]
1. AirTags-Never, they are not located like other Apple devices. They use Low Energy Bluetooth to transmit the info to other Apple devices. 
2. v3 is pretty solid and almost 400 have downloaded it since beta 15 (now working on beta 17). I’m just touching up the v2 to v3 migration features now.
