### ISSUE TITLE
iPhone alert no longer sends the iphone alert as from iCloud or am I doing wrong?

### ISSUE THREAD

**Issue by turboboost** [gcobb321/icloud3#266]
Earlier when I used the "Actions: Send find my iPhone alert" the phone started to make noise even if muted as per the iCloud functionality but now recently I noticed that it only alerts my Home Assistant app with a quick message/ping.
Is this changed as I really liked the find-my-iPhone better.
Hope the question make sense

**Comment by gcobb321** [comment]
iCloud3 version?. No changes to v2.4.7

**Comment by turboboost** [comment]
So I just updated to V3 and still no iPhone alert sent.
When I go in to the iCloud3 V3 Event Log GUI and choose actions -> "Send Find My iPhone Alert (FanShr)" the message is successful and on my iphone the Home Assistant app kicks in and shows a critical event "Find my iPhone alert".
That is how it is working now.
Previously the iPhone strted with the typical iPhone sound and kept pining for a long time, that sound came from iCloud itself as i understand it. Can I have that behaviour back?
The sound from the Home Assistant app is too short :(
Best regards
Stef

**Comment by gcobb321** [comment]
I just tried it with my phone and it sent the alert directly to the phone. There was the Find My Phone Alert message displayed at the top with constant alert ping until I opened my phone. The ‘ICloud Find-my-Phone Alert sentz’ message was displayed in the Event Log. 

If the FamShr info is not set up for the phone, the ‘iCloud device is not available, the alert will be sent to the iOS App’ message is display In the Event Log.  

- Check the set up for your phone on the Configure Settings > Update Devices screen and verify it is tracked correctly. 
- Review the list of devices on the Family Sharing list and make sure the one selected is for the model of your phone and not an older one you no longer have
- Check Stage 3 and 4 when icl starts and review the devices in your iCloud account to make sure you do not have any duplicates.

**Comment by turboboost** [comment]
Thanks!
I checked the Family sharing list and there was adifference to the phone I have, I also notet that the entity name was starting with "s" in the icloud3 config and "S" on iCloud, not sure if that was the issue but I deleted the device from iCloud3 config and re-created it - the spelling cam correct in the FamShr and now all is OK! 
Again thanks!

**Comment by gcobb321** [comment]
Excellent
