### ISSUE TITLE
Event Log resource not found

### ISSUE THREAD

**Issue by andyblac** [gcobb321/icloud3#269]
As the title, the resource is not found, any ideas whats wrong the JS file is `/config/www/custom_cards/icloud3-event-log-card.js`

<img width="502" alt="Screenshot 2023-06-06 at 11 03 07" src="https://github.com/gcobb321/icloud3/assets/77936/01ba728e-5a9d-4a80-85d8-e65e96c031c4">

**Comment by gcobb321** [comment]
The Dashboard Resources needs to be setup first:
- HA Settings > Dashboards > 3-dots in upper-right > Resources
  url =` /local/custom_components/icloud3-event-log-card.js`

On the Lovelace card, go to edit and raw yaml mode, use the code below:
`type: custom:icloud3-event-log-card`

**Comment by andyblac** [comment]
an entry is already there.
<img width="1226" alt="Screenshot 2023-06-06 at 15 48 36" src="https://github.com/gcobb321/icloud3/assets/77936/2132b300-c9d2-49a0-a5ba-f4ef345bec8a">

**Comment by gcobb321** [comment]
Maybe so but it needs the `/local/custom_component/` so it looks like the previous statement

**Comment by andyblac** [comment]
removed old one and recreated, still not found 
<img width="1215" alt="Screenshot 2023-06-06 at 16 01 23" src="https://github.com/gcobb321/icloud3/assets/77936/bd7ba6a8-cc96-475d-be46-79a88cd1d984">

**Comment by gcobb321** [comment]
Create a lovelace card with just the following:
```
type: grid
cards:
  - type: custom:icloud3-event-log-card
square: false
columns: 1
```

Also, make sure icloud-event-log-card.js is in the www/custom_components directory

**Comment by andyblac** [comment]
<img width="1035" alt="Screenshot 2023-06-06 at 16 10 16" src="https://github.com/gcobb321/icloud3/assets/77936/6a07940b-e24f-4205-991b-04f26eef1dae">
<img width="331" alt="Screenshot 2023-06-06 at 16 11 18" src="https://github.com/gcobb321/icloud3/assets/77936/1fc215b7-4968-44cc-ba7d-d22cb566b79a">

```
//  When iCloud3 starts, the version of this file, 'icloud3-event-log-card.js',
//  in the 'custom_components\icloud3' directory  (or the current directory of
//  the icloud3 platform being run) is compared with the one in 'www/custom_cards'.
//  If they do not match, the one in the 'custom_components\icloud3' is copied
//  to the 'www\custom_cards' directory.
```

**Comment by andyblac** [comment]
ok restarted, now sees it, thanks

**Comment by gcobb321** [comment]
Resources should have `custom_cards` directory not `custom_components`.

`/local/custom_cards/icloud3-event-log-card.js`

I've changed it in v3 and forgot what the directory was in v2
