### ISSUE TITLE
iCloud3 and IOS App - testing together

### ISSUE THREAD

**Issue by andystewart999** [gcobb321/icloud3#27]
Hi - I've installed iCloud3 2.0.5 and everything appears to be working as expected... I had to rename the IOS App v2 device tracker name as called out [here](https://gcobb321.github.io/icloud3/#/chapters/1-setting-up-icloud-account).

One question I have is that now I've renamed the IOS App device tracker name I don't seem to get any 'state change/zone change' events any more. iCloud3 is eventing as expected but nothing via the IOS app and/or the original device_tracker.andy_s_iphone_iosappv2 object (that was rename from device_tracker.andy_s_iphone).

Is that expected? I wanted to compare the two and see what kind of location-based events I got from both sources, and compare the time deltas, accuracy etc.

Thanks all,
Andy

**Comment by andystewart999** [comment]
I think I understand what's going on - the iCloud 3entity has to have the entity name that the IOS app expects, so when the IOS app triggers a zone/location change of some kind the iCloud3 app captures it?  Is that what's happening?

**Comment by gcobb321** [comment]
There is a large section in the iCloud3 documentation that explains how the iOS app and iCloud3 work together, including what iCloud3 monitors and how things must be set up. Go [here](https://gcobb321.github.io/icloud3/#/chapters/1-setting-up-icloud-account?id=associating-the-iphone-device-name-with-home-assistant-using-the-home-assistant-ios-app) to read it. You might want to review the chapter from the start again to make sure you didn't miss anything.

**Comment by gcobb321** [comment]
Reopen the issue if it still exists in v2.1

**Comment by gcobb321** [comment]
Release Candidate 4 is now available. See the Release Candidate Change Log file for information on the changes. Download it [here](https://github.com/gcobb321/icloud3/tree/master/development%20v2.2.0-rc4)
