### ISSUE TITLE
Configurator.apple_id_verification_code - this entity is unavailable

### ISSUE THREAD

**Issue by rocnydad** [gcobb321/icloud3#271]
I'm trying to verify my icloud connection via 2FA.  This has worked in the past but I recently got a new phone.  

The phone's "name" matches the name in the config file.

When I reset in icloud3, I get a 6 digital code on my phone.  When I enter that code into HA via the notification, I get a warning that the Configurator.apple_id_verification_code - entity is unavailable

When I click on the gear in the warning message it reads
This entity ('configurator.apple_id_verification_code') does not have a unique ID, therefore its settings cannot be managed from the UI. See the [documentation](https://www.home-assistant.io/faq/unique_id) for more detail.

In the icloud3 event log I see "iCloud alert > FmF of FamShr Tracking Method is disabled until Verification has been completed.

How do I successfully verify so I can re-enable tracking and location?

Also, I do not use the HA ios App.  It drinks battery.  I simply want to poll location from FmF.  I was able to do this previously

Thanks

**Comment by gcobb321** [comment]
1. Restart HA.  Then reset the iCloud interface using Event Log > Actions > Reset icloud interface. That should generate the new code and a new notification alert. Then enter it like you normally do. 
2. FmF does not work any more and can not be used to track devices. Apple pulled the plug in May.

**Comment by keithajmani** [comment]
Please see this issue for a workaround until the next release of iCloud3 -- worked for me.

#268 
https://github.com/gcobb321/icloud3/issues/268#issue-1740054440
