### ISSUE TITLE
Airtag

### ISSUE THREAD

**Issue by nicm91** [gcobb321/icloud3#273]
Hello
Is it possible to locate the airtag as well?

**Comment by gcobb321** [comment]
No. AirTags can not be located since they are tracked through other iDevices using Low Energy. Bluetooth

**Comment by townsmcp** [comment]
@gcobb321 i wonder if iOS 17 will help with this as Tags can be shared between people on family sharing? Maybe something will open up allowing for these to be added to icloud3?

**Comment by gcobb321** [comment]
Right now, there is no AirTag data returned from the iCloud Location Web service on the URL's used to provide FamShr data. We'll see.
