### ISSUE TITLE
Usecase question

### ISSUE THREAD

**Issue by Vinisz** [gcobb321/icloud3#277]
Hi, Looks like a nice component but what's exactly the usecase over using location via the companion app ? (I already do location tracking, zone enter-exit, etc that way)

**Comment by gcobb321** [comment]
A comparison of iCloud3 and iCloud components that has n ot yet been added to iCloud3 v3 docs it’s [here](https://github.com/gcobb321/icloud3/blob/master/docs/README.md)

The introduction to iCloud3 v3 is [here](https://github.com/gcobb321/icloud3/blob/master/docs/README.md). 
iCloud3 v3 prerelease is available on HACS when you enable beta versions

**Comment by Vinisz** [comment]
Yes, but that’s compared to the “normal” icloud add-in (which I don’t use at all, I just use companion app on the IOS devices and do location tracking that way)

So, how does it compare to that ?

 

Van: Gary Cobb ***@***.***> 
Verzonden: woensdag 30 augustus 2023 16:38
Aan: gcobb321/icloud3 ***@***.***>
CC: Vinisz ***@***.***>; Author ***@***.***>
Onderwerp: Re: [gcobb321/icloud3] Usecase question (Issue #277)

 

A comparison of iCloud3 and iCloud components that has n ot yet been added to iCloud3 v3 docs it’s here <https://github.com/gcobb321/icloud3/blob/master/docs/README.md> 

The introduction to iCloud3 v3 is here <https://github.com/gcobb321/icloud3/blob/master/docs/README.md> .
iCloud3 v3 prerelease is available on HACS when you enable beta versions

**Comment by gcobb321** [comment]
The feature list in the v3 link in your last message was wrong and should have pointed [here](https://gcobb321.github.io/icloud3_v3_docs/#/). That page describes the main functions of iCloud3 v3 that you can compare to the iOS App that is described in the HA docs and your experience with it to see if it will be of use to you. iCloud3 monitors the info from the iOS app for location and zone enter/exit triggers, along with location from your iCloud account. It can also track device locations with just the iOS App data and serve as an Aston t to it.
