### ISSUE TITLE
Locations not longer updating 

### ISSUE THREAD

**Issue by bradpearl** [gcobb321/icloud3#278]
As of yesterday afternoon, locations are no longer updating.

**Comment by gcobb321** [comment]
Ok. That’s a general statement that doesn’t really explain what is going on so it is difficult to help you. 

Any errors in the HA logs related to iCloud3? Any errors in the Event Log ? What does the Event Log show as far as tracking? 
and hardware changes? Have you reviewed the settings to make sure you are tracking the correct device?
What version are you running?  Is it a new install or v2 migration? Was everything running ok before?
Did you restart iCloud3? Did you restart HA?

**Comment by bradpearl** [comment]
No logs it’s as if the phones haven’t moved. My device (iPhone 2 - Brad) is
working fine but is using the Home Assistsnt app. The other two are issuing
Find My family sharing. Worked fine for the last week since initial
install. Restarted Home Assistant last night and it seemed to take (around
7pm) but hasn’t updated the location since.

**Comment by gcobb321** [comment]
Have you reviewed the Event Log for any errors during Stage 3 and 4 when the phones are being set up and associated with the Family Sharing list devices? 
what version of iCloud3 are you running?
Any notifications about reauthentication of your iCloud account?
Go to Configure Settings > Enter/Request Verification code and request a new verification code. Then enter it.

**Comment by gcobb321** [comment]
If you still have issues, turn on Debug logging. 
- Configure Settings > Page 2 > Format Parameters > Log Level = Debug - Auto Restart

Restart HA, let it run for an hour or so so it will generate tracking events. 
Send the _config/icloud3-0.log_ file to geekstergary@gmail.com 

I’ll look at it and see if I find anything

**Comment by bradpearl** [comment]
Looks like after reloading Cloud 3 again I am all set! Everything is
working as expected.

**Comment by gcobb321** [comment]
Good. Glad it’s now working. 

BTW.  You never said if you were running the v3 prerelease or the old v2.4.7..

**Comment by bradpearl** [comment]
v3
