### ISSUE TITLE
Create custom buttons on eventlog card

### ISSUE THREAD

**Issue by bobvmierlo** [gcobb321/icloud3#28]
Is there any way to create my own service call buttons on the eventlog card?
I would love to have a 'pause' button!

**Comment by gcobb321** [comment]
No, it isn't possible to create a new button (pause/resume) button on the Event Log. 

What you might want to do is create a 'tap_action' on one of the entities (interval) to pause and another on another entity (travel_time) to resume. You would run scripts that do the pause and resume on the tap_actions. See sample scripts that do this in the `sample-automations-scripts` directory, `sc_icloud3.yaml` file [here](https://github.com/gcobb321/icloud3/blob/master/sample-automations-scripts/sc_icloud3.yaml).
