### ISSUE TITLE
daily iCloud sign-in e-mail

### ISSUE THREAD

**Issue by martindinicolino** [gcobb321/icloud3#282]
Hello, 
thank you very much for creating this custom component!

I am trying it out instead of the HA iCloud integration, as i was hoping it would solve the problem of repeatedly receiving sign-in e-mails from Apple (i heard this custom component would not have this issue). Also, I really like the added functionality the iCloud3 custom component offers.

I deleted the HA iCloud integration completely, before i installed the iCloud3 custom component (i followed your instructions on GitHub).

First i installed version v2.4.7 but after getting it up and running for a couple of hours, i couldn‘t resist and migrated over to v3.0-pr1.4 (on the same day).

Ever since, I have been receiving a sign-in e-mail from Apple every night. Is this a know issue of the pre-release version of v3.0, or are others running the official release version v2.4.x and earlier, having this issue as well?

Looking forward to your replies. Thanks for your help.

edit: fixed a typo

**Comment by gcobb321** [comment]
Nothing solves the Apple email problem except creating an email filter that discards it. iCloud3 tries to minimize it by using a verified “session” token first to authenticate iCloud account access. When the token has expired, the password must be used. I think it is using the password that generates the email. V2 uses the password all the time which generates a lot more emails

**Comment by martindinicolino** [comment]
Thank you for replying.
I don‘t think i will create an email filter, as it presents a security issue.
Great job, i admire your work - v2 is great, but v3 is a huge improvement over it.
If there is ever a fix, i‘d be happy to come back to iCloud3.
