### ISSUE TITLE
iCloud3v3  Release Candidate 8 has been uploaded - v3.0.rc8 (10/25/2023)

### ISSUE THREAD

**Issue by gcobb321** [gcobb321/icloud3#285]
This release includes some bug fixes and new features.

### Update using HACS
When I create a new release, it is not picked up by HACS immediately. It might take HACS up to 48-hours to pick up the new release information and add it to the Devices & Services screen.

Check to see if the new version of iCloud3 is displayed as an available update on the Devices & Services screen. If it is not displayed there, do the following:
Open HACS from it's sidebar icon. Select Integrations, then type iCloud3 in the search field and press Enter.
Two items are displayed - iCloud3 Device Tracker and iCloud3 v3, Development Version.
Select iCloud3 v3, Development Version, click the 3-dots in the upper-right corner to open the menu. Select Update Information, Then select Download or Redownload. HACS will download and install the new version.
Restart HA like you normally do.
This Update

### Change Log:

Visit the Release Page [here](https://github.com/gcobb321/icloud3/releases) for a complete list of the changes.

**Comment by zeflash** [comment]
@gcobb321 FYI the rc8 tag is pointing on the rc6 commit (and therefore I'm not getting the rc8 in HACS because it's re-downloading the code at the rc6 commit level)

**Comment by gcobb321** [comment]
I just checked GitHub to be sure commit numbers there are different and everything is ok on GitHub. I think it is a HACS issue where its database is wrong. 

Go to HACS > Integrations > Search for iCloud3.  Select it, select 3-dots in upper right corner, select Update information. Then redownload. 

GitHub and HACS have been giving me fits where it reassigns the same commit number on a release Update. That is why the Release tag is v8.1.

**Comment by zeflash** [comment]
Hmmm sorry to disagree here :)
![image](https://github.com/gcobb321/icloud3/assets/1046904/7bfd1d8a-5532-4505-92dd-97b8566a0fcd)

in the tag list, if you click on the commit hash (44e1362) you’ll end up on the commit for rc6 ;)

**Comment by gcobb321** [comment]
I see. You are getting it from the icloud3 repository. I was referring to the same issue on the icloud_v3 repository. It appears GitHub has applied the rc8 changes to the rc6 commit instead of the master commit. 

I’ll remove the rc6 base and reupload it later this morning. You could download the rc8 zip file from the release page and unzip it into the _config/custom_components/icloud3_ directory. 


Edit: I just updated rc8 to create a new release with a new commit number. rc6 was/has been deleted.

**Comment by LordNex** [comment]
Even though I have the 3.0 RC. Every now and then I'll get a notification that theres a. New 2.4.7 version out. Usualy just checking for updates again makes it go away. Today it’s been there all day. Not that it matters as I know what versions installed. But I thought you should know.

**Comment by gcobb321** [comment]
That’s going to be a problem with how HACS handles a beta release notification and the regular release. Not much I can do about that.

**Comment by LordNex** [comment]
Well hopefully people look before they leap. But if you've ever worked in IT you know how users can be. Never RTFD or Manual.

**Comment by 1PlusN** [comment]
I've noticed RC 8 (8.1) is out on both the dev repo and the main... is there a nice way to switch from one to the other without loosing everything?

**Comment by LordNex** [comment]
I've for RC8 but haven't went further. Should I upgrade or wait?

**Comment by gcobb321** [comment]
@1PlusN 
My plan is to promote iCloud3 to an official release status around the end of December (rc9 will be released later today or tomorrow). The HACS iCloud3 will be the official, production version. The iCloud3-v3 GitHub repository will become a Development version. To switch from one to the other probably is to go to HACS and just install it from the one you want.

**Comment by 1PlusN** [comment]
> @1PlusN My plan is to promote iCloud3 to an official release status around the end of December (rc9 will be released later today or tomorrow). The HACS iCloud3 will be the official, production version. The iCloud3-v3 GitHub repository will become a Development version. To switch from one to the other probably is to go to HACS and just install it from the one you want.

I failed to reboot enough times. The first reboot shows the integration cannot be reloaded, the second one makes everything work perfectly. Thank you for all your time!

**Comment by gcobb321** [comment]
I think the first reboot still uses some cached config and integration settings. When that failed, it clears it so the second then works
