### ISSUE TITLE
No sample config file

### ISSUE THREAD

**Issue by estiens** [gcobb321/icloud3#287]
Documentation mentions a sample configuration YAML, but I don't see it anywhere....

**Comment by gcobb321** [comment]
Years ago, I included a file but have not done so since HA started online support for automations and scripts. They are in the docs and can be copied by selecting the one you are interested in. 

They are [here](https://gcobb321.github.io/icloud3_v3_docs/#/chapters/5.0-sample-automation-scripts)

**Comment by temmink** [comment]
nope, they are not at the provided link, mentioned above by Gcobb321

**Comment by gcobb321** [comment]
The docs have been completely reorganized since November. The iCloud3 v3 docs are [here](https://gcobb321.github.io/icloud3_v3_docs/#/). See the Reference > Sample Automations and Scripts chapter
