### ISSUE TITLE
Failed to call service device_tracker/icloud3_update. Service not found

### ISSUE THREAD

**Issue by yvansandoz** [gcobb321/icloud3#289]
<img width="520" alt="Screenshot 2023-11-12 at 08 08 08" src="https://github.com/gcobb321/icloud3/assets/68730331/83ea82ba-4ec0-48ac-acd0-593dc8d88234">

I just upgraded to v3, sofar everything looks good, I see all the information from the 4 family iPhone, but I cannot see the log file (see attached image). I did add the path of the log file in the dashboard.

If I hit "Setup" a pop-up windows shows the error message "Failed to call service device_tracker/icloud3_update. Service not found".

**Comment by gcobb321** [comment]
1. That screen is the v2 _Event Log_ screen, not the v3 version. You need to refresh your browser. 
See [here](https://gcobb321.github.io/icloud3_v3_docs/#/chapters/2.0-installing-and-configuring?id=step-5-set-up-a-lovelace-card-tracking-card) for a screenshot. Notice the v3 and icons at the top. 

See [here](https://gcobb321.github.io/icloud3_v3_docs/#/chapters/2.0-installing-and-configuring?id=clearing-the-browser39s-cache) for info about clearing the cache. 
2. The _update _ Service has been renamed to _action_.

**Comment by peetereczek** [comment]
Issue exists after migration. There is no guide how to fix it

**Comment by gcobb321** [comment]
What is the issue again? If it is the same screenshot from above, again, that Event Log is from v2, not v3.

EDIT: An additional thought. Did you clear the browsers cache. See [here](https://gcobb321.github.io/icloud3_v3_docs/#/chapters/3.1-migrating-v2-to-v3?id=step-5-clear-the-browsers-cache)
