### ISSUE TITLE
Integration Wizard Fails

### ISSUE THREAD

**Issue by LordNex** [gcobb321/icloud3#291]
I've used this in the past and it's worked very well. When I seen you had a RC for 3.0 I thought I'd give it a try. Everything was already configured and from the install instructions you just download the newer repo, then add the integration. I don't know if this had an integration before but I never seen it. I just had the config in my yaml files and have your page that shows the reports. 

Anyway, I downloaded as of 11-19-2023 @ 4:30 CST and rebooted. It seemed to take an extra long time booting and loading integrations but I looked at the config share and could see that it was building a migration log, so something was happening. After a long time booting I attempted to install the integration. It just spins and spins then gives this error, then from what I can tell HA reboots. I'm guessing from an error. Yet it boots back fine but no integration for icloud3 loaded. Let me know what logs or anything you need. Here's a bland error it shows after a long spin

![image](https://github.com/gcobb321/icloud3/assets/9270948/60cffd71-d0cf-42a8-aaa9-b9beab34d226)

**Comment by LordNex** [comment]
Well I tried your dev version that was updated yesterday and it did the same thing. And I can confirm that trying to install the integration causes HA to crash. I'm not talking the App. I'm saying the entire server. Or at least the docker supervisor and all containers. Do I need to modify something in my configuration.yaml?

**Comment by gcobb321** [comment]
1. Were you loading from the HACS iCloud3 beta or the HACS iCloud3_v3 repo?
2. In the custom_components/icloud3 directory, do you see a lot of files, including const.py, sensor.py, icloud3_main, and several directories? const.py has a version at the beginning of the file. What is it?
3. The migration would create the icloud3_migration.log file. Send that to geekstergary@gmail.com. The migration will create the config/.storage/icloud3/configuration file. Send me that too. 

Try this:
 Remove the yaml config statements from the HA configuration.yaml file. Or comment them out. 
 Rename the config_ic3.yaml if you have one. 
Then restart HA. Then restart HA again (yes again). 
Then reinstall from HACS. 
Then restart HA, go to the Integration screen and add iCloud3 again. 
Then go to its Configure screen. That will have the settings from the configuration file. 
If you have problems, delete the .storage/icloud3 directory. Do not delete .storage/icloud (without the 3). That file contains your Apple iCloud account cookie files. 
Restart HA. This will create a default configuration file and should let you go into the Configure Settings screens.

**Comment by LordNex** [comment]
What's under my device tracers in my configuration.yaml

```

  - platform: icloud3
    username: REDACTED
    password: REDACTED 
    create_sensors: all
    exclude_sensors: 
    event_log_card_directory: '/www/custom_cards'
    config_ic3_file_name: '/config/config_ic3.yaml'
    tracking_method: iosapp
```
```
## System Information

version | core-2023.11.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.59
arch | x86_64
timezone | America/Chicago
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4922
Installed Version | 1.33.0
Stage | running
Available Repositories | 1415
Downloaded Repositories | 115
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | March 2, 2024 at 6:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | us-east-1-2.ui.nabu.casa
certificate_status | ready
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.3
agent_version | 1.6.0
docker_version | 24.0.6
disk_total | 786.7 GB
disk_used | 106.6 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | AdGuard Home (4.8.17), AirCast (4.0.1), AirSonos (4.0.0), Duck DNS (1.15.0), ESPHome (2023.11.2), File editor (5.7.0), Frigate Proxy (1.3), MariaDB (2.6.1), Matrix (0.10.0), Z-Wave JS (0.3.0), Studio Code Server (5.14.2), Advanced SSH & Web Terminal (16.0.1), Traccar (0.22.0), Tor (4.3.0), chrony (2.6.2), TasmoAdmin (0.26.0), Spotify Connect (0.12.6), Node-RED (16.0.2), Samba share (12.1.0), Samba Backup (5.2.0), Exadel CompreFace (1.1.0), AppDaemon (0.15.2), Bookstack (1.10.1), Matter Server (4.10.2), go2rtc master hardware (master-hardware), EMQX (0.2.12), Terminal & SSH (9.8.1), Tailscale (0.13.1), Music Assistant BETA (2.0.0b75), OpenThread Border Router (2.3.2), Piper (1.4.0), Whisper (1.0.0), Vaultwarden (Bitwarden) (0.20.1), openWakeWord (1.8.2), Google Assistant SDK (2.5.0), Docker Wyze Bridge (2.5.1), TubesZB Silicon Labs FW Flasher (0.2.2), DeepStack (CPU) (2021.09.1), SSH Tunnel (1.0.6), CodeProject AI.Server (CPU) (2.3.4.1), Double Take (1.13.11.7.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 61
views | 15
mode | storage

</details>

<details><summary>NextDNS</summary>

can_reach_server | ok
-- | --

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | May 24, 2023 at 4:40 AM
-- | --
current_recorder_run | November 19, 2023 at 4:58 PM
estimated_db_size | 10331.14 MiB
database_engine | mysql
database_version | 10.6.12

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>
```

**Comment by gcobb321** [comment]
Another user was using HA in a docker environment a couple of days ago.  I don’t know what he did but his issue is [here](https://github.com/gcobb321/icloud3/issues/290). 

I have no real experience with docker but I would:
 Delete the custon_components/icloud3 directory and .storage/icloud3 directory. 
Remove the icloud3 statements from HA configuration.yaml file and config_ic3.yaml file. 
 Restart HA twice. Yes twice. 
 Reinstall icloud3 from HACS
Restart HA and read the Integration.

**Comment by LordNex** [comment]
> 1. Were you loading from the HACS iCloud3 beta or the HACS iCloud3_v3 repo?
> 
> 2. In the custom_components/icloud3 directory, do you see a lot of files, including const.py, sensor.py, icloud3_main, and several directories? const.py has a version at the beginning of the file. What is it?
> 
> 3. The migration would create the icloud3_migration.log file. Send that to geekstergary@gmail.com. The migration will create the config/.storage/icloud3/configuration file. Send me that too. 
> 
> 
> 
> Try this:
> 
>  Remove the yaml config statements from the HA configuration.yaml file. Or comment them out. 
> 
>  Rename the config_ic3.yaml if you have one. 
> 
> Then restart HA. Then restart HA again (yes again). 
> 
> Then reinstall from HACS. 
> 
> Then restart HA, go to the Integration screen and add iCloud3 again. 
> 
> Then go to its Configure screen. That will have the settings from the configuration file. 
> 
> If you have problems, delete the .storage/icloud3 directory. Do not delete .storage/icloud (without the 3). That file contains your Apple iCloud account cookie files. 
> 
> Restart HA. This will create a default configuration file and should let you go into the Configure Settings screens. 
> 
> 

Walking through your fix now. I probably don't need the dev version. I wouldn't consider myself a programmer. I'm more of a Network Guru. Been stomping out fires since 1998 professionally. Let me try this and if this don't work I'll gather the logs and email them to you. Thanks a bunch for your help and cool ass app! Many thanks!

**Comment by LordNex** [comment]
> 1. Were you loading from the HACS iCloud3 beta or the HACS iCloud3_v3 repo?
> 
> 2. In the custom_components/icloud3 directory, do you see a lot of files, including const.py, sensor.py, icloud3_main, and several directories? const.py has a version at the beginning of the file. What is it?
> 
> 3. The migration would create the icloud3_migration.log file. Send that to geekstergary@gmail.com. The migration will create the config/.storage/icloud3/configuration file. Send me that too. 
> 
> 
> 
> Try this:
> 
>  Remove the yaml config statements from the HA configuration.yaml file. Or comment them out. 
> 
>  Rename the config_ic3.yaml if you have one. 
> 
> Then restart HA. Then restart HA again (yes again). 
> 
> Then reinstall from HACS. 
> 
> Then restart HA, go to the Integration screen and add iCloud3 again. 
> 
> Then go to its Configure screen. That will have the settings from the configuration file. 
> 
> If you have problems, delete the .storage/icloud3 directory. Do not delete .storage/icloud (without the 3). That file contains your Apple iCloud account cookie files. 
> 
> Restart HA. This will create a default configuration file and should let you go into the Configure Settings screens. 
> 
> 

That did it. Basically reset everything to default but it shouldn't be too hard to clean up some stuff. But I got it running and each of my families iPhones and watches. Going to see how it does before I add iPads. I have a lot of AirTags too so I'll have to figure that out later. But at least it's now triggering properly in the right zones. Thank you very much much!!

**Comment by gcobb321** [comment]
Glad resetting everything worked. AirTags are not supported. Apple doesn’t provide a web interface for them.
