### ISSUE TITLE
Question about Family Shared Calendars

### ISSUE THREAD

**Issue by LordNex** [gcobb321/icloud3#292]
Is there a way to bring those into the new calendars function?

**Comment by gcobb321** [comment]
Not that I know of. I don’t have any plans to do anything with calendars.

**Comment by LordNex** [comment]
Yea just could the caldev config. Going to try that. Thanks for the fast reponse. Feel free to hit me up if you need anything

***@***.***

**Comment by gcobb321** [comment]
iCloud3 is a device tracking program that has nothing to do with calendars. Are you confusing it with another program or HA custom component?

**Comment by LordNex** [comment]
No I just knew it pulled in other family sharing features so I wasn’t sure if that would be a sensor or not. I didn’t think so but I figured there’s no harm in asking. So far Caldav at least in the config doesn’t seem to be working. But it’s hard to tell
Benjamin T Powers

On Nov 20, 2023, at 4:34 PM, Gary Cobb ***@***.***> wrote:

﻿

iCloud3 is a device tracking program that has nothing to do with calendars. Are you confusing it with another program or HA custom component?
