### ISSUE TITLE
Downgrade Prompt When On Beta

### ISSUE THREAD

**Issue by LordNex** [gcobb321/icloud3#293]
Not that it's a big deal or anything but this keeps popping up even though I'm technically on a higher version. Feel free to close if you'd like. I just thought you should know. 

![image](https://github.com/gcobb321/icloud3/assets/9270948/54f7d1b3-6a2f-4074-95ae-72eba8002d96)

**Comment by gcobb321** [comment]
That would be a GitHub-HACS issue not knowing or comparing the release date to see which is the latest. That will solve itself when iCloud3 goes off beta.
