### ISSUE TITLE
Empty setup windows (missing text)

### ISSUE THREAD

**Issue by TomDidi** [gcobb321/icloud3#296]
after installing iCloud3 v3 rc8  I got in the setup windows missing text, so that I am only to guess, what does it mean!
Setup will be in german, but you can image the english translation.
So, how can I proceed or what I am doing wrong?

BR Thomas

<img width="507" alt="Bildschirmfoto 2023-12-17 um 21 34 45" src="https://github.com/gcobb321/icloud3/assets/34604238/2f0347b1-8600-4d4a-94a2-d3653e88d6f5">
<img width="408" alt="Bildschirmfoto 2023-12-17 um 21 34 06" src="https://github.com/gcobb321/icloud3/assets/34604238/b497fe3d-a130-451d-ba16-29a66f61478e">
<img width="619" alt="Bildschirmfoto 2023-12-17 um 21 33 47" src="https://github.com/gcobb321/icloud3/assets/34604238/5edb8a06-d56f-4431-bca1-3391ea47a15d">

**Comment by gcobb321** [comment]
There was a problem like this about 8-months ago. Try refreshing your browser several times. If it still does not display correctly, restart HA 2-times. Yes, it takes 2-times to clear the HA cache and reload it.

**Comment by TomDidi** [comment]
Yes, you are right. Due to missing Clearing of Browser cache I got the problems above, again reboot was the solution. This fits my rule: 70% of the failures are sitting in front the device! But I will come back with an other question in the community tonight.

BR Thomas

**Comment by gcobb321** [comment]
I haven’t heard that phrase before and think 79% is about right. Glad it’s ok now. Watch for rc9, in uploading tomorrow so HACS should pick it up about Thursday. I’ll close this to keep things tidy.
