### ISSUE TITLE
don't have the integration when installed from HACS.

### ISSUE THREAD

**Issue by temmink** [gcobb321/icloud3#299]
I tried to install the prelease of icloud3 through HACS. 
I downloaded the repository, and I choose the version (I think it was mentioning 2.4.9).

after rebooting the raspberry (and so restarting homeassistant) I don't have the integration available, not even after cleaning my browser cache, just to be sure,

The files are loaded in the custom-folder of Homeassistant.

how can I enable icloud3, so that i can start configuring/using it?

**Comment by gcobb321** [comment]
Enable beta versions on HACS. Then you should see v3 rc9
