### ISSUE TITLE
Second account and only service find

### ISSUE THREAD

**Issue by CH1PSET1** [gcobb321/icloud3#300]
Hello. Please tell me 2 questions.
1. Is it possible to add a second separate icloud account? If, for example, the devices are not in the same family.
2. I would like to use the integration exclusively to use the iPhone search service. In this regard, is it possible to limit integration requests to the icloud account as much as possible, thereby getting rid of apple login letters?

**Comment by gcobb321** [comment]
1. No, only one account is supported at this time. 
2. The Apple login notifications are generated when a login security token expires and the password is used to authenticate access. The token usually needs to be renewed every 30-minutes. A long inzone interval reduces the locate requests which reduces the notifications. You could also set a fixed interval for a device and move it a long time which handles out of zone location requests.
