### ISSUE TITLE
Logger: homeassistant.setup Source: setup.py:221 First occurred: 15:31:46 (1 occurrences) Last logged: 15:31:46  Setup failed for custom integration 'icloud3': No setup or config entry setup function defined.

### ISSUE THREAD

**Issue by didi1231** [gcobb321/icloud3#303]
I get the following errors, what can I do? Logger: homeassistant.setup
Source: setup.py:221
First occurred: 15:31:46 (1 occurrences)
Last logged: 15:31:46

Setup failed for custom integration 'icloud3': No setup or config entry setup function defined.
and logger: custom_components.icloud3.device_tracker
Source: custom_components/icloud3/device_tracker.py:6779
Integration: icloud3 (documentation, issues)
First occurred: 15:32:03 (1 occurrences)
Last logged: 15:32:03

(Status Code 501)
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 6779, in _setup_tracked_devices_for_fmf
    self._log_rawdata("iCloud FmF Raw Data - (api_friends.data)", api_friends.data)
                                                                  ^^^^^^^^^^^^^^^^
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 1079, in data
    self.refresh_client()
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 1006, in refresh_client
    req = self.session.post(self._friend_endpoint, data=mock_payload, params=params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 179, in request
    self._raise_error(response.status_code, response.reason)
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 239, in _raise_error
    raise api_error
custom_components.icloud3.pyicloud_ic3.PyiCloudAPIResponseException: (Status Code 501)

**Comment by gcobb321** [comment]
It looks like you are using v2.4.x of iCloud3 and there is an error setting up the Find-my-Friends tracking method. That has not been available since May, 2023 when Apple stopped supporting it. 

The best thing to do is to install the updated iCloud3 v3. It is in the final stages of beta and will solve that problem. See the 'iCooud3 v3.0.rc10.3' issue for more information on installing it.
