### ISSUE TITLE
v3.0.rc10.4 Triggers a lot of AppleID warning emails

### ISSUE THREAD

**Issue by chaugan** [gcobb321/icloud3#307]
After installing (via HACS) I started getting MANY AppleID warnings email warning me about that my AppleID was logged on through a browser. 

All logins can be correlated with actions in iCloud3 logs:

I have not changed my password or anything. It just happened out of the blue after it had been working for days. I could post a screenshot from the mail from Apple but it's on my native language (Norwegian).

['23:44:17', 'iCloud Acct Auth #58 > Password+Token, Last-23:43:40']

['23:43:40', 'iCloud Acct Auth #57 > , Password, ERROR-Invalid username/password, Last-23:43:04'] 

['23:43:04', 'iCloud Acct Auth #56 > , Password, ERROR-Invalid username/password, Last-23:42:45']

['23:42:45', 'iCloud Acct Auth #55 > , Password, ERROR-Invalid username/password, Last-23:42:22']

**Comment by gcobb321** [comment]
Are there any other errors in the HA log file?
Apple will send a notification email and there is not much you can do about those. That is described in the iCloud3 docs [here](https://gcobb321.github.io/icloud3_v3_docs/#/chapters/2.2-apple-id-verification?id=login-email-notification-from-apple). 
I saw a similar issue yesterday on my system while making a code change and wonder if it is actually another issue not related to the iCloud account password but displaying that message. 
Restart HA and see if the error continues. If it does, sends the iCloud-0.log file to geekstergary@gmail.com. I’ll see if is like what Iran into and then send you the rc10.5 code I’m working on to try to trap that error.

**Comment by chaugan** [comment]
Happened again. I've just sent you the log file.

**Comment by gcobb321** [comment]
I took a quick look at the log file and the errors are probably more of a notification that the Verification Code may have been needed (450, & 500).

The letter from Apple is normal and discussed in the User Guide [here](https://gcobb321.github.io/icloud3_v3_docs/#/chapters/2.2-apple-id-verification?id=login-email-notification-from-apple)

The rc10.5 zip file is the updated one I'm running. I didn't see any problems with it today while running around. Unzip it into the icloud3 directory and restart HA and lets see what happens.
[icloud3_v3.0.rc10.5.zip](https://github.com/gcobb321/icloud3/files/14390909/icloud3_v3.0.rc10.5.zip)

**Comment by nsutcliffe** [comment]
@gcobb321 it would be great if you could add an option to send an email when icloud3 is doing a login, so at least could pair these off as a user and know if it's icloud3 vs something else.

**Comment by gcobb321** [comment]
@nsutcliffe 
I can not send an email. The Event Log Tracking Monitors show when an iCloud Authentication is being done. Select _Event Log > Actions > Show Tracking Monitors_ and look for it. Select Hide Tracking Monitors to not show them.
