### ISSUE TITLE
AirPods Pro battery stuck at 0%

### ISSUE THREAD

**Issue by polmonta** [gcobb321/icloud3#309]
I've using iCloud 3 for a while now and I've just noticed that my AirPods Pro battery has been stuck at 0% forever. I have tried factory restarting the AirPods, opening the case with both AirPods in (the battery indicator came up on my phone and both AirPods & case had plenty of battery) and repeatedly removing and adding the AirPods to iCloud 3 but nothing seems to work.

This is the configuration I'm using:
<img width="584" alt="Screenshot 2024-02-26 at 17 37 31" src="https://github.com/gcobb321/icloud3/assets/49655908/56d3bbeb-84a1-460e-b1d2-a8bb3488f0e8">

I have also tried investigating online in case this was a bug or it had some fix, but I haven't had any luck.

Thanks in advance.

**Comment by gcobb321** [comment]
Apple does not return any battery info for the AirPods. That is why it is always 0. It does return the last known location

**Comment by polmonta** [comment]
> Apple does not return any battery info for the AirPods. That is why it is always 0. It does return the last known location

I didn't know that, thank you.
Is there any other possible way I can pull the percentage of the AirPod's battery?

**Comment by gcobb321** [comment]
Not that I know of.  The data from famshr that is returned has one battery level field that it’s always 0.0. The AirPods have 3 battery levels-case, right pods and left pod. That could be why Apple isn’t providing that data

**Comment by polmonta** [comment]
That's probably it.
Thank you anyway!
