### ISSUE TITLE
speed attribute always 0

### ISSUE THREAD

**Issue by lvefferen** [gcobb321/icloud3#31]
The speeds attribute is always 0 in my setup. the same is with multiple devices. is this a known issue? the speed from HA ios app was OK and enabled me to detect if I was driving my car.

**Comment by riemers** [comment]
I also see the value 0.

**Comment by gcobb321** [comment]
All iCloud3 does with the speed is pass it along from the iOS app and it is always 0 for me too. I have added a speed, speed_high and speed_average attribute in  The next update that is calculated on each poll. 

I've also added a new Lovelace iCloud3 Event Log card that displays the significant events that happen within iCloud3 when tracking devices.
