### ISSUE TITLE
HA 107.x and icloude3 now connecting icloud

### ISSUE THREAD

**Issue by JMuffin** [gcobb321/icloud3#31]
Error in log:

'NoneType' object has no attribute 'friends'

Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 5623, in _setup_tracked_devices_for_fmf
    fmf = self.api.friends
AttributeError: 'NoneType' object has no attribute 'friends'

**Comment by gcobb321** [comment]
This probably means there is no friends/contacts in the non-2fa account. Check to make sure you have added the users names and iCloud email address of the 2fa accounts you want to track in the non-2fa account.contacts app. Also check the FindMe app to make sure the friends can be located. If the Find Ne app can not locate the devices/contacts, iCloud3 will not be able too either.

More information is in the iCloud3 documentation [here](https://gcobb321.github.io/icloud3/#/chapters/1-setting-up-icloud-account?id=locating-your-device-with-icloud)

Check the Event Log for more information.

And, what version of iCloud3 are you running. Upgrade to v2.1 if you are on an earlier version.

**Comment by gcobb321** [comment]
Reopen issue is problem still exists
