### ISSUE TITLE
Issues from V2 to V3

### ISSUE THREAD

**Issue by diver77** [gcobb321/icloud3#310]
Hello.
i migrate von V2 to V3 and get some issues. 
Sorry if i do same wrong, but i´m a beginner in HA.

as i said, i migrate the Version. that works ok.
But i have the problem, i just can install person how have the HA-App installt in the Iphone.
Persons how are in the Familie-Share but don´t have the HA-APP i can´t add to the icloud3.

The other problem i have. i tried to add the dashboard with your example. but when i copy past it an click save i geht this issue
YAML kann nicht geparst werden: YAMLException: bad indentation of a mapping entry (30:9) 27 | name: TravTime 28 | - entity: sensor.gary_ipho ... 29 | name: NextUpdt 30 | - type: glance --------------^ 31 | columns: 5 32 | entities:

thanks for your help

sunny Greetings from Bavaria

Diver

**Comment by diver77** [comment]
one more information with this problem:
Persons how are in the Familie-Share but don´t have the HA-APP i can´t add to the icloud3.

in the Version 2.4 i could add any Person from the family share. in Version 3 just the persons with the HA-App.

Is this this issues?: (i found it just at this moment)
My iPhone/iPad is not in the Update Device screen > Family Sharing Device selection list
It is displayed on the FindMy App Devices screen but I can not select it when configuring the device.

This means that Location Sharing is probably not enabled on the iDevice. On the iDevice:

Go to Settings App > Privacy and Security > Location Services - Share My Location screen. Verify that Location Sharing is enabled.
Go to FindMy App > Me screen. The Location field should be "Shared". If it is "‘Not Sharing Location", Location Sharing is still not enabled.

**Comment by gcobb321** [comment]
Go to Settings App > Privacy and Security > Location Services - Share My Location screen. Verify that Location Sharing is enabled.
Go to FindMy App > Me screen. The Location field should be "Shared". If it is "‘Not Sharing Location", Location Sharing is still not enabled.

This is correct. Then _Event Log > Actions > Restart ICloud3_  and the devices in the Family Sharing List will be displayed on the _Configure Settings > Update Devices_ screen Family Sharing list field. Do this for every device.

**Comment by gcobb321** [comment]
Did you get iCloud3 running? Or were you waiting for me to answer the question?

**Comment by diver77** [comment]
hello,
yes it´s running.
Thanks for your help and thanks for your awesam work.
Just one more question.
how can it be, that someone is at home but i get two different answeres.
device-tracker says away and the Info says i´m at home

[image: image.png]

thanks again for your help

Diver

Am Do., 29. Feb. 2024 um 08:30 Uhr schrieb Gary Cobb <
***@***.***>:

**Comment by diver77** [comment]
oh sorry just saw, that the Picture isn´t show, hiere again the Picture. 
![image](https://github.com/gcobb321/icloud3/assets/72558304/f858a2db-617d-4c7e-a479-615d05097750)

This is what HA show of the postion of my son. But this is Sylt, which is 1000km away from our home.
![image](https://github.com/gcobb321/icloud3/assets/72558304/ad32739f-098e-4da3-9a45-3d03a8f34d3d)
 we were there 1 year ago.
Do you kow why HA show me the wrong position?

**Comment by gcobb321** [comment]
1. I would start by reviewing the Event Log, Stage 3,4 & 5 and see if there are any devices for Benni that have the same name. 
2. Look at the devices in the Family Sharing List and remove any devices you no longer have.
3. Review the Benni Update Devices screen and see if there is an old Family sharing Device you no longer own assigned to Benni.
4. Look at the FindMy App and see where Benni is when this occurs.
