### ISSUE TITLE
Thread is calling async methods directly

### ISSUE THREAD

**Issue by balloob** [gcobb321/icloud3#315]
The main loop `_polling_loop_5_sec_device` is not decorated as `callback`, so it is executed in a thread every 5 seconds. When it detects an update, it can call `write_ha_sensor_state` (still within the context of the thread). This method then calls [`self.async_write_ha_state()`](https://github.com/gcobb321/icloud3/blob/master/custom_components/icloud3/sensor.py#L783).

A sync method is not allowed to call any async method. They can be recognized by the `async_` prefix. Some of them need to be awaited, others are not.

In this case, you should call `self.schedule_update_ha_state()`.

**Comment by 26tajeen** [comment]
@balloob could this be causing Home Assistant to restart?

**Comment by gcobb321** [comment]
Thank you for your advice. This change has been included in the version of iCloud3 v3.0.1 that will be posted to the iCloud3 Development GitHub repository this week and the general release GitHub repository a short time later.

**Comment by gcobb321** [comment]
@26tajeen 
I have updated iCloud3. Here is a preliminary copy of v3.0.1. Let me know if it does not solve your issue.

Unzip it to the icloud3 directory and restart HA.
[icloud3_v3.0.1.zip](https://github.com/gcobb321/icloud3/files/14551229/icloud3_v3.0.1.zip)

**Comment by 26tajeen** [comment]
Hi, I had hoped it would fix my issue but I got another freeze this morning as I arrived home. Thanks for being 'on it' :-)

**Comment by gcobb321** [comment]
Completed in v3.0.1/v3.0.2
