### ISSUE TITLE
running v3.0.rc10.4 but constantly getting notification to update to the 2.4.7 version - cannot skip it away

### ISSUE THREAD

**Issue by Menz01** [gcobb321/icloud3#316]
Hello,
   i am running version v3.0.rc10.4 and when i open HA i always getting prompted to update in my updates section to version 2.4.7. ifi try and click "skip" i get some error message at the bottom saying something about no version or something. the update may or may not go away at that point. if it does go away it always comes back. if i am on the latest beta... why am i constantly getting prompted to install 2.4.7??

**Comment by gcobb321** [comment]
It is probably a HACS issue where it is not recognizing that you have installed a beta version that is newer than the release version. There is nothing you can do but ignore it until I release v3 as the primary release version instead of a preliminary beta version.

**Comment by Menz01** [comment]
Ok. Thank you
