### ISSUE TITLE
HA freezes when entering Home Zone

### ISSUE THREAD

**Issue by gcobb321** [gcobb321/icloud3#319]
@[26tajeen](https://github.com/26tajeen)
I have opened a new issue for this problem so balloob does not get a notification on every post for this issue. 

1. Turn on Debug logging - _Configure Settings > Page 2 > Format Parameters_ screen > Log level > Debug
2. Restart HA
3. Run everything until you get the freezer. 
4. Send me the complete icloud3-0.log and home-assistant.log files. Email to geekstergary@gmail.com

**Comment by 26tajeen** [comment]
[Current working theory](https://community.home-assistant.io/t/logs-provided-can-anyone-see-whats-causing-my-ha-to-lockup-freeze/703503/2?u=daneboom)

my home-assistant_v2.db got corrupted due to all the freezes/restarts.
Now I have 'hangover issues' from that, and actually the icloud3 repo you provided MAY have solved the original issue.
I'll install and retry....

**Comment by 26tajeen** [comment]
Hi Gary, will email you the HA logs. Currently my HA is freezing so often I can't even get in to the UI to export  the event logs.  SSH always works - is there somewhere I can access them from the file system to export them?

**Comment by 26tajeen** [comment]
Hi Gary, not sure if you got my email or not, but my latest theory is [this script](https://github.com/rodpayne/home-assistant/blob/main/.homeassistant/python_scripts/set_state.py) might be responsible for the crashes

**Comment by gcobb321** [comment]
I looked at the log file you sent and iCloud3 was doing its normal startup and just stopped.  I don’t think iCloud3 is the problem. The Python script code looks ok but why are you running it and what entities are you force setting? Comment it’s out of your HA config and see what happens. When trying to solve a problem like this, you have to remove one thing at a time and see if it then works. If it does,  you have found the p problem

**Comment by 26tajeen** [comment]
Yeah, I've removed all references to that script from my automations and my HA has been stable ever since. It's only been a day but it's a MASSIVE improvement on what it was.
![Screenshot 2024-03-15 at 14 40 31](https://github.com/gcobb321/icloud3/assets/28266789/1d76ec12-3a47-43a7-b452-80eacc845864)

**Comment by gcobb321** [comment]
Great. Sounds like progress.
v3.0.1b4 that fixes that problem.

#### Here is the latest v3.0.1b4
Unzip into the icloud3 directory and restart HA.
[icloud3_v3.0.1b4.zip](https://github.com/gcobb321/icloud3/files/14617211/icloud3_v3.0.1b4.zip)

#### Change Log : v3.0.1 - 3/15/2024
1. UPDATE SENSOR & DEVICE TRACKER ENTITIES (Improvement) - Changed the method of updating these items at the request of @balloob (Paulus Schousten, HA Founder) to prevent a potential Home Assistant lockup when doing an update.
2. LOG FILE (Improvement) - Changed the method of updating the iCloud3 log files. Also changed some of the record formatting to improve readability.
2. WAZE & CALC DISTANCE SENSORS (Fixed) - They were not being created.
3. UPDATE DEVICES CONFIGURE SCREEN (Fixed) - The Picture parameter was listing every image file in the all of the www/ sub-directories. A filter was added to limit the search to specific directories. The filter is defined on the Tracking and Other Parameters screen. Only the first 25 image files in a directory will be displayed to prevent overloading the HA dropdown list handler.
4. FIXED INTERVAL (Improvement) - The lowest interval was reduced from 5-minutes to 3-minutes.
5. DIRECTION OF TRAVEL (Improvement) - Changed the way this is being updated. If the distance from Home is more than 400m/250mi, it will be set to FarAway.
6. STATIONARY ZONE (Fixed) - The second device to enter an existing Stationary Zone was not saving the Stationary Zone info correctly.

**Comment by 26tajeen** [comment]
You are an amazing dev!
