### ISSUE TITLE
Does icloud3 intentionally request multiple GPS data in a short time period

### ISSUE THREAD

**Issue by jata1** [gcobb321/icloud3#321]
Hi Gary - I'm still working away at getting reasonably good speed data between the HA app and iCloud3 integration. 

I have noticed that icloud3 seems to go through a little fit from time to time - my hunch is when approaching 'home' - see chart below. I have seen this previously but thought it was a one off. Lots of GPS data/requests is a bit of an issue as GPS coordinates and fixtime data can be good but I guess it is screwing up my speed calcs because of GPS accuracy. 

Are you aware that icloud is doing this multiple request in a short period of time thing? If so, can I control it somehow?

See data below to give you an idea

![image](https://github.com/gcobb321/icloud3/assets/23280705/dc09cd67-c64b-4870-b301-5be15ae9abd5)

**Comment by gcobb321** [comment]
When iCloud3 approaches a tracked zone (Home), the request interval is set to 15-secs when the distance is less than 1-km. This helps insure triggering a Home zone enter, especially if the device does not have the mobile app or is in a poor cell area.

**Comment by jata1** [comment]
I see so I guessed that was it. Can I ask for a feature for the user to be able to set this frequency please?

**Comment by gcobb321** [comment]
You can ask but it probably won’t happen.  There are several other choices you might think about.
- Ignore speed if within 1km of Home
- Create a template sensor with the gps and timestamp and update that when the timestamp is x-secs/mins from the last one. Use that sensor as input to your speed
- Ask Phil to ignore timestamps close to the last value

**Comment by jata1** [comment]
Thanks. Phil and I are discussing.

I am going to look into creating a statistics sensor that will take all of the speed data and output the average or median. 

Overall my speed limit tracking project is going well. This is the last (hopefully) issue to resolve.
