### ISSUE TITLE
Stationary zone change

### ISSUE THREAD

**Issue by Tdubs3** [gcobb321/icloud3#325]
If the location of a device does not update for any amount of time longer that the set no movement time, it will be set as stationary. I think the check for setting the stationary zone should include the last update time so that if the phone is not updating it won't change zones. This issue only would occur for users who significantly lower the movement time setting for stationary zones. There also probably should be a limit to force set stationary if the device is offline for an extended period of time.

**Comment by gcobb321** [comment]
Reopen this issue if f you are still having a problem.
