### ISSUE TITLE
Cannot remove an erroneous old device

### ISSUE THREAD

**Issue by happy-chap** [gcobb321/icloud3#335]
Hi,

I've recently removed an old iPhone from iCloud3 monitoring (running v3.0.2 under a full install of HAOS) using the configuration screens in iCloud3, and whilst it has been removed from the configuration menus within iCloud3 (ie. it no longer appears in the list of FamShr devices currently being monitored), it's still showing up in Devices list under the iCloud3 integration within Home Assistant (ie. if you go into Settings->Integrations->iCloud3->Devices it is still showing, although if you click on it, it says the devices has no Entities and no data is reported).

I'm not sure if this is an iCloud3 integration issue or a main Home Assistant error, but do you have any advice on how I can remove the Device?

Thanks, HC.

**Comment by gcobb321** [comment]
You can delete orphaned entities on the _Devices & services > Entities_ screen.
1. Click the icon between Filter and Search at the top.
2. Click the Check Box in the Headings line to highlight everything.
3. Click the 3-dots in the upper right and select Remove Selected. A confirmation screen is displayed that will say you can only remove X of X devices selected. 
4. Select Remove and they will be removed. No valid entities will be removed.

**Comment by gcobb321** [comment]
Reopen this issue if f you are still having a problem.
