### ISSUE TITLE
icloud3 when click on person in icloud3 v3 event log

### ISSUE THREAD

**Issue by rkpollack** [gcobb321/icloud3#337]
Get following pop-up box message at bottom of screen

Failed to call service icloud3/action.time data '00am' does not match format %l%p

**Comment by gcobb321** [comment]
Could you provide more info on the steps you are doing to create the error. 
Are you clicking something on the screen? 
Are you calling the action service from an automation?
What version of iCloud3 are you running?

**Comment by gcobb321** [comment]
Reopen this issue if f you are still having a problem.
