### ISSUE TITLE
How did delete

### ISSUE THREAD

**Issue by captcurrent** [gcobb321/icloud3#341]
I have deleted Al yaml related entities and I am still getting updates.  How do I remove the app

**Comment by gcobb321** [comment]
Delete the _config/custom_components/icloud3_ directory. Were you running the old v2.4.7 or the new v3 that was just released.

**Comment by captcurrent** [comment]
2.4.7.  I deleted that and ha keeps trying. To update

**Comment by gcobb321** [comment]
Did you remove the platform: icloud3 statements from the configuration.yaml file and restart HA?

**Comment by captcurrent** [comment]
I think it was a issue limited to HACS which want to update what wasn’t there any more

I delete it from HACS integrations and appears happy

This
