### ISSUE TITLE
HA reboot/update?

### ISSUE THREAD

**Issue by tokroth** [gcobb321/icloud3#343]
Hi,

what is the best practice (easiest) way to force device tracker updates after HA reboot (usually due to software updates). All my device trackers start ”away”, but we might all be home… or can you set device trackers to persistent storage?

**Comment by gcobb321** [comment]
What version of iCloud3 are you running?

iCloud3 v3 restores the device _tracker and sensor state values on a  restart  before the initial locate.

**Comment by gcobb321** [comment]
Reopen issue if you are still having a problem or question.
