### ISSUE TITLE
one one of our iPhones we get  Old Location/Other Error-Location > Old #3, 15 mins ago, RetryAt-21:47:30 (15 secs)

### ISSUE THREAD

**Issue by AlexanderTurnowsky** [gcobb321/icloud3#344]
I setup all things it was working great in the past with v3.0.5.0. In the last days (i think with the latest version) i get the following problem one one of the iPhones:
petra_iphone Old Location/Other Error-Location > Old #3, 15 mins ago, RetryAt-21:47:30 (15 secs)

the location will no longer update. When i'm restarting HA it is working for a few minutes or 1-2 hours. After that the problem accour again. 

Version used: iCloud3 v3.0.5.1
HA latest and greatest.

I tried a few things.
- deleted device and reregister it in iCloud3. Same result.
- deleted all configuration, setup up all new -- same result
- maybe the problem is about the naming as its Petras iPhone(3). there different old ones with the similar names in the icloud account.

What needs to be cleaned from the log so that my data are secure?

Thx
Alex

**Comment by gcobb321** [comment]
I found a problem with selecting the correct device to track when there are multiple devices in the Family Sharing list with the same name that was introduced in v3.0.5.1.

I have posted an update, v3.0.5.2, that should fix the problem. Go [here](https://github.com/gcobb321/icloud3_v3/issues/305) for an explanation and the update. Scroll to the last entry or one close to the bottom. 

Here is the update …
Unzip the v3.0.5.2 zip file into the icloud3 directory and restart HA.
[icloud3 v3.0.5.2.zip](https://github.com/gcobb321/icloud3_v3/files/15484701/icloud3.v3.0.5.2.zip)

 It is not available on HACS

**Comment by AlexanderTurnowsky** [comment]
thank you i renamed the device and all is working again. Thank you for the great addon

**Comment by gcobb321** [comment]
I just saw your question. Having an old location and then retrying is normal since Apple may just return the last known location when it can not get a good one due to poor cell service, gps accuracy errors, etc. iCloud3 will ask for the location again when this happens until a good l location is received. My phone goes offline when it is in a building with a lot of medical equipment or in a large office building.
