### ISSUE TITLE
iCloud Password not updating

### ISSUE THREAD

**Issue by lordexorr** [gcobb321/icloud3#346]
I recently reset my iCloud Password and when attempting to update it in iCloud3 it succeeds (by this I mean I get the notification on my phone and enter the code into iCloud3) but then when iCloud3 restarts it says it failed to login and when I go back into the configuration my old password is still there. I've tried to sign back in multiple times and the issue continues. I'm running the latest release - 3.0.5.2.

**Comment by gcobb321** [comment]
I'll look at that,. But try the _Log out_ option which will clear the username/password field and then enter the new one.

**Comment by lordexorr** [comment]
That did it. Thank you.
