### ISSUE TITLE
Integration not load after latest update of HA

### ISSUE THREAD

**Issue by Liionboy** [gcobb321/icloud3#354]
![image](https://github.com/gcobb321/icloud3/assets/87735636/072b9eac-e94b-4822-8d69-e975e2a61170)

I have installed version 3.0.5.2

**Comment by gcobb321** [comment]
See [here]([Setup failed for 'icloud3': Integration not found · Issue #310 · gcobb321/icloud3_v3](https://github.com/gcobb321/icloud3_v3/issues/310)) for instructions. Scroll to the bottom.

**Comment by gcobb321** [comment]
iCloud3 v3.0.5.5 (7/16/2024) has been released that fixes this problem. It should be available on HACS in a day or so. No other changes have been made.

**Comment by gcobb321** [comment]
Completed with iCloud3 v3.0.5.5/v3.0.5.6
