### ISSUE TITLE
Temporary fix to iCloud3 not loading after HA 2024.7.x update

### ISSUE THREAD

**Issue by gcobb321** [gcobb321/icloud3#356]
iCloud3 inserts special code into the HA recorder that automatically excludes some text based iCloud3 sensors from the HA log database. HA release 2024.7 broke this and 2024.7.2 prevented iCloud3 from loading if it tried to do this injection. 

I am back from Switzerland. After replacing the video board on my computer after it failed the smoke test when powering it up and resurrecting an old RPi after my main one failed to boot, I’ll be working on an update to fix the problem created by the HA 2024.7.x release. In the meantime, I have updated the code in GitHub.
1. Download the _support/recorder_prefilter.py_ file in the iCloud3 GitHub repository [here](https://github.com/gcobb321/icloud3_v3/blob/main/custom_components/icloud3/support/recorder_prefilter.py) and save it to the icloud3/support directory. (Look for ‘Raw’ in the menu bar above the code on the right. The Download icon is the 2nd icon to the right)
2. Edit the _icloud3/manifest.json_ file. Change the version value from “3.0.5.2” to “3.0.5.3”. 
3. Restart HA.

The _Event Log_ also adds a large item into the log and will generate a warning message in the Error Log.  To stop the warning message and exclude this sensor from being added, add the following to the _configuration.yaml_ file.  It adds a manual exclude for sensor. 

```
recorder:
  exclude:
    entities:
      - sensor.icloud3_event_log
```

**Comment by varenc** [comment]
Just did this and can confirm it works!  For those that need a little help with shell commands, this is roughly what I did on my HomeAssistantOS machine [over SSH](https://github.com/hassio-addons/addon-ssh).


```sh
$ cd ~/homeassistant/custom_components/icloud3/support
$ mv recorder_prefilter.py recorder_prefilter.py.OLD_VERSION
$ wget https://github.com/gcobb321/icloud3_v3/raw/main/custom_components/icloud3/support/recorder_prefilter.py
$ cd ~/homeassistant/custom_components/icloud3/
$ sed -i 's/"version": "3.0.5.2"/"version": "3.0.5.3"/' manifest.json  # this just modifies the version number. Or use an editor like `nano`.
$ ha core restart  # (or just restart HA from the GUI)
```

Big thanks to @gcobb321  for creating such a useful integration and working hard to help users like us even while they're traveling. Thank you!

edit: I went hard on overkill and automated the above process into a simple-ish script! Find it here: https://gist.github.com/varenc/243eeed5622f0e749367b2f9e9d73a38

**Comment by NickVulkers** [comment]
@gcobb321 Have you thought about allowing others to create releases like this? Having to do things like this is not something every user wants to do, or comfortably does. I think that a lot of users won't even think about looking at this repository and navigating through the reported issues to find this solution.

**Comment by gcobb321** [comment]
This was an unusual situation where an HA release broke some code, I was not home and the SSL certificate expired while I was away so I could not log into my HA server.  

I did a patch to the GitHub code and posted instructions all over the place. See [here](https://github.com/gcobb321/icloud3/issues/356) for a temporary solution to this problem. Scroll to the bottom and follow the instructions to get iCloud3 going again. An update will be released soon. 

The above post is probably for a special installation. 

I’ll have a new release out next week on HACS and the GitHub repository. I would welcome someone else being able to do a patch/fix while I’m away. Are you interested?

**Comment by strickersuk** [comment]
I can't help with the coding Gary, but I do appreciate your efforts whilst on holiday, enjoy the rest of it.

**Comment by dmcnaugh15** [comment]
Thank you for the temp fix!  Easy.  Works.

**Comment by markcshaz** [comment]
thanks for an awesome integration and for the support.

**Comment by gcobb321** [comment]
iCloud3 v3.0.5.5 (7/16/2024) has been released that fixes this problem. It should be available on HACS in a day or so. No other changes have been made.

**Comment by wookash** [comment]
> iCloud3 v3.0.5.5 (7/16/2024) has been released that fixes this problem. It should be available on HACS in a day or so. No other changes have been made.

I've just tried and it did not work for me, I've used this and it worked (I've changed version to 3.0.5.6):

> Just did this and can confirm it works! For those that need a little help with shell commands, this is roughly what I did on my HomeAssistantOS machine [over SSH](https://github.com/hassio-addons/addon-ssh).
> 
> ```shell
> $ cd ~/homeassistant/custom_components/icloud3/support
> $ mv recorder_prefilter.py recorder_prefilter.py.OLD_VERSION
> $ wget https://github.com/gcobb321/icloud3_v3/raw/main/custom_components/icloud3/support/recorder_prefilter.py
> $ cd ~/homeassistant/custom_components/icloud3/
> $ sed -i 's/"version": "3.0.5.2"/"version": "3.0.5.3"/' manifest.json  # this just modifies the version number. Or use an editor like `nano`.
> $ ha core restart  # (or just restart HA from the GUI)
> ```
> 
> Big thanks to @gcobb321 for creating such a useful integration and working hard to help users like us even while they're traveling. Thank you!
> 
> edit: I went hard on overkill and automated the above process into a simple-ish script! Find it here: https://gist.github.com/varenc/243eeed5622f0e749367b2f9e9d73a38

**Comment by gcobb321** [comment]
HACS was the problem. It was downloading the v3.0.5.2 release, not the v3.0.5.5 release even though the zip file for the release was correct and the files were correct. I will create a new release and see what happens.

Here is the v3.0.5.5 zip file.
[icloud3.zip](https://github.com/user-attachments/files/16253192/icloud3.zip)

**Comment by gcobb321** [comment]
It was my error. I did everything except update the _custom_components/icloud3_ code files on the GitHub repository so it was picking up v3.0.5.2 code instead. 

All is good now. HACS updates the files  with the v3.0.5.5 version after refreshing via the _Update Information_ option.

**Comment by reisueber** [comment]
Is iCloud3 still blocked with version 2024.7.3? I can't find any indication in the release notes that it is no longer the case.

**Comment by gcobb321** [comment]
iCloud3 v3.0.5.5 removes the offending code that was causing HA lock up.  I just updated to 2024.7.3 and all is well.

**Comment by gcobb321** [comment]
Completed with iCloud3 v3.0.5.5/v3.0.5.6
