### ISSUE TITLE
Installation - Can't find the Integration

### ISSUE THREAD

**Issue by MixedTape1992** [gcobb321/icloud3#358]
I try to install iCloud3 v3 the first time. But after adding the repository I can't find the Integration. If I type iCloud I only find the typical Integration of Apple. 

<img width="537" alt="Bildschirmfoto 2024-07-14 um 09 48 12" src="https://github.com/user-attachments/assets/44c39ead-8678-4707-9f0e-e7efe9bba48e">

I tried to remove the repository from HACS and add it new. Doesn't work.

**Comment by gcobb321** [comment]
Make sure iCloud3 has been installed in the _config/custom_components/icloud3_ directory. Then see [here](https://github.com/gcobb321/icloud3/issues/356) for a temporary solution to this problem. Scroll to the bottom and follow the instructions to get iCloud3 going again. An update will be released soon. 

Hopefully this will get it up and running again.

**Comment by McWuragu** [comment]
Changlog HA 2024.7.2

"Block icloud3 custom integration from breaking the recorder ([@frenck](https://github.com/frenck) - [#121658](https://github.com/home-assistant/core/pull/121658))"

**Comment by gcobb321** [comment]
iCloud3 v3.0.5.5 (7/16/2024) has been released that fixes this problem. It should be available on HACS in a day or so. No other changes have been made.

**Comment by gcobb321** [comment]
Completed with iCloud3 v3.0.5.5/v3.0.5.6
