### ISSUE TITLE
Configuration warnings Platform error 'device_tracker' from integration 'icloud3' - Integration 'icloud3' not found.

### ISSUE THREAD

**Issue by russellmoran99** [gcobb321/icloud3#359]
After the latest upgrade, I have encountered this error:

Configuration warnings
Platform error 'device_tracker' from integration 'icloud3' - Integration 'icloud3' not found.

**Comment by gcobb321** [comment]
See [here](https://github.com/gcobb321/icloud3/issues/356) for a temporary solution to this problem. Scroll to the bottom and follow the instructions to get iCloud3 going again. An update will be released soon.

**Comment by Guenter61** [comment]
Thank you very much!!!

**Comment by gcobb321** [comment]
iCloud3 v3.0.5.5 (7/16/2024) has been released that fixes this problem. It should be available on HACS in a day or so. No other changes have been made.

**Comment by gcobb321** [comment]
Completed with iCloud3 v3.0.5.5/v3.0.5.6
