### ISSUE TITLE
iPhone HomeDistance Not going to 0 when arrived home

### ISSUE THREAD

**Issue by barney34** [gcobb321/icloud3#360]
I dont know if this is how it should work but I would think when arriving home the HomeDistance variable should change to 0 as of last night my wifes phone without the home assistant app had a little drift and an event was triggered but the "and if" looks for HomeDistance over x value.   Well it still had the value from mid day when she traveled to the store so the automation executed.    When does the HomeDistance reset or how can I force it to reset?

![image](https://github.com/user-attachments/assets/49b26cf5-08d6-4eed-82bd-e2fd83fb9d32)

**Comment by gcobb321** [comment]
iCloud3 shows the distance to the center of the zone even when it is inside a zone's radius. The HomeDistance sensor will always show this distance and will not actually reset to 0 when in the Home zone. Right now, my HomeDistance sensor is  0.01903. The unit of measure is miles so that is 100.5ft or 30.6m

**Comment by barney34** [comment]
what about the max distance that should reset when you arrive home so you can use it again and again when leaving or coming home

**Comment by gcobb321** [comment]
As I recall from a long time ago, doing it when you arrive caused problems when you arrive home a the Mobile App EnterZone trigger. The distance was reset to 0 and the automation would not run. I think it is now reset a few minutes after arriving Home so you have time for the automation to trigger.

**Comment by gcobb321** [comment]
I was doing it that way before I added the `went_3km` distance. I would use that to not issue a trigger to open my garage door when I arrived home after walking my dog. See the Sample Automations in the iCloud3 docs for what I am doing.
