### ISSUE TITLE
HA 2024.7.4 CREATES PROBLEMS WITH ICLOUD3

### ISSUE THREAD

**Issue by gcobb321** [gcobb321/icloud3#366]
The 2024.7.4 HA update causes problems that I think are related to getting data from the Apple iCloud Account. 

This stops iCloud3 from tracking devices since it can not get location data and creates error adding and updating devices on the configuration screens since the devices in the Family Sharing account are not known.

Stay tuned...

**Comment by andyblac** [comment]
is this also related to my sign-in issue ?
