### ISSUE TITLE
How to remove devices?

### ISSUE THREAD

**Issue by raptile** [gcobb321/icloud3#368]
I see 6 device trackers but only two real ones when i say i want to update or remove them.

How do i remove all de the device trackers that i don't want to use?

The devices in the list are marked as "Used by iCloud3 device" but i do not see them when i use the "Configure" option to update or delete devices.

Thanks in advance!

**Comment by gcobb321** [comment]
1. Make sure the devices are not in the `known_devices.yaml` file.
2. Make sure there is no  `platform: icloud3` entry in your `configuration.yaml` file.
3. Go to _Devices & Settings > entities_. Click the pulldown icon at the top where you check all devices (2nd from the right). Check it to select everything. Click the 3-dots on the upper-left, Select Delete. You will see a message that only xx of xx devices can be deleted. Click Delete to delete the unused entities. Reboot HA.

**Comment by raptile** [comment]
Thats what i tried.

Here i have 3 devices.
I want to remove two of them.

<img width="479" alt="image" src="https://github.com/user-attachments/assets/2702f2de-3562-40d8-bd18-0211aa59a7d4">

But when i search for the entities, i do not see them in the list:
<img width="1449" alt="image" src="https://github.com/user-attachments/assets/f952e7a5-c8da-473e-b2bc-d836d34e8c67">

I only see 1 and that's not an icloud3 device.

Any other idea on how to remove them?

When i try to delete it from the config option i do not see the ones i want to delete:
<img width="583" alt="image" src="https://github.com/user-attachments/assets/ba6d41f1-5950-446c-9594-fc13b3da5f72">

**Comment by gcobb321** [comment]
Maybe use the _Developer Tools_ on the hay sidebar and see if you can see them and use their attributes to see where they are coming from and who owns them. You could always make copies of the .storage/conf_device_registry and conf_entity _registry. Then open the files in an editor and look for them and then delete their entries. Do this only if you know what you are doing. You don’t want to make any mistakes and cause problems requiring a restore. 

Or disable your integrations, reboot twice and try to delete them again.

**Comment by gcobb321** [comment]
Also, What devices are listed when you go to the iCloud3 configure screen where it shows the devices and entire counts. You can click devices to filter by the iCloud3 integration and the same thing for entities.

**Comment by raptile** [comment]
I can see them in the developer tools:
<img width="799" alt="image" src="https://github.com/user-attachments/assets/f7bb00f9-427d-4b63-8a66-e4511c691c4b">

<img width="1144" alt="image" src="https://github.com/user-attachments/assets/1bac586e-776b-4ae4-82a6-4447e28af6d5">

I dont understand what u mean with this:
"Also, What devices are listed when you go to the iCloud3 configure screen where it shows the devices and entire counts. You can click devices to filter by the iCloud3 integration and the same thing for entities."

That's what i've printed above right?

They are only in the icloud 3 integration but it does not show them here:
<img width="585" alt="image" src="https://github.com/user-attachments/assets/4343acab-eb8d-442a-a0de-3bf037ac0a24">

**Comment by raptile** [comment]
And do u mean `.storage/core.device_registry` and `.storage/core.entity_registry`?

When i search for the names i see them in the core.device_registry and icloud3:
<img width="1362" alt="image" src="https://github.com/user-attachments/assets/48cc63ba-6137-4c43-9283-46b825ad1d67">

They both have the same tracker name as entity as far as i can tell: `device_tracker_iphone_van_daniella`

When i search for that, i see them in the core.device_registry, core.entity_registry and icloud3:
<img width="1367" alt="image" src="https://github.com/user-attachments/assets/e14e23a6-0e2a-47a5-a103-9221c05c24d1">

**Comment by gcobb321** [comment]
Earlier I was referring to this screen and the device_trackers and entities. 

![image](https://github.com/user-attachments/assets/113d7c6d-65c1-4af9-beba-520044b15774)

This is really an HA device_tracker/entity registry issue and it is difficult to offer any more advice on how to remove them from HA. I would just go to the `Devices & settings > Entities` and see if they can be renamed, deleted or disabled.
