### ISSUE TITLE
Arrival time with date?

### ISSUE THREAD

**Issue by Airblader** [gcobb321/icloud3#376]
Currently the arrival_time is a local time only. Is there a way to get it with a date? Currently I kind of augment it with the date of when I entered the zone.

**Comment by Airblader** [comment]
Ah, I suppose I can use the sensor's sensor_updated attribute?

**Comment by gcobb321** [comment]
That would be the only way to do it. The date is not part of the State Value.

**Comment by Airblader** [comment]
Any downside to using that, or will that contain the correct value?

**Comment by gcobb321** [comment]
None at all. It is just the full data/time of the State value that is just the time part.

**Comment by Airblader** [comment]
Perfect, thank you. Closing this then.
