### ISSUE TITLE
How do I create an iCloud account with 2FA?

### ISSUE THREAD

**Issue by tmchow** [gcobb321/icloud3#39]
I want to try to use the "Find My" sharing method, but it requires an iCloud account without 2FA.  I can't find a way to create an iCloud account without it. I've tried on my mac through a browser and on the browser on my iPhone. During the account creation process, you are forced to give a phone #, and after creation, no way to turn it off in settings.

Did Apple just force 2FA on everyone now and thus breaking this sharing method with iCloud3?

**Comment by gcobb321** [comment]
iCloud3 v2.2.0, the next version to be released, let’s you track devices using the ‘Family Sharing’ tracking method on 2fa accounts. It should be available next week. You can get a prerelease version from the *development_2.2.0rc5’ directory on the iCloud3 GitHub repository  at https://github.com/gcobb321/icloud3/tree/master/development%20v2.2.0-rc5. The change log in that directory has the install instructions.

————————
Gary Cobb

**Comment by tmchow** [comment]
@gcobb321 Thanks! I'll try it out. Have you considered making these pre-releases easier to install by marking them as "pre-releases" for HACS so we can install via HACS vs manually?

**Comment by tmchow** [comment]
Confirmed that this works with iCloud3 v2.2.0rc5 so closing the issue.

**Comment by xvolte** [comment]
Hello,
when i set up my icloud account, i get a notification on my iphone saying someone is accessing icloud. Fine by me. Then i click approve on my phone, and i get a 6 digit code that i should enter somewhere. unfortunately, there is no pop up or notification asking me for the code. 
Where can i put this code ?

**Comment by gcobb321** [comment]
You need to be using the iCloud3 v2.2.0 release candidate to use the FamShr tracking method. See [this answer](https://community.home-assistant.io/t/icloud3-v2-1-device-tracker-advanced-tracking-features-ios-app-monitoring/148943/512?u=gcobb321) for more info on rc10.

That 6-digit code is not used. More info is in the docs [here](https://gcobb321.github.io/icloud3_docs/#/chapters/1-setting-up-icloud-account?id=family-sharing-famshr-tracking-method). The final docs will have a better answer when I can get to it.

**Comment by 26tajeen** [comment]
Hi Gary, sorry to bother you. I'm currently using (and loving) the component using family sharing but being utterly plagued by the constant 2FA alerts on my phone. So now I'm trying to move over to the Find-my platform in the hope that will give the same good tracking but without the alerts. To that end I created a new iCloud account but it enabled 2FA by default and I can't turn it off.
I'm really confused how I can use the component WITH 2FA (as there seems to be no way to avoid 2FA now?) and without the constant notifications. Any help much appreciated!! Thank you

**Comment by gcobb321** [comment]
V2.1 does not support 2fa. V2.2 in the Release Candidate directory does. Download and unzip the zip file and it will work. 

I just uploaded the v2.2 docs in preparation for the final release of that version on Friday.
