### ISSUE TITLE
❌ Entry Error, Invalid Username or Password

### ISSUE THREAD

**Issue by GarfieldMZ** [gcobb321/icloud3#393]
I'm trying to login into my icloud account but I always getting "❌ Entry Error, Invalid Username or Password".
Already uninstalled icloud3, deleted the complete icloud3 folder and restarted HA. Downloaded and installed icloud3 (v3.1.2) again with the same result. 
Can anyone help me solve the problem?

Thx!

**Comment by gcobb321** [comment]
Are you logging in on the _Configure Settings > Username Password_ screen or is that message in the _Event Log_. If in the _Event Log_, go to the _Configure Settings > Data Sources_ and verify the values in the Username Password screen

**Comment by GarfieldMZ** [comment]
> Are you logging in on the _Configure Settings > Username Password_ screen or is that message in the _Event Log_. If in the _Event Log_, go to the _Configure Settings > Data Sources_ and verify the values in the Username Password screen

I'm in the config settings to do the initial configuration after new installation.
The error message is shown in the samw window where I put in my username and password .

**Comment by gcobb321** [comment]
Try erasing it with the Stop Using This Apple Account, save it and then add it again

**Comment by GarfieldMZ** [comment]
I tried this and got an error message "Unknown error occurred". 
Nevertheless I tried again to login after this action and it seems to be working now.

Thank you for your help!!

**Comment by AlfaJackal** [comment]
Same issue here after changing my AppleID password. I then tried to stop using an AppleID and re-entered the account details. Tried all of the above. No luck. Double checked login data. 

Any ideas how to fix it? I am on 3.1.3

**Comment by gcobb321** [comment]
Are there any password related messages in the _Event Log_?  They would be in the Startup Stage 4 area.

**Comment by AlfaJackal** [comment]
Nothing in Stage 4
![image](https://github.com/user-attachments/assets/4eb4cc1e-8e28-4fba-bc2f-70fe1166703e)

And all the other messages in log file are referring to not having an account set up.

**Comment by AlfaJackal** [comment]
Found the issue: In configuration file there were no `apple_accounts` written. Had to manually add it. It seems that there might be a bug because deleting an Apple account from the configurator didn't work.

This is correct:
```
  "data": {
    "tracking": {
      "username": "JohnDoe",
      "password": "««secret==»»",
      "apple_accounts": [
        {
          "username": "JohnDoe",
          "password": "««secret==»»",
          "totp_key": "",
          "locate_all": true
        }
      ],
```

This was mine after changing the password and trying to update the account details:
```
"apple_accounts": [],
```

**Comment by gcobb321** [comment]
@AlfaJackal 
The _Invalid Username/Password _ message would be confusing if an Apple account had never been added. I’ll change the message in the next release. 

Did you ever go to _Configure > Data Sources-Apple Accts & MobApp _ screen and select _Add Apple Account _ and then add one? That will add one like you did by editing the config file.

**Comment by AlfaJackal** [comment]
Yes, I did that several times. Not sure what happened but my iCloud3 stopped working - I am using it more than two years, always latest version.

My history with this issue:
1. Had installed previous versions (I think 3.1.2)
2. Changed Apple ID password
3. Noticed iCloud3 stopped pulling data
4. Went to _configure > Data Sources > Selected Existing Apple iCloud Account > Entered new Password_ 
5. Error showed up (see my initial comment)
6. Tried _Stop Using an Apple Account_ which didn't remove the Account but showed the error
7. Updated to 3.1.3
8. Tried steps 4-6 again with no success
9. Deleted iCloud3 completely, including icloud3 folder (but except .storage/icloud3
10. Reinstalled everything and tried 4-6 again with no success

I then noticed the misconfigurated configuration file.

**Comment by gcobb321** [comment]
@AlfaJackal 
I found the error where the Apple account was not being deleted when you stop using it. And will check out changing p/w when I get home.

**Comment by realschmidt** [comment]
hello, 

I have the same problem. Even after deleting and downloading again several times, I get the same error. I previously had the problem that the location was no longer tracked. After I saw that the Apple account in icloudV3 was no longer tracking devices, I reset everything and tried a new installation. But now the mentioned error occurs. It was also not possible to receive a new verification code and no request was sent before the "Entry error..." occurred the first time.

Thanks

**Comment by gcobb321** [comment]
@realschmidt
See [here](https://github.com/gcobb321/icloud3/issues/401#issue-2695511469) for more information about this problem
