### ISSUE TITLE
iCloud 3 v3: Event Log - How to update in Firefox?

### ISSUE THREAD

**Issue by MichaelSchaaf999** [gcobb321/icloud3#399]
Dear Gary,
in Chrome I was able to update the Event Log as you can see:
<img width="276" alt="grafik" src="https://github.com/user-attachments/assets/dee1e1e0-27d5-4dcd-9dec-8016daa561f1">
But in Firefox (and on the iphone?) this does not work:
<img width="500" alt="grafik" src="https://github.com/user-attachments/assets/2221d993-0efe-4d16-9aaa-3d6d745446f2">
<img width="286" alt="grafik" src="https://github.com/user-attachments/assets/324902cf-077a-41ca-8e0b-be07c92bc67d">

What do you recommend here to update as required?

Best regards
Michael

**Comment by gcobb321** [comment]
For the HA Companion App, see [here](https://gcobb321.github.io/icloud3_v3_docs/#/chapters/3.2-installing-and-configuring?id=clearing-the-browser39s-cache)
For Firefox, try googling Clear Browser Cache. You are on your own there.

**Comment by MichaelSchaaf999** [comment]
Excellent and very fast support, sorry for bothering you.

**Comment by MichaelSchaaf999** [comment]
Dear Gary,

thanks a lot.
- HA Companion App: This worked fine.
- Firefox: We like to use Chrome but for some reasons there is still a FireFox installation here on the Mac.
  You don’t like / don’t use FireFox? For whatever your reasons are: The Google search showed this:
  https://oit.colorado.edu/tutorial/clear-web-browser-cache-firefox
  and this worked fine for FireFox.
  Never had to to this before, that’s the reason we did not know.

Kind regards
Michael


Michael Claßen  | fon +49 172  52 33 6 33  | fax +49  7172  30 64 98 4   |  Härtsfeldstr. 1  73553 Alfdorf   | mail: ***@***.***



------ Originalnachricht ------
Von "Gary Cobb" ***@***.******@***.***>>
An "gcobb321/icloud3" ***@***.******@***.***>>
Cc "Michael Schaaf" ***@***.******@***.***>>; "Author" ***@***.******@***.***>>
Datum 19.11.2024 16:17:06
Betreff Re: [gcobb321/icloud3] iCloud 3 v3: Event Log - How to update in Firefox? (Issue #399)


For the HA Companion App, see here<https://gcobb321.github.io/icloud3_v3_docs/#/chapters/3.2-installing-and-configuring?id=clearing-the-browser39s-cache>
For Firefox, try googling Clear Browser Cache. You are on your own there.

**Comment by gcobb321** [comment]
This only happens when I make changes to the _Event Log_ custom card, which is rare.
