### ISSUE TITLE
hard coded config directory at /config

### ISSUE THREAD

**Issue by jeyrb** [gcobb321/icloud3#4]
Failure at startup when looking for .storage/core_entity_registry because het path is hard coded for /config

There's an API call to get hold of the registry at hass.helpers.entity_registry

**Comment by gcobb321** [comment]
This can be overridden with the `entity_registry_file_name` configuration parameter described [here](https://gcobb321.github.io/icloud3/#/chapters/2-config-parms).

Thanks for the suggestion. However, like most APIs in the helpers and components reference section, there is no documentation on how to call it, what it returns and what to do then. Pointers to example code would be helpful. Most of the under-the-cover HA code is great if you know your way around the HA internals. I'm an apps guy, not a systems coder guy so I don't . I spent several days trying to figure out how to use their api's without success and then spent 30-minutes getting the file, scanning for what I needed and then using the few pieces of info tie HA iOS App v2 to iCloud3.

**Comment by gcobb321** [comment]
I would welcome the assistance if you are familiar with the inner workings of HA and want to show me how to use the api's to read the registry file,

**Comment by jeyrb** [comment]
I’m only recently moved to HASS from Domoticz. I’ll give it a go when I get time and send a PR

**Comment by gcobb321** [comment]
I look forward to working with you. I keep the ‘icloud3_dev’ development repository in sync with the ‘iCloud3’ repository when I upload updates. This provides a mechanism of having both a production version available for download by general users and another that available for development and testing by others. Any changes you make and PRs should be against the development ‘icloud3_dev’ repository. After checking everything out, I promote development versions to the production ‘iCloud3’ repository.

**Comment by ludeeus** [comment]
For storing files in `.storage` you should look at `homeassistant.helpers.storage` [example](https://github.com/hacs/integration/blob/master/custom_components/hacs/store.py)

To get the configuration dir on _any_ HA install use `hass.config.path()`

**Comment by gcobb321** [comment]
iCloud3 v2.0.6 addresses this issue. See the change.log for more into.

I just updated the iCloud3 v2.0.6 release candidate in the 'development v2.0.6' directory in the iCloud3 GitHub repository [here](https://github.com/gcobb321/icloud3/tree/master/development%20v2.0.6) . Download the 'device_tracker.py' and 'pyicloud3_ic3.py' files and copy them to the 'custom_components/icloud3' directory.
