### ISSUE TITLE
3.0.5.9: Logged into Apple Account but no devices are shown

### ISSUE THREAD

**Issue by MichaelSchaaf999** [gcobb321/icloud3#403]
<img width="688" alt="image" src="https://github.com/user-attachments/assets/fc20c8d3-5ec2-4644-9668-5fab46c1aca5">
Anything I can do about it?

**Comment by OskarBrink** [comment]
I seem to be having a similar issue. Running version 3.1.3 and login is not working properly. Also not getting the 2FA code from apple. The integrations give message that the icloud3 parameters have been updated successsfully, but nothing else happens.

Message in the log:
🔺 XXXXXXX, POST, REQUEST,  VALIDATE_USERNAME_PASSWORD/541
❗   items={'url': 'setup.icloud.com/setup/authenticate/XXXXXXX@…………', 'retry': 0, 'data': None, 'json': None}
❗   headers={'Authorization': 'Basic ……N1bQ=='}
12-09 13:42:08 [pyicloud_ic3:0259] CONFIG
🔻 XXXXXXX, POST, RESPONSE, VALIDATE_USERNAME_PASSWORD/541 
❗   items={'code': 409, 'ok': False}

**Comment by emaa10** [comment]
Same here.

**Comment by JimDotR** [comment]
same

**Comment by gcobb321** [comment]
v3.1.3 does not work due to Apple reverting the the old password authentication method, You need to downgrade to v3.0.5.9 until I post a fix (hopefully next week end)

See the issue [here](https://github.com/gcobb321/icloud3/issues/401#issue-2695511469)

**Comment by JimDotR** [comment]
Thanks Gary. Sorry I didn’t realize you mentioned this elsewhere.

**Comment by OskarBrink** [comment]
I had missed this as well.
Thanks

**Comment by MichaelSchaaf999** [comment]
But this issue here for me is with version 3.0.5.9, as suggested:
<img width="347" alt="image" src="https://github.com/user-attachments/assets/18949b68-a88b-46fd-88c2-6b983b63090f" />
So the app seems to find apple devices and the iPhones:
<img width="559" alt="image" src="https://github.com/user-attachments/assets/d608cc34-7fe4-4ea3-8f4f-41b98134c9e3" />
But what is meant with "Not assigned to an iCloud3 device"?

**Comment by gcobb321** [comment]
Now I understand. The Apple device (and HA mobile app device) needs to be associated with the icloud3 device so iCloud3 can locate it using the correct Apple device. The message on the _Event Log_ is saying this has not been done. Go to the _Configure > iCloud3 Devices > Select > Update Device_ screen for each iCloud3 device and select the Apple and mobile app device providing location data. 

See the iCloud3 docs [here](https://gcobb321.github.io/icloud3_v3_docs/#/chapters/2.1-icloud-account?id=assigning-the-family-sharing-device) for more information

**Comment by MichaelSchaaf999** [comment]
I understand that the iphone devices have to be associated with iCloud3.
But...   How?
You tell me "Go to the Configure > iCloud3 Devices > Select > Update Device screen".
But I do not see a "Update device screen here" in the configuring part on the HA client on the Mac:
<img width="787" alt="image" src="https://github.com/user-attachments/assets/8c591192-96fb-4146-aa6b-c2b576a8626b" />

After clicking "ok" in the above screen this is shown:
<img width="683" alt="image" src="https://github.com/user-attachments/assets/3a77492c-f38c-43fc-9059-f53eb9734fb1" />
So where is the "Update Device screen" part you are mentioning here?
In HA on an iPhone? I cannot find this.

**Comment by JimDotR** [comment]
Michael - you would click OK on that screen as well and add your device. Did you read the docs that Gary linked to? It is pretty well outlined there.

**Comment by bkr1969** [comment]
This does not work for me at all.

**Comment by buds** [comment]
I had a similar issue which was due to incorrect file permissions on a folder when installed via HACS.
Might be worth checking.
https://github.com/gcobb321/icloud3_v3/issues/370

**Comment by gcobb321** [comment]
@buds 
I looked at that a while ago and I’m creating the directory using standard Python make directory calls. My directories always have a permission of 777 which it’s full reads, write permission. I could never create them with just read. In running on a RPi4 & 5. Could the HA server system have anything to do with it? Thoughts?

**Comment by gcobb321** [comment]
@bkr1969 
When you select Add Device and click Submit/Weiter, what happens? An error message? Is the Add Devices screen displayed?

**Comment by MichaelSchaaf999** [comment]
@JimDotR: 
> Michael - you would click OK on that screen as well and add your device. Did you read the docs that Gary linked to? It is pretty well outlined there.

There are no devices shown when I follow your advice:
<img width="555" alt="image" src="https://github.com/user-attachments/assets/dbf8d330-4934-4ae6-9c7b-d68113ce8d6e" />

**Comment by JimDotR** [comment]
@MichaelSchaaf999  Again, the docs help you here but you would first make up a name for how your “main” device would appear in HA (I did jim_iphone). Then you give it a friendly name (I did Jim’s Phone). Next screen will allow you to link your iCloud account. Then when you add ANOTHER device you should be able to choose from your iCloud devices.

**Comment by MichaelSchaaf999** [comment]
@JimDotR Yes, I can add a name there but I cannot select from a list of names. If I follow your advice and enter my iPhone's name, then I see this:
<img width="601" alt="image" src="https://github.com/user-attachments/assets/22ae57a8-ffa1-4842-9202-7b29a6be7ba7" />
So this step of the setup does not work for me, sorry.

**Comment by gcobb321** [comment]
Think about it. Each device and sensor must be unique. You can not have one integration create light.kitchen_counter entity and also have another integration also create a light_kitchen_counter entity. The same is true for device tracker entities. 

That message means you already are using the _device_tracker.michael_iphone_ entity in the HA iCloud integration and you need to (1) use another name for iCloud3 or (2) remove the HA iCloud integration which will release that entity name or (3) use another name in the HA iCloud integration (_michael_iphone_ic3_). If you use another name, just be sure you use the ic3 name in dashboard cards and automations. Otherwise, they will show the HA Integration entity.

**Comment by MichaelSchaaf999** [comment]
@gcobb321:  "Each device and sensor must be unique"... Yes, no doubt about that.
"you already are using the device_tracker.michael_iphone entity in the HA iCloud integration..."...  Yes, understood. 

But my understanding was that in the iCloud**3** process I would refer to those devices and sensors that of course are already present in the iCloud integration. I myself did not add the iPhone devices in the iCloud integration (or did I?): This iCloud integration found these devices, so is my understanding.

I am still confused that the iCloud**3** configuration process does not use the already existing devices/sensors. 

If I now follow (1) and use another name for an iPhone in the iCloud**3** integration setup, then I see this:
<img width="563" alt="image" src="https://github.com/user-attachments/assets/7340d6af-5816-4ad7-8994-49869032c841" />
Pressing "ok" leads to this:
<img width="600" alt="image" src="https://github.com/user-attachments/assets/ec8a01f1-b987-4a50-b3d4-205eab9e5adb" />

And this is the conformation:
![image](https://github.com/user-attachments/assets/1a30506c-d881-484e-bdd1-aad52b8a4f79)

and THIS is the iCloud3 event log now:
![image](https://github.com/user-attachments/assets/f53b0562-188f-4210-ac55-0374fe036522)

I think that this looks good now and iCloud3 knows my device.
**I assume that my general fault was not to realize that an artificial name in the iCloud3 integration setup must NOT be the same name as in the iCloud integration. 
I was not aware that iCloud3 needs a name for a device to assign the device it finds in the Apple iCloud.
I was confused that this one and only device/sensor has two names: One in the Apple iCloud integration and one in the iCloud3 integration.** 
Sorry for that.

This is the "long" version of the Event Log just FYI:

<img width="469" alt="image" src="https://github.com/user-attachments/assets/28d7b4ea-9f16-4111-a83f-aa02b0800743" />

**Comment by gcobb321** [comment]
iCloud3 replaces the HA iCloud integration, it is not an add-on to it. It does everything the HA iCloud does and a lot more. You can remove the HA iCloud integration and then you will be able to use the _michael_iphone_ device tracker name in iCloud3

**Comment by MichaelSchaaf999** [comment]
thanks a lot @gcobb321 - understood.

**Comment by gcobb321** [comment]
Your welcome. Glad everything is all set now.
