### ISSUE TITLE
MySQL Exception "Incorrect string value"

### ISSUE THREAD

**Issue by nicx** [gcobb321/icloud3#41]
Hi, I have a lot of errors in my log:

```
2019-05-23 22:04:43 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (MySQLdb._exceptions.OperationalError) (1366, "Incorrect string value: '\\xE2\\x97\\x8FPoo...' for column `homeassistant`.`states`.`state` at row 1")
[SQL: INSERT INTO states (domain, entity_id, state, attributes, event_id, last_changed, last_updated, created, context_id, context_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('sensor', 'sensor.iphone_info', '●Poor GPS, #1, (198.0)', '{"icon": "mdi:information-outline"}', 53381, datetime.datetime(2019, 5, 23, 20, 2, 48, 298601, tzinfo=<UTC>), datetime.datetime(2019, 5, 23, 20, 2, 48, 298601, tzinfo=<UTC>), datetime.datetime(2019, 5, 23, 20, 4, 43, 256440), '5852b0d47e3e441a8ff3a3855cea05b5', None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

any hints what's going wrong here?

**Comment by strfn** [comment]
Having the same issue with MariaDB is spamming my log.

**Comment by gcobb321** [comment]
Looks like HA is having some problems updating the log file. Nothing to do with iCloud3. You might want to restart HA ...

**Comment by nicx** [comment]
did that already multiple times. other components are all logging correctly, its only icloud3 having this problem. maybe its related to the special character in the message?

**Comment by gcobb321** [comment]
Wouldn't think so since the same special characters are used in other messages.  The good accuracy is poor. If you have the iCloud3 command Lovelace screen, try pausing and then resuming to see if you can get a better location reading with better accuracy. You can set the GPS accuracy in the parameters. Try increasing it to see if it passes GPS test.

**Comment by nicx** [comment]
I think I solved it with changing the mariadb default-character-set from latin1 to utf8. The error is no more appearing since some hours now... :)

**Comment by strfn** [comment]
> I think I solved it with changing the mariadb default-character-set from latin1 to utf8. The error is no more appearing since some hours now... :)

Hi @nicx  can you quickly share how you fix it pls ? 
a simple `alter database hassio CHARACTER SET = 'utf8';` didn't;t fix for me unfortunately.

**Comment by nicx** [comment]
@strfn I tried to change the character set with this article: https://mariadb.com/kb/en/library/setting-character-sets-and-collations/

But I ended up in deleting the whole MariaDB docker container and just set it up from scratch with this settings in the my.cnf:

```
[client]
default-character-set = utf8

[mysql]
default-character-set = utf8

[mysqld]
character-set-server = utf8
collation-server = utf8_unicode_ci
```
