### ISSUE TITLE
Documentation of installation directory inconsistent

### ISSUE THREAD

**Issue by deepcoder** [gcobb321/icloud3#45]
Here in your documentation, you specify installing the code in both 'custom-components/icloud' and 'custom-components/icloud3' . Which is correct?

https://gcobb321.github.io/icloud3/#/chapters/1-installation?id=installing-icloud3

'
Create a config/custom_components/icloud directory on the device (Raspberry Pi) running Home Assistant. Copy the five component files in the custom_components-icloud3 GitHub directory (device_tracker.py, pyicloud_ic3.py, init.py, manifest.json, services.yaml) into that directory so the directory structure looks like:

config
  custom_components
    icloud3
      device_tracker.py
      pyicloud_ic3.py
      __init__.py
      manifest.json
      services.yaml

'

**Comment by gcobb321** [comment]
The directory structure is *config/custom_components/icloud3*


Sorry about the confustin. I'm currently updating the docs for v2.2.0 
and will make the corrections.

Gary
------ Original Message ------

**Comment by deepcoder** [comment]
Thank you for the information.
