### ISSUE TITLE
Include HACS support

### ISSUE THREAD

**Issue by riemers** [gcobb321/icloud3#45]
As seen on https://github.com/custom-components/hacs
Would help auto update everything. This is the follow up on the custom_updater.

**Comment by DBa2016** [comment]
Should be addressed by pr#46. Not sure though whether the two lines of code I had to add to HACS are due to the forked repository I had to use or whether it is a HACS bug - I will create a PR for HACS if needed.

**Comment by gcobb321** [comment]
Will check out HACS when I get a chance. Trying to figure out how to get iCloud access working again right now.

**Comment by DBa2016** [comment]
For now, I think renaming the custom_components-icloud3 directory to "custom_components" should be sufficient - that's what my PR is about. Rest seems to be either related to me forking your repo or a bug in HACS, either way I can work on that once the PR has been merged.

**Comment by gcobb321** [comment]
@DBa2016 I'm trying to add the icloud3 custom_components/device_tracker.py (others to follow) file to the  HACS on the HACS Custom Repository and am having all kinds of problems. I've entered lots of combinations including:
```
Starting repository registration for...
gcobb321/icloud3
gcobb321/icloud3/device_tracker.py
gcobb321/icloud3/device_tracker
gcobb321/icloud3/custom_components/device_tracker.py 
gcobb321/icloud3/custom_components/icloud3/device_tracker.py
gcobb321/custom_components/icloud3/device_tracker.py
And Others
```
Did you get HACS to recognize the icloud3 repo?
Should custom_components actually be custom_components/icloud3?

**Comment by DBa2016** [comment]
I had to update 2 or 3vlines of code in HACS - not sure right now whether it is a bug there (its code looks everything but mature, to be honest...) or something else. I will look into it.

**Comment by gcobb321** [comment]
The other custom components used a *custom_components/icloud3* directory structure. I’m going to change to that structure later today for consistency and since I may end up with several custom components to get iCloud access back working again, I’ll also Be pushing an update to be able to send notifications to HA  ios app requesting location info.

**Comment by riemers** [comment]
i'll be a tester ;) since i have it turned off now since it just puts my phone away/home/away/home constantly.

**Comment by DBa2016** [comment]
> 
> 
> @DBa2016 with the _custom_components/icloud3_ structure, What did you use for the repo entry on the settings screen? I’ve tried several combinations (see previous note) and none worked.

You were absolutely right, the directory structure should indeed have been custom_components/icloud3 - I created a PR #47 to fix it (and you already merged it).

The issue can be closed.

**Comment by DBa2016** [comment]
@gcobb321 - I entered “https://github.com/gcobb321/icloud3” as repo URL, that worked.

**Comment by riemers** [comment]
That works for me too, although yesterday it failed on me so i thought i look into it now and now it worked. Funny, but seems ok now. So the issue is resolved, it can be closed :)

**Comment by haakonstorm** [comment]
Sorry to reopen this but I'm having the same issue:
https://github.com/gcobb321/icloud3
```
Could not add 'gcobb321/icloud3' with type 'plugin' at this time.
If you used the correct type, check the log for more details.
```

I've tried all combinations - perhaps you could update the docs on how to install via HACS?
