### ISSUE TITLE
Time display, 12h vs. 24h, local vs. GMT and time zones

### ISSUE THREAD

**Issue by deepcoder** [gcobb321/icloud3#47]
Small issue but important to stay on top of for not 'techie' user, which are so important. There are a lot of causes of the display of time in different formats and this is very frustrating for users. Do all you can to make time and date as clear and logical as possible:

<img width="558" alt="timezoneand24hr" src="https://user-images.githubusercontent.com/1409547/84855847-ff2c8480-b019-11ea-8fa5-2e2274bc3e1d.png">

**Comment by gcobb321** [comment]
The times are correct and have a different purpose.  The time below the Restart iC3 is the date/time the Event Log screen was refreshed and displayed. The time on the left is the time iCloud3 updated the device info and added it to the Event Log. When you press Refresh, you will see the info change and the Refreshed time on the right will change. 

BTW-Questions like "I noticed a difference in the times, is correct or is this a problem" are fine and what the 'issues' category is intended for. Statements like "Do all you can to make time and date as clear and logical as possible" are not helpful. 

I have no problems with questions and pointing out potential bugs. At over 8000 lines of code, I'm sure you might come across a bug. With over 1300 users worldwide, most things have come up at one time or another. On of my goals is to have the program as rock solid as I can and to have the docs explain things clearly with enough detail so people can get up and running without any problems. You have just started using iCloud3, did not experience the result of Apple forcing 2fa on everyone and the time and effort on getting iCloud3 running again, first with the Find-my-Friends tracking method and now with the Family Sharing tracking method, which is in a prerelease state until I can finish the docs. I have been working with computers for over 50-years, and hopefully, figured out most things. Enough said..

I hope you find iCloud3 useful and that it meets your needs. Do let me know if you have any suggestions or problems. If you want, give me a star at the top of the GitHub page. I'll close this issue. If you have more questions about using the Event Log, open another issue.
