### ISSUE TITLE
Not your issue per se, however if you can collaborate with the HA team..... 43 sensors on the wall 🍺

### ISSUE THREAD

**Issue by deepcoder** [gcobb321/icloud3#48]
After my house cleaning, I am pretty sure the only two 'device tracker' integrations are the iOS Home Assistant app and your icloud3. With these, I end up with the 43 'sensors' updating in my HA. Wow, WTF, great and painful. So many questions about this data, but no idea who and where to look for documentation and help....
device_tracker.iphonexi
device_tracker.iphonexi_i01
sensor.icloud3_event_log
sensor.iphonexi_activity
sensor.iphonexi_average_active_pace	
sensor.iphonexi_badge
sensor.iphonexi_battery
sensor.iphonexi_battery_level
sensor.iphonexi_battery_state
sensor.iphonexi_battery_status
sensor.iphonexi_bssid
sensor.iphonexi_calc_distance
sensor.iphonexi_connection_type
sensor.iphonexi_dir_of_travel
sensor.iphonexi_distance
sensor.iphonexi_floors_ascended
sensor.iphonexi_floors_descended
sensor.iphonexi_geocoded_location
sensor.iphonexi_gps_accuracy
sensor.iphonexi_info
sensor.iphonexi_interval
sensor.iphonexi_last_located
sensor.iphonexi_last_update
sensor.iphonexi_last_update_trigger
sensor.iphonexi_last_zone
sensor.iphonexi_last_zone_name1
sensor.iphonexi_last_zone_name2
sensor.iphonexi_last_zone_name3
sensor.iphonexi_name
sensor.iphonexi_next_update
sensor.iphonexi_poll_count
sensor.iphonexi_sim_1
sensor.iphonexi_sim_2
sensor.iphonexi_ssid
sensor.iphonexi_steps
sensor.iphonexi_travel_distance
sensor.iphonexi_travel_time
sensor.iphonexi_trigger
sensor.iphonexi_waze_distance
sensor.iphonexi_zone
sensor.iphonexi_zone_distance
sensor.iphonexi_zone_name1
sensor.iphonexi_zone_name2
sensor.iphonexi_zone_name3
sensor.iphonexi_zone_timestamp
zone.iphonexi_stationary

**Comment by gcobb321** [comment]
These sensors are from the iOS app and iCloud3. 
iCloud3 sensors are listed in the iCloud3 did [here](https://gcobb321.github.io/icloud3/#/chapters/2-sensors)
iOS app sensor docs are [here](https://companion.home-assistant.io/docs/core/sensors)

With iCloud3, you can specify the sensors you want to include our exclude. This is described in the docs above. 
With the iOS app, you can rename and delete them in the HA entities and integrations screen.
