### ISSUE TITLE
Windows Support for Icloud3

### ISSUE THREAD

**Issue by rdstodda** [gcobb321/icloud3#48]
I am able to run Icloud3 in windows, but I need to manually adjust all the string formatting code. My understanding is that Windows does not support %- formatting option .

For example, I change the following:
dt_util.now().strftime('%A, %B %-d')) 

to

dt_util.now().strftime('%A, %B %d'))

**Comment by gcobb321** [comment]
All string formats were taken from the Python docs [here](http://strftime.org/). I’m not sure there is anything I can do about any problems you are running into.

**Comment by rdstodda** [comment]
Unfortunately, the %- directive appears to only be supported on Linux.  This [Link](https://docs.python.org/3/library/time.html) does not list the dash as a cross platform directive and lists a note "Additional directives may be supported on certain platforms, but only the ones listed here have a meaning standardized by ANSI C." 

My request is to just eliminate the dash directive and make your integration cross platform (which appears to be currently working on my windows platform (outside of the Icloud authentication issues).  My fear is that at some point, my simple "search and replace" is going to cause deeper issues and prevent usage.

**Comment by gcobb321** [comment]
I’ve made a note of your equestrian and will look at what needs to be done when I get a chance.

**Comment by rdstodda** [comment]
I was able to get the Icloud3 1.1.0b3 to run (it eliminates the invalid format string error) after changing the "%-" directive to just "%" on the following lines:
699
765
4277
4278
5336

**Comment by gcobb321** [comment]
Thanks. I have made the changes you found and it will be in beta 4 
tonight or tomorrow (along with a lot of other stuff).

------ Original Message ------

**Comment by rdstodda** [comment]
Confirming that this is fixed in 1.1.0b4 - Thank You!
