### ISSUE TITLE
Battery State

### ISSUE THREAD

**Issue by guyyar89** [gcobb321/icloud3#49]
hey,

always i get Battery State: Charging but my iphone not charging, i have iphone 6 
in past he used to show me when to charge when I was not charging.
How do you fix it?
thanks

**Comment by gcobb321** [comment]
iCloud3 doesn’t have anything to do with the battery state. All it does is pick it up from the iOS app or fmphn and pass it along. The find-my-friends tracking method does not pass any battery information along so iCloud3 can’t report it.
