### ISSUE TITLE
Wrong version bundled in zip for 1.0.6 release

### ISSUE THREAD

**Issue by pauly7300** [gcobb321/icloud3#50]
Gary, from the 1.0.6 release link, the zip file contains the 1.0.5 version of the device_tacker.py file.  The direct download of the file is the correct version however.

This is the link i'm referring to.  
https://github.com/gcobb321/icloud3/releases/tag/v1.0.6

**Comment by gcobb321** [comment]
Fixed. Thanks for the heads up.
