### ISSUE TITLE
iCloud3 and duplicate entity IDs

### ISSUE THREAD

**Issue by GriGri-ha** [gcobb321/icloud3#51]
Gary,

Thanks for developping this.  New to HA and your integrattion.  Got everything working except I cannot see in the UI the properties of the sensors.  It says "This entity does not have a unique ID, therefore its settings cannot be managed from the UI.".  Any idea?

Have 3 phones, all with different names, tracked through famshr. custom event log works fine.

**Comment by gcobb321** [comment]
@GriGri-ha The sensors are created when iCloud3 starts so they do not really exist in the entities registry and their information can not be changed. However, they do exist in HA as temporary items so they can be used in automations and scripts and are included in the entities list as Read Only entities and have the Read Only symbol on the right side of their line.
