### ISSUE TITLE
Error when phone name has a space in it

### ISSUE THREAD

**Issue by sylviepipi** [gcobb321/icloud3#52]
I get a lot of errors in my log file

2019-07-05 20:56:53 ERROR (SyncWorker_17) [custom_components.icloud3.device_tracker] ►►INTERNAL ERROR (UpdtSensorUpdate-Invalid entity id encountered: sensor.iphone xxxs_zone. Format should be <domain>.<object_id>)

I do have a space in my phone name, it looks like the same does not get replaced by an _

when looking at the battery attribute it is empty. (battery_status: )

same issue with attributes _zone,_interval,_info

**Comment by gcobb321** [comment]
It’s probably the space that’s the problem. When the sensor_name _prefix or sensor_badge(?j is being set up, all spaces are stripped out. I would suggest using an underscore instead of a space in the phone name to insure it will be available everywhere.
