### ISSUE TITLE
Icloud3 cannot be used normally at all. Can it be updated as soon as possible?

### ISSUE THREAD

**Issue by a120578270** [gcobb321/icloud3#52]
Try before many versions are the same, either can not get data or data update after several times do not update! And the first time HA gets data after restart is very slow or the data can not be obtained directly! Request boss to update as soon as possible...

**Comment by gcobb321** [comment]
iCloud3 runs as an HA custom component. The last version of HA changed the way custom components start up and it now takes longer. When iCloud3 starts, there is a lot to do. The longest step is setting up access to the iCloud account, getting your location, getting your zone data and, if you are not home, getting route distance and travel time to home. The length of time to do this depends on the speed of your computer running HA, your internet connection speed, how long it takes iCloud to respond to authentication requests, the number of phones you want to track, the speed of the phone,  how long it takes iCloud to locate each phone, if you have good cell phone service or are in a poor cell connection area, the device you are using to display the tracking results, and it's connection speed, etc. iCloud3 has no control over any of this and displayed the data as soon as it has it. 

Your last issue had lots of errors trying to connect with iCloud Web Servers. I think that is the problem you are having, or the main one, and there is nothing I can do about that. I can only handle problems working with the data that is returned by iCloud Web Servers. 

The Event Log shows what is going on when HA starts, error message, transactions that are discarded and why, poor GPS, old location data, etc. And is a valuable to in seeing what is going on. You can get detailed information about the tracking in the HA log file by turning on the Debug on the Event Log or putting 'log_level: debug' in your HA config file iCloud3 parameters. The iCloud3 configuration chapter in the document gives more info about this. 

Screen shots of the Event Log, phone attributes, tracking display, etc would be helpful in seeing what is going on. Like your last issue with errors generated trying to connect with the iCloud Web/Location servers.  Also, I'm not sure what you mean by "request boss to update as soon as possible". What is "boss"?

**Comment by a120578270** [comment]
![image](https://user-images.githubusercontent.com/58241282/86897947-ad6bab80-c13a-11ea-83fd-e7520acb2b4d.png)
Now restart HA is basically showing that you can't get the data, or the data will not be updated after a period of time, do you have such a situation? The network environment is normal from my point of view, so I don't know why, I just use ha's official icloud plug-in!

**Comment by a120578270** [comment]
![image](https://user-images.githubusercontent.com/58241282/86898370-31be2e80-c13b-11ea-838c-22504b35f109.png)

**Comment by gcobb321** [comment]
Then HA starts, mine also looks like this until the devices are located the first time. Sometimes it takes 10-15 seconds to display the first screen. The latest version of HA slowed things down during startup. What does the Event Log show? Any errors? Look at Develper Tools>Logs and see if there are any coding errors in iCloud3 preventing it from starting.

**Comment by a120578270** [comment]
Sometimes all the data could not be loaded, and sometimes the data could not be loaded from a few mobile phones. There was no error of icloud3 in the log. After I called ICloud3 and restarted the service for many times, maybe all the phones would have data, but after a period of time, the data would not be updated. Now I don't know the reason, so I want to ask you, do you have such a situation? 2.2 Rc8 is very likely to be stuck in the stationary state when the device is not refreshing!

**Comment by gcobb321** [comment]
I found a problem with devices not getting out of a stationary zone last week. It has to do with several devices in the same zone, one leaves and comes back. The iOS app issued Region Enter trigger for another devices stationary zone and it would stay there. 

I also found a problem when there was more than one device tracker entity for a device caused by installing the iOS app several times. This created multiple mobile app integrations with different entity names. iCloud3 stopped scanning the entity registry on the first one and monitored that. The iOS app was had stopped updating that entity and was updating a new one. I fixed that on Monday and am cleaning up all the debugging code I had added to solve that issue. Now, you get an effort message if there is more than one entity for the device tracker and then monitor the last one added instead of the first. 

I should be putting up rc9 tomorrow or the next day.

**Comment by a120578270** [comment]
When the device is in the not set state, will it not always be acquired? I waited for more than ten minutes, but there are still several devices in the not set state. If the next update is less than the current time, icloud3 will not be getting data and will be stuck. Is there a mechanism to force it to refresh?

After using ha0.111, I found that after using icloud3, ha restart often fails. After clicking restart, the HA interface prompts to disconnect, but it will never start. You have time to test whether this problem exists

**Comment by gcobb321** [comment]
iCloud3 does an authentication of the main iCloud account and then updates the location of each device. It returns the location info for all devices at the same time, not one at a time. In famshr tracking, it locates all devices in the Family Sharing list on the account, even the ones you are not tracking. If you have an iPad or iwatch on the account, it has to locate them too. In fmf tracking, iCloud only locates the devices you are following.

I can't tell what you are using.. It does look like you are running rc4 when the one on GitHub repository is rc8 with rc9 almost available. Update to rc9 when it's out tomorrow or the next day. Maybe only track 1 phone and see what happens, than add another, then another. See if one phone in creating problems.

**Comment by a120578270** [comment]
I have used RC8 in all versions of 2.2, but now the main problem is that I get the data in all versions, and it is very likely that the data will not be set or the data will not be updated after a period of time. I've been looking for problems and I haven't reported any errors in my log. According to what you said, you should not have my situation, so I have to rule out what the problem is.
