### ISSUE TITLE
After restarting HA, RC9 version is prone to location error, which is judged to be at home

### ISSUE THREAD

**Issue by a120578270** [gcobb321/icloud3#56]
I didn't see an error in the log. I don't know what caused it!

**Comment by gcobb321** [comment]
When HA  starts and iCloud3 loads, the last thing it does is to locate the devices by calling iCloud Location Services. iCloud3 just reports the data it gets back from iCloud, it doesn’t locate the device itself. 

Have you installed and set up the Event Log Lovelace card? If you haven’t, you should. It tells you what is going on between the iOS app, iCloud locate, the status of the data received (old location, poor gps) and will answer most of the issues you bring up. Go [here](https://gcobb321.github.io/icloud3_docs/#/chapters/1-installing-event-log-card) for more info. I have asked you several times what the Event Log shows In different issues you have posted and you have never answered that question so I’m not sure you have.
