### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kzelnick** [gcobb321/icloud3#57]
Very newbie to ha and github so forgive me
Downloaded the files and place in the proper file 
On restart i get a username password error
Any help would be great

**Comment by gcobb321** [comment]
I would suggest going through the Reade file [here](https://github.com/gcobb321/icloud3/blob/eb019f16d12c5fdae1ca82287d873a8d543f7518/beta/Readme%20v1.1.0.md). It contains extensive documentation, with examples, on how to set up iCloud3 and use it.

**Comment by kzelnick** [comment]
I am sorry and appreciate the reply I read through the documentation and idownloaded 4 of the five files but the release shows a fifth file 
pyicloud_ic3.py that i cannot find where to download
log below 

iCloud location service has been disabled
6:08 PM custom_components/icloud3/device_tracker.py (ERROR)
Error returned from pyicloud: ('Invalid email/password combination.', PyiCloudAPIResponseError('Failed to validate the credentials from cookie'))
6:08 PM custom_components/icloud3/device_tracker.py (ERROR)
Error authenticating iCloud Service for kennyzelnick@gmail.com/kenny_icloud
6:08 PM custom_components/icloud3/device_tracker.py (ERROR)
Failed to validate the credentials from cookie
6:08 PM custom_components/icloud3/device_tracker.py (ERROR)
You are using a custom integration for icloud3 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
6:08 PM loader.py (WARNING)

**Comment by gcobb321** [comment]
Redownload all of the files from the beta section [here](https://github.com/gcobb321/icloud3/tree/master/beta). It contains all of the v1.1.0 files needed to use the latest version of iCloud3. The docs in the beta directory have been updated for v1.1.0. It would have been released but I am out of town until mid-August. See the “About Your Apple iCloud Account“ for information on getting started.

**Comment by kzelnick** [comment]
Thanks got the phones to show up but still cant authenticate icloud 
Enjoy ur time off will check back
