### ISSUE TITLE
Pre releases available through HACS please :)

### ISSUE THREAD

**Issue by xvolte** [gcobb321/icloud3#57]
@gcobb321 Have you considered making these pre-releases easier to install by marking them as "pre-releases" for HACS so we can install via HACS vs manually?

_Originally posted by @tmchow in https://github.com/gcobb321/icloud3/issues/39#issuecomment-640278989_

**Comment by xvolte** [comment]
That would be awesome (i'm using 2.1 version from HACS now) and can't install RC9 of 2.2

**Comment by gcobb321** [comment]
I’m waiting on the final iOS app update which I think will be within the next 2 weeks and then will be releasing it to HACS. Meantime, I have uploaded a zip file with all the updates. Download the zip file, unzip it to your iCloud3 directory and restart HA. More info and instructions are in the v2.2.0 Release Candidate directory. There are also links to the docs, which are almost done. 

Creating a HACS update is not trival and that is why I haven’t done it. Plus, I keep adding another feature and doing a GitHub update is real easy. Now on rc10 which added updates to the Event Log and addressed an update to the iOS app regarding small zones. I’m adding some final touches to the Event Log now and I have one rare issue with iCloud3 to address.

**Comment by broyuken** [comment]
The new iOS update is out, should we be expecting the 2.2 update shortly now? Really looking forward to it.

**Comment by gcobb321** [comment]
I'm getting ready to post rc11 which adds support for fmf for 2fa accounts, some enhancements to the event log and verifying that the ios app Device name is the same as the mobile app integration device name. I've been working on the docs but lost some changes yesterday that I still have to redo. And I'm in the middle of a bedroom/bathroom remodel and need to install base boards.

I've been running the updated app for a while and there are no problems I know of.

Stay tuned. and look for rc11 today or tomorrow. Docs should be done next week.

**Comment by broyuken** [comment]
Did RC11 get posted somewhere and I missed it? I might bite the bullet and use the custom component if there won’t be a version in hacs soon.

**Comment by gcobb321** [comment]
Later today. It’s ready but need do final look at the logs from last night.  I’m remodeling a bathroom and need to finish prepping for the guys installing the vanity top.

**Comment by broyuken** [comment]
Ok no worries, just wanted to make sure I didn’t miss something.

**Comment by gcobb321** [comment]
Just Updated to rc11. Go [here](https://community.home-assistant.io/t/icloud3-v2-1-device-tracker-advanced-tracking-features-ios-app-monitoring/148943/552) for more info

**Comment by gcobb321** [comment]
iCloud3 v2.2 has been released on HACS.
