### ISSUE TITLE
2.2 RC10 : Multiple icloud3 device_tracker Failing

### ISSUE THREAD

**Issue by xvolte** [gcobb321/icloud3#58]
Hello,

When configuring icloud3 with 2 accounts (like explained here : https://gcobb321.github.io/icloud3/#/chapters/1-setting-up-icloud3?id=tracking-devices-using-two-icloud3-platforms)

**I get only one being actually taken into account :**
device_tracker:
  - platform: icloud3
    username: !secret yyyy_icloud_id
    password: !secret yyyy_icloud_secret
    track_devices:
      - yyyyy_iphone > yyyyyy@yyyyy.yyy, yyyy.png
      
device_tracker:
  - platform: icloud3
    username: !secret xxxx_icloud_id
    password: !secret xxxx_icloud_secret
    track_devices:
      - xxxx_iphone > xxxxxx@xxx.xxx, xxxx.png

Same in the event Log, i can only see XXXX account (not yyyyy)

Thanks in advance,

**Comment by gcobb321** [comment]
I knew the Event Log did not support 2 accounts. It will take some work to get it to and I’ll look at it when I get a chance. However, I am surprised thatYou are having problems with the tracking part of iCloud3 itself. I’ll check that out and see if I have a any problems.

**Comment by xvolte** [comment]
i also noticed i got some wrong info coming from icloud3 this weekend, whereas the ios app located me correctly.
Does icloud3 need the "home assistant" to be accessible from internet to work correctly ?
I was connected through my VPN, but the position it kept saying i was away, even when i was on the road, the location didn't upate correctly whereas ios app worked fine.

i can help debugging if you tell me how 👍 

Thanks in advance!

**Comment by gcobb321** [comment]
iC3 needs the iOS App to be able to access HA all the time so location triggers and state changes are updated within HA. iC3 monitors these items to update the zone enter/exit, significant location updates, background refreshes, etc. location information.

Be sure to check the Event Log iC3 startup info to make sure the device_tracker entities for the ios App are being monitored. They are set up in Stage 3 of starting iC3. Also be sure the device name within the iOS App on the device matches the entity names.

Be glad to have you check out new features.

**Comment by xvolte** [comment]
Can you explain the following : be sure the device name within the iOS App on the device matches the entity names
i don't understand what this means.

for your info, here are my IC3 2.2.0 RC10 logs:

iphone_xxxxxxxxxxxxxx	11:32:20p	home	Home	2 hrs		0 mi	$$Service Call Command Received > `log_level: debug`
iphone_xxxxxxxxxxxxxx	11:32:00p	home	Home	2 hrs		0 mi	$$Device Info > UpdateMethod-None, UpdateReason-IgnoredTrigger-Sig Loc Change@11:31:51, State-maison, Trigger-Sig Loc Change@11:31:51, LastLoc-11:31:55, Zone-maison, ZoneDist-9999999999m, inZone-True, GPS-(aaa.bbbbbbb, cc.dddddddd)/65m), StateThisPoll-maison, StateLastPoll-maison
iphone_xxxxxxxxxxxxxx	11:31:55p	home	Home	2 hrs		0 mi	IOS App update complete
iphone_xxxxxxxxxxxxxx	11:31:55p	home	Home	2 hrs		0 mi	Results: Maison > CurrZone-Maison, GPS-(aaa.bbbbbbb, cc.dddddddd)/65m), Interval-2 hrs, Dist-0 mi, TravTime- (in_zone), NextUpdt-1:32:00, Located-11:31:51 (4 sec ago), OldLocThreshold-3 min
iphone_xxxxxxxxxxxxxx	11:31:55p	home	Home	2 hrs		0 mi	$$Distance Data > DirOfTrav-in_zone, LastDirOfTrav-in_zone, DistFmZone-0km, LastDistFmZone0km, DistFmZoneMoved-0km, DistFmLastPollMoved-0km 
iphone_xxxxxxxxxxxxxx	11:31:55p	home	Home	2 hrs		0 mi	Select Zone > Maison-0m/r100, Stationary-1.0km/r1 > Selected-Maison
iphone_xxxxxxxxxxxxxx	11:31:55p	home	Home	2 hrs		0 mi	iOS App update started (State Change)
iphone_xxxxxxxxxxxxxx	11:31:55p	home	Home	2 hrs		0 mi	$$Device Info > UpdateMethod-IOSAPP, UpdateReason-State Change, State-maison, Trigger-Sig Loc Change@11:31:06, LastLoc-11:31:51, Zone-maison, ZoneDist-9999999999m, inZone-True, GPS-(aaa.bbbbbbb, cc.dddddddd)/65m), StateThisPoll-maison, StateLastPoll-home
iphone_xxxxxxxxxxxxxx	11:31:55p	home	Home	2 hrs		0 mi	iOSApp State Change detected > home to maison
iphone_xxxxxxxxxxxxxx	11:31:55p	home	Home	2 hrs		0 mi	$$iOSApp Monitor > Trigger-Sig Loc Change@11:31:02, State-home@11:31:06, GPS-(aaa.bbbbbbb, cc.dddddddd)/65m), 
iphone_xxxxxxxxxxxxxx	11:31:52p	home	Home	2 hrs		0 mi	IOS App update complete
iphone_xxxxxxxxxxxxxx	11:31:50p	home	Home	2 hrs		0 mi	Results: Maison > CurrZone-Maison, GPS-(aaa.bbbbbbb, cc.dddddddd)/65m), Interval-2 hrs, Dist-0 mi, TravTime- (in_zone), NextUpdt-1:31:45, Located-11:31:06 (49 sec ago), OldLocThreshold-3 min
iphone_xxxxxxxxxxxxxx	11:31:50p	home	Home	0 sec			$$Distance Data > DirOfTrav-in_zone, LastDirOfTrav-not_set, DistFmZone-0km, LastDistFmZone0km, DistFmZoneMoved-0km, DistFmLastPollMoved-0km 
iphone_xxxxxxxxxxxxxx	11:31:50p	home	not_set	0 sec			Select Zone > Maison-0m/r100, Stationary-1.0km/r1 > Selected-Maison
iphone_xxxxxxxxxxxxxx	11:31:50p	home	not_set	0 sec			iOS App update started (Sig Loc Change)
iphone_xxxxxxxxxxxxxx   11:31:50p	home	not_set	0 sec			$$Device Info > UpdateMethod-IOSAPP, UpdateReason-Sig Loc Change, State-home, Trigger-Sig Loc Change, LastLoc-11:31:02, Zone-home, ZoneDist-5.22m, inZone-True, GPS-(aaa.bbbbbbb, cc.dddddddd)/65m), StateThisPoll-home, StateLastPoll-not_set
iphone_xxxxxxxxxxxxxx	11:31:50p	home	not_set	0 sec			$$iOSApp Monitor > Trigger-Sig Loc Change@11:31:02, State-home@11:31:06, GPS-(aaa.bbbbbbb, cc.dddddddd), Trigger Change-Sig Loc Change
_**	11:31:06p						^^^ Initializing iCloud3 v2.2.0rc10 > Complete, Took 4.44 sec**_
*	11:31:06p						Initialize Sensors > iphone_xxxxxxxxxxxxxx
*	11:31:06p						Sensor entity prefix > sensor.xxxxxxxxxxxxxx
*	11:31:05p						Setup Stationary Zone > iphone_xxxxxxxxxxxxxx_stationary, Using Base Location-(aaa.bbbbbbb, cc.dddddddd), DistFromHome-1.0km
*	11:31:05p						Initialize Data Fields > iphone_xxxxxxxxxxxxxx
_**	11:31:05p						Stage 4 > Configure tracked devices**_
*	11:31:05p						Tracking Devices >  iphone_xxxxxxxxxxxxxx ( ... _iosapp)
*	11:31:04p						iOS App monitoring >xxxxxxxxxxxxxx (iphone_xxxxxxxxxxxxxx) > device_tracker.iphone_xxxxxxxxxxxxxx_iosapp, sensor.iphone_xxxxxxxxxxxxxx_last_update_trigger
*	11:31:04p						Verified Device > xxxxxxxxxxxxxx (iphone_xxxxxxxxxxxxxx)
_**	11:31:04p						Stage 3 > Verify tracked devices**_
*	11:31:04p						Results > FriendlyName-xxxxxxxxxxxxxx, Email-xxxxxxxxxxxxxx@gmail.com, Picture-/local/iosxxxxxxxxxxxxxx.png, DeviceType-iphone, TrackFromZone-[`home`]
*	11:31:04p						Decoding > iphone_xxxxxxxxxxxxxx > xxxxxxxxxxxxxx@gmail.com, iosxxxxxxxxxxxxxx.png
*	11:31:04p						Entity Registry mobile_app device_tracker entities found >, 
                    • iphone_yy_iosapp (iPhone YY),
                    • iphone_xxxxxxxxxxxxxx_iosapp (iPhone xxxxxxxxxxxxxx)
*	11:31:04p						iCloud Account Authentication Successful > xxxxxxxxxxxxxx@gmail.com
*	11:31:02p						iCloud Web Services interface (pyicloud_ic3.py) > Verified
*	11:31:02p						Preparing Tracking Method > Find My Friends
_**	11:31:02p						Stage 2 > Set up tracking method & identify devices**_
*	11:31:02p						Set Up Waze > Region-US, MinDist-1 mi (1.61km), **MaxDist-1000 mi (1609.35km),** Realtime-False
*	11:31:02p						Set Initial Stationary Zone Location > GPS-(aaa.bbbbbbb, cc.dddddddd), Radius-100m, DistFromHome-1.0km
*	11:31:02p						Set up Zones > home/Maison (r100m)
*	11:31:01p						Event Log Version Check > Current release is being used. Version-2.2.0.04 (7/20/2020), /config/www/custom_cards
_**	11:31:01p						Stage 1 > Prepare iCloud3 for xxxxxxxxxxxxxx@gmail.com**_
*	11:31:01p						^^^ Initializing iCloud3 v2.2.0rc10 > Tuesday, Aug 04

**Comment by gcobb321** [comment]
1. Everything looks fine with your log file. The 
```iphone_xxxxxxxxxxxxxx 11:31:50p home not_set 0 sec $$Device Info > UpdateMethod-IOSAPP, UpdateReason-Sig Loc Change, State-home, Trigger-Sig Loc Change, LastLoc-11:31:02, Zone-home, ZoneDist-5.22m, inZone-True, GPS-(aaa.bbbbbbb, cc.dddddddd)/65m), StateThisPoll-home, StateLastPoll-not_set```
shows the ios app is communicating with HA and being monitored.

2. Your question. Your log file shows:
```
11:31:05p Tracking Devices > iphone_xxxxxxxxxxxxxx ( ... _iosapp)
11:31:04p iOS App monitoring >xxxxxxxxxxxxxx (iphone_xxxxxxxxxxxxxx) > device_tracker.iphone_xxxxxxxxxxxxxx_iosapp, sensor.iphone_xxxxxxxxxxxxxx_last_update_trigger
```
The device_tracker.iphone_xxxxxxxxxxxxxx_iosapp entity is being monitored for state changes, etc. There are times when iC3 will issue a 'request_location_update' message to the phone device_tracker.iphone_xxxxxxxxxxxxxx_iosapp. The phones device name can be set on the App Configuration>General>Device Name field (on the phone itself). If they are different, you will get an notify error message that the device_tracker.iphone_xxxxxxxxxxxxxx_iosapp can not be found.

**Comment by xvolte** [comment]
Since i got no notification i assume it was correct. i did however since your response, manually changed it to put the same name (xxxxxxxxxxx_iosapp), where it was set to "iphone of xxxxxx"
i don't know why i had positions differences between icloud3 and iosapp. My guess was that the homeassistant "server" needs to be accessible from the internet? 
I will see if it is better in the next road trips 👍 

Regarding the mutliple icloud3 devices with two account and two settings, can you help ? it only take the last one in the config file.


`
device_tracker:
  - platform: icloud3
    username: !secret xxxxxxxxxx_id
    password: !secret xxxxxxxxxx_secret
    track_devices:
      - iphone_xxxxxxxx > xxxxxxxxx@gmail.com, iosxxxxx.png

device_tracker:
  - platform: icloud3
    username: !secret yyyyyyyy_id
    password: !secret yyyyyyyy_secret
    track_devices:
      - iphone_yyyyyyy > yyyyyyyyy@gmail.com, iosyyyyyy.png
`

Hass only loads the last one (yyyyyy)

Thanks in advance,

**Comment by gcobb321** [comment]
I’ll look into it. You can use the find-my-friends to track devices that are not part of the same family sharing list on one iCloud account. Lots of info about using that Tracking method in the ic3 docs. 

Ic3 adds iOS app debug info to the evlog but doesn’t display them. Go to the Actions drop down on the event log and select showevent log tracking recds

**Comment by xvolte** [comment]
Hi @gcobb321, thanks for the follow up

what i end up doing is using the family share, so that i use it like this :

```
device_tracker:
  platform: icloud3
  username: !secret xxxxxxxxxx_id
  password: !secret xxxxxxxxxx_secret
  track_devices:
    - iphone_xxxxxxxx > xxxxxxxxx@gmail.com, iosxxxxx.png
    - iphone_yyyyyyy > yyyyyyyyy@gmail.com, iosyyyyyy.png
```

So i confirm now i can see both iphones (including in the card)

However, my wife is at work this morning, and the tracker still says she is at home. Any thoughts ?

i noticed  that the interval is set to "2 hours" might this be the problem? i thought as long as there is movement and you are not "stationary" it should update automagically ?

I got no location update since this morning 8:16 am, and it is now 9:55am

thanks in advance,

**Comment by gcobb321** [comment]
Review the event log to make sure she is set up and verified when iCloud3 starts. Also check for location updates. Check the fmf section in the iCloud3 docs [here](https://gcobb321.github.io/icloud3_docs/#/chapters/1-setting-up-icloud-account?id=troubleshooting-startup-errors)

**Comment by xvolte** [comment]
She is set up correctly, but there is still no location update as of now 11:30am (still being located in house).
I can see in IOS, (not related to Home Assistant nor icloud3), that she is located correctly at work, whereas icloud3 still says she is at home.

I wonder if icloud3 take my position instead of hers

**Comment by xvolte** [comment]
i found this in the Error Log of Home Assistant when i reboot it, but not in the icloud3 scorecard ?

```
Détails du journal ( ERROR )
Logger: custom_components.icloud3.device_tracker
Source: custom_components/icloud3/pyicloud_ic3.py:140
Integration: icloud3 (documentation)
First occurred: 23:16:31 (1 occurrences)
Last logged: 23:16:31

Two-Step Authentication (2SA) Required for Account xxxxxxxxxxx@gmail.com

raceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 6042, in _setup_tracked_devices_for_fmf
    self.log_level_debug_rawdata("iCloud FmF Raw Data - (device_obj.data)", device_obj.data)
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 689, in data
    self.refresh_client()
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 660, in refresh_client
    req = self.session.post(self._friend_endpoint, data=mock_payload, params=params)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 125, in request
    self._raise_error(code, reason)
  File "/config/custom_components/icloud3/pyicloud_ic3.py", line 140, in _raise_error
    raise PyiCloud2SARequiredException(self.service.user["apple_id"])
custom_components.icloud3.pyicloud_ic3.PyiCloud2SARequiredException: Two-Step Authentication (2SA) Required for Account xxxxxxxxxxxxxx@gmail.com
```



i get the 2FA code on my mobile (not by SMS - by apple push) but then i got no option whatsoever to input a code in HA or icloud3

What is strange is that i get no error message either in the icloud3 scorecard ; it does see all accounts and set them correctly.

**Comment by gcobb321** [comment]
Fmf was originally set up to not use a 2fa account to get around the constant notifications that someone had logged into your 2fa account. I’ll bet you are using a 2fa account for fmf to track your devices to get around the single instance requirement of ic3. I don’t think I went back and checked to see how a 2fa account would work with fmf. Ill check it out and see what is going on tomorrow and let you know what I find. 

Btw, where are you located? Just curious.

**Comment by xvolte** [comment]
Haaaa nice !
Yes i use a 2FA account - yes i got constant notification each time icloud3 is restarted.
Please tell me how to track two phones - if there is a better way - as i want to automatically disable home alarm/camera based on location of any of the two devices.

previously, i set two icloud3 instance, but only one would be picked up, so i figured i would try the Family sharing option / FMF

i'm in France near Lyon - i've read in your website that quentame should be in the same town :) 👍

**Comment by gcobb321** [comment]
The easiest way is to add the other devices to your Apple/iCloud Family Sharing list and use the FamShr tracking method. Specify both devices in the track_devices parameter. There are examples in the iCloud3 docs and that is what I use. On your iPhone, go to SettingsApp>AppleID, Icloud>FamilyList to add or view people on the list. Then go to FindMy, make sure ShareMyLocation is on for all the devices you are tracking and you can see them on the FindMy App map

I get a notification every once in a while about a device is logged into my account. The iCloud cookie file is used to authenticate the account. I renamed mine, restarted HA and it took about 8 hours before I got an HA notification that my account needed to be authenticated via a text message. The cookie file is in the ‘.storage/iCloud’ directory. The file is your iCloud account without punctuation.

**Comment by xvolte** [comment]
i'll try that today.

Maybe the documentaiton needs an update:
https://gcobb321.github.io/icloud3/#/chapters/1-setting-up-icloud3

it should:

1. correct the tracking_ method to tracking_method (space typo i think)
2. States that the Tracking devices using two icloud3 platforms is NOT supported
3. states that FMF does not work with 2FA/2SA

to make it more clear :) 👍 

thanks again for your hard work!

**Comment by xvolte** [comment]
So, i can confirm i was able to input the 2FA sms code in HA : worked like a charm.

Now, i do have setup the tracking_method to famshr - i will see if things are OK now - will keep you posted :D

**Comment by gcobb321** [comment]
I just loaded iCloud3 v2.2.0 Release Candidate 11 to support Find-my-Friends tracking method on 2fa accounts, plus some other things.

Go here for more information about it and how to download and install it.

**Comment by gcobb321** [comment]
Did you download rc11?

**Comment by xvolte** [comment]
I will soon - i was away for a couple of days. 
I have been using famsh instead as you recommended but i will try rc11. 

I got some really strange things coming up for both my wife and i. 
See picture. 

Looks like there are some « pings » that goes to « stationary » locations 1km north (as explained in your doc) - but i don’t undertand why i got some incorrect location.

**Comment by xvolte** [comment]
![1EA08159-3166-44B3-A74F-4117D4A003AF](https://user-images.githubusercontent.com/21142611/90959639-7a883780-e49c-11ea-929f-62ae268ce1d7.jpeg)


As i explained - i was away so the points on the right are the correct ones- and the points going back and forth to my « stationary » (1km north of my home) are incorrect. You can see that when i was driving back i got all these issues. 
Any idea why?

Also - i have been reading the doc multiple times but i still don’t understand what the « stationary » does.

Is there a way to delete them - as i would likz to be sure they are re-created correctly

**Comment by xvolte** [comment]
i also notice that my states are correct, but the ones from my wife are wrong.
it says she is not at home and cycling ? whereas we are both at home.

Green are OK values
Red are wrong values
Blue: is worth mentioning...

Is there a way to remove all the device_tracker and reinstall properly ? i wonder if I or icloud3 didn't make a mess by testing first 2 icloud3 accounts, then using FMF, then using FAMSHR ....

![strange](https://user-images.githubusercontent.com/21142611/90960535-837c0780-e4a2-11ea-9ebf-a40d1f7fdd5f.png)

**Comment by gcobb321** [comment]
I would review the Event Log to see what is going on. You probably are experiencing gps wandering where the wrong location is reported by iCloud Location Services or the iOS app. ICloud3 does not actually locate the device, it uses the data provided by these 2 services. The Event Log will also show if you are getting a lot of gps accuracy issues or the location data is old. 

Switching between fmf and FamShr and 2 devices are not a problem, I do it all the time while testing but usually use fmf. 

I did fix a problem with rc11 (now 11c) to fix a problem that would not move  a phone into the stationary zone if the stationary zone timer expired and you the location was old or you had gps accuracy issues. You might download the 11c zip file and see if that fixes your issues.

**Comment by xvolte** [comment]
I think i messed up something when renaming iphones in the ios_app. 

I think i will remove all entries of iosapp and icloud3 and reinstall clean. 
Is there any thing to manually remove in icloud3?
Then  i will install 11c 

Thanks a lot for your support!!

**Comment by xvolte** [comment]
Are you sure icloud3 is getting the correct location from apple icloud?
I noticed in the « find-my » that the location showed in icloud3 is the one from my wife earpods and not the one of her iphone - could you double check? How can i help with debug?
I installed rc11c i will send screen in a while

**Comment by gcobb321** [comment]
There is no need to uninstall iCloud3. To install a release candidate, download the zip file and unzip it into the config/custom_components/icloud3 directory. It will overwrite the necessary files and install the Event Log into the www/custom_cards directory. 

All renaming phones in the iOS app does after the initial install of it’s mobile_app is change the entity iCloud3 will send location requests to. After the initial install, The other device tracker and entity names are changed by HASidebar >  Configuration > Integration, Entities and Devices. 

The latest is rc11c.zip

The Event Log gives a lot more details about the mobile_apps it finds, which ones it is monitoring and which ones it will send location requests to when needed..

**Comment by xvolte** [comment]
Hi there, looks like the rc11c seems fine for now - using FMF.
i'll check a little more in the coming days

**Comment by gcobb321** [comment]
I just update to RC11d. One of the issues fixed was trigger updates being discarded when the state change time was the same as the last_update_trigger change time. That check was originally in there to prevent state change and trigger changes from firing duplicate updates but I took care of that another way.

**Comment by xvolte** [comment]
Will update tonight 👍 
🥇 you are a star, thanks for all the support!

**Comment by xvolte** [comment]
So far, with fmf and rc11d, all looks perfect!
No back and forth to stationary. 
Location reported correctly too. 
I ll keep you posted in the coming days 👍

**Comment by xvolte** [comment]
I confirm all is working fine now. 
Looks like you got a fine Release Candidate for HACS :) 
Well done and thanks a lot for all your efforts, communication, etc

**Comment by xvolte** [comment]
Unfortunately, the problem going back and forth to the home stationary position (1km north of my home) reappeared ...
I really don't understand why?
problems was for my wife and i today ...
i'll send captures and logs in a bit, the time to remove sensitive info

![Stationary problems](https://user-images.githubusercontent.com/21142611/91645131-e2adbf00-ea42-11ea-852e-a3275bd9fb72.png)

the point shown in the picture is the "Stationary" point 1km north of my home. i don't understand why i'm getting some location there.

here are the log around the period :
![strange things](https://user-images.githubusercontent.com/21142611/91645319-77fd8300-ea44-11ea-80b0-bab5af9d2d12.png)

**Comment by gcobb321** [comment]
The "iOS App used another device's Stationary Zone,..." is a normal message to keep a phone assigned to it's own Stationary Zone.

When 2 phones are in the same location for any length of time (stationary_still_time), each has it's own stationary zone with the same coordinates. That location is also in the ios app. When it issues a Zone Enter trigger, it sets it's state to the the first zone name in it's zone table. What you are seeing above is the ios app moving your device into your wife's stationary zone, which is at the same location. That is OK. iC3 knows this and changes the the stationary zone of your phone to your stationary zone.

This could be confusing to you since both of your phones start with the same name (iphone_de_xxxxx). I look at changing the message to use the friendly name of both phones in the message, which might clear thing up. 

Since you blacked out the complete gps coordinates, I can not see the accuracy to see if it was a poor location. Maybe next time, just black out the main part before the '.'. Normally, it will not move the device into a stationary zone at the base location 1km north of Home since it has a 1m raduis. The latest version of the ios app looks at the zone radius and if it is less than 100m, it will (may) still move a device into that zone area which might fire the trigger. I'll see if making it passive has any effect. Yu might also move the stationary zone base location further away using `stationary_zone_offset: 5,0` to move it 5km north of Home (the second parameter moves it east/west). See the docs [here](https://gcobb321.github.io/icloud3_docs/#/chapters/2-config-parms?id=stationary_zone_offset) for more info about this parameter.
As you can see from the iOSApp Monitor, iCloud3 is reacting to zone changes generate by the ios app. 

Edit: I am changing iCloud3 in v2.2.0 rc11g to revert back to using the full devicename for the zone's friendly name (iphone_de_xavier_stationary) rather than an abbreviation (iph:stationary) to avoid confusion and prevent identification problems. This had been done to prevent the Event Log from formatiing errors when the iOS App State and iC3 Zone were onger than 10 characters. Instead, the Event Log will only display the first 10-characters of these fields.

**Comment by xvolte** [comment]
Hi,

jsut installed version J.

will keep you posted.
