### ISSUE TITLE
No altitude data, always zero in version 2.2.0rc6 from iOS device

### ISSUE THREAD

**Issue by deepcoder** [gcobb321/icloud3#59]
I never get any altitude data, always zero. Is this attribute available on iOS?

I am no longer able to find you dev branch in github. So I have been stuck on this version.

**Comment by gcobb321** [comment]
Go [here](https://github.com/gcobb321/icloud3/tree/master/v2.2.0-Release%20Candidate) For the latest release candidate. I changed the directory name to better describe the update. 

Re altitude. iCloud3 just passes along data from iCloud and the iOS app. Check the iOS app docs out go to HASide bar>developer tools > states to reviews the entities the iOS app provides.

**Comment by deepcoder** [comment]
Thx for reply and your work on this project! I have downloaded and installed rc10 under 0.113.3, refreshed app cache on iOS device. It appear that I am now getting altitude data in your sensor now, I will check to see if I get any different results over the next days.
