### ISSUE TITLE
Typo in device_tracker.py

### ISSUE THREAD

**Issue by MikeTannenbaum** [gcobb321/icloud3#62]
<img width="883" alt="Screen Shot 2020-08-17 at 8 13 13 PM" src="https://user-images.githubusercontent.com/792648/90456372-dc285a80-e0c6-11ea-8656-1ad5ddd35505.png">

 See line 1420 with variable "devicenme" — I changed it in the file and the error went away.

**Comment by gcobb321** [comment]
Fixed in RC11a just uploaded.
