### ISSUE TITLE
How to include all device types ?

### ISSUE THREAD

**Issue by andriuskr** [gcobb321/icloud3#62]
Hello,

I want to include all device types on my icloud, but if i do not specify any device types, only device names - i get error that i need to include device types to track. How to include all device types ?

**Comment by gcobb321** [comment]
Device types are going away with version 1.1 now in beta (see the'beta' directory on the iCloud3 GitHub page). The reason is that the Find-my-Friends location service is replacing the Find-my-Phone location service as the default tracking method. FmPhn is going to require 2fa which is not supported by apps like Home Assistant so you get a notification from Apple that someone logged into your account about every half hour. With this change, you will have to specify each device you are taking by name using the new *track_device* config parameter. 

For now, Instead of *include_device_types*, try specifing each device With the *include_devices* parameter.

**Comment by andriuskr** [comment]
Beta is stable?
Can i track battery of macbook and airpods?

**Comment by gcobb321** [comment]
Yes. Beta is stable. Tracking batteries is so-so. Sometimes  the HA App reports battery info, sometimes  Find my Friends reports it, sometimes nothing is reported. Ic3 will get the battery info from the last service to report the location and pass it along. But no guarantee it is always there.

**Comment by andriuskr** [comment]
Tried beta:

Log Details (ERROR)
Sun Sep 15 2019 08:55:16 GMT+0300 (EEST)

iCloud3 Setup Aborted, no devices to track


my config:
device_tracker:
  - platform: icloud3
    username: !secret icloud_andriaus_user 
    password: !secret icloud_andriaus_pass
    account_name: andriaus_icloud
    unit_of_measurement: km
    track_devices:
      - Andriaus iPhone
      - Andriaus MacBook Pro
      - Andriaus Watch
      - Andriaus AirPods

**Comment by andriuskr** [comment]
And with not beta, getting this error:

devicenames or device_types must be included in configuration parameters
9:03 AM custom_components/icloud3/device_tracker.py (ERROR)
iCloud3 Setup Aborted, no devices to track
9:03 AM custom_components/icloud3/device_tracker.py (ERROR)


Config:

device_tracker:
  - platform: icloud3
    username: !secret icloud_andriaus_user 
    password: !secret icloud_andriaus_pass
    account_name: andriaus_icloud
    unit_of_measurement: km
    include_devices:
      - Andriaus iPhone
      - Andriaus MacBook Pro
      - Andriaus Watch
      - Andriaus AirPods

**Comment by gcobb321** [comment]
It is impossible to see what the error is when you just type your platform: iCloud3 settings. The best way is to do a copy-and-paste, then highlight the parameters and click '<>' above. that will put the pasted part In a 'code block' that will look like:

```
device_tracker:
  - platform: icloud3
    username: gary-fmf-acct@email.com       <<< Your Apple iCloud Account ID for your FmF iCloud account
    password: gary-fmf-password
    group: family                      <<< Name of this group of tracked devices.
    track_devices:                   <<< Devices to be tracked
      - gary_iphone > gary-2fa-acct@email.com, gary.png
      - lillian_iphone > lillian-2fa-acct@email.com, lillian.png

```

The above was taken from the beta version documentation. It is an example of how the tracked_device parameter is set up for the Find my Friends tracking method. As you can see, your device names are not in the format used by Home Assistant. Look in The known_devices.yaml file for their names (gary_iphone in the above example). 

```
# Example device names:
iPhone Settings -- General>About = Gary-iPhone
IOS App name    -- gary_iphone 
    
Note: Special characters (’-’) get mapped to ‘_’ by HA.
```

The  iCloud3 documentation has the above but it looks like the some of the paragraph is missing. It also talks about how device's are named.
