### ISSUE TITLE
Prefix to the devices and bind enter/exit to another tracker.

### ISSUE THREAD

**Issue by Cybersmurfen** [gcobb321/icloud3#70]
First of all. Great improvement of Icloud. Could't have done it better myself ;)

I'm missing two things: The option to set a prefix to the entitiy, i.e. that my device_tracker.cybersmurfens_iphone and device_tracker.wifes_iphone could be renamed. A configuration option called prefix would be great, so the tracker could be named device_tracker.icloud3_cybersmurfens_iphone if I set the prefix "icloud3" or device_tracker.gps_cybersmurfens_iphone if I set the prefix "gps". This is because I'm using more trackers, like the Unifi Device Scanner and Tile, who also creates a tracker with the name of the device. When the whole family are using one or two devices each, its easy to loose control over which device who belongs to where.

And for the second: From what I understand the IOS app makes it easier to calculate enters/exits. However, as I am using another device tracker (Unifi) - HA knows if I have left the building or not. Why not have the option to connect the icloud tracker with another enitity for the enter/exit connection. The reason for me is simple - there is no way I can get my wife to use the IOS-app. She's "all good" with Apple Home. And I do understand her - the fewer apps the better.

**Comment by gcobb321** [comment]
I’ll think about the prefix but it is the access to the iCloud account that would complicate matters. I’m trying to get this release out the door so I don’t see it happening in this release.

About triggering zone changes with other trackers. You can set up an automation for the other tracker that is triggered by a state change. Then use the icloud3 update service call with the “zone xxx” parameter to trigger a zone change in iCloud3. The section on service calls in the iCloud3 docs has some examples.
