### ISSUE TITLE
iCloud3 v2.2.0 Documentation Issues, Suggestions and Comments

### ISSUE THREAD

**Issue by gcobb321** [gcobb321/icloud3#72]
Add any suggestions or comments to this issue.  Thanks.  Gary

**Comment by B-Hartley** [comment]
“To be report“ should say “To report” on https://gcobb321.github.io/icloud3_docs/#/

“ To be able to use another zone(s)” should say
“To be able to use other zone(s)”

**Comment by gcobb321** [comment]
v2.2.0 Docs updated. Thanks for picking that up
