### ISSUE TITLE
iCloud3 beta - Map integration, pictures

### ISSUE THREAD

**Issue by robertomano24** [gcobb321/icloud3#73]
Hello,
Thanks for your excellent work with this. It is probably my favorite integration. 
I am probably just dense, but I cannot seem to figure out how to get pictures to show up on the map. Instead, it defaults to first initial. Pictures work elsewhere with the plugin, so I know I have the folders and paths setup correctly. I am sure there is some trick to get the pics to load on the map. I have attached an image for clarification.
![Screenshot_22](https://user-images.githubusercontent.com/284899/67587376-c275eb00-f721-11e9-8252-2db56a4913d5.png)

**Comment by gcobb321** [comment]
I have ‘picture: /local/gary.png’ in my known_devices.yaml file for gary_iphone.  the picture is in the config/www Directory.
