### ISSUE TITLE
Zone within a zone, inner, closer zone not always selected

### ISSUE THREAD

**Issue by marshn** [gcobb321/icloud3#77]
I have been having trouble with overlapping zones. Depending on the order of the zone an 'inner' zone is not always selected. 

The issue seems to be due to what looks like a bug in lines 4849-4852 in device_tracker.py

                if in_zone_flag and (closer_zone_flag or smaller_zone_flag):
                    zone_selected      = zone
                    zone_selected      = zone
                    iosapp_zone_msg    = ""

Changing these lines to this seems to resolve the issue for me:

                if in_zone_flag and (closer_zone_flag or smaller_zone_flag):
                    zone_selected_dist = zone_dist
                    zone_selected      = zone
                    iosapp_zone_msg    = ""

**Comment by gcobb321** [comment]
Fixed in Release Candidate 12c. Thanks for spotting it.
