### ISSUE TITLE
can't install via hacs

### ISSUE THREAD

**Issue by garywilson4** [gcobb321/icloud3#8]
``` Log Details (ERROR)
Wed Nov 27 2019 16:14:24 GMT+0000 (Greenwich Mean Time)
Download was not complete. 
```
can install other integrations fine,  iCloud3 brings the above error.

Home Assistant 0.102.2
hacs Version: 0.17.4

**Comment by gcobb321** [comment]
I have just updated iCloud3 to v2.0.2 and corrected the issues installing with HACS. You should be OK now.
