### ISSUE TITLE
Feature Request: Travel Time based on Google Maps using Public Transport

### ISSUE THREAD

**Issue by poudenes** [gcobb321/icloud3#81]
Hi There,

I love your code and im very happy that I take the time to install it after your last release.
I don't have a car, so would be nice if there is a possibility to calculate the travel time based on Google Maps using public transport.

Kind Regards,
Peter 
Netherlands

**Comment by groenmarsmannetje** [comment]
Why would you expect this in this integration? It is already way too complex. You can already create your own sensor in Home Assistant with Google Maps integration to determine this based on location of a device (or even better: a person). For me this iCloud integration is just one of the device trackers (not the only one) for a person. I really think it is way better to keep things clean and dedicated.
