### ISSUE TITLE
Feature Request: Use !secret to hide emails, password, names etc

### ISSUE THREAD

**Issue by poudenes** [gcobb321/icloud3#82]
Hi There,

Would be nice to have option to use !secret. Then you can hide usernames, passwords, emails, names, etc
If you sync with GitHub then none of your personal information is visible for others when you share your Github.

Now I exclude the device_tracker.yaml from the Github.

**Comment by Mic92** [comment]
I don't think this module needs to do anything for this to work. The following works for me: https://github.com/Mic92/dotfiles/commit/bc20f388c0bc3adb36f00a6007567e30191e6158#diff-69381aa1ce4d801a201e84bd24efc9ceed50b2d6609a5bd313c51a4cc244e8eaR87

**Comment by poudenes** [comment]
I tried the !secret thing but didn't work for me

**Comment by Mic92** [comment]
Maybe a configuration error on your site? custom_components should not have to implement anything to handle secrets. This is handled in home-assistant.

**Comment by gcobb321** [comment]
If HA handles the !secrets, than those parameters would need to be in the configuration.yaml file, not the config_ic3.yaml file. The config_ic3.yaml file is handled as a text file when they are decoded by iCloud3.

**Comment by broyuken** [comment]
I use secrets with icloud3 with no issues.

**Comment by gcobb321** [comment]
v3 encrypts the password in the config files and obscures them when they are displayed on the configuration screens. I hope to have it in beta in November (working on the docs now). It's pretty much done and I haven't seen any issues with it is several weeks. I'll let you know when it's available.
