### ISSUE TITLE
integration goes nuts if you restart HA and a user's phone is off

### ISSUE THREAD

**Issue by 26tajeen** [gcobb321/icloud3#85]
My phone's been off for about four hours. icloud3 was chill, until I restarted HA due to an unrelated improvement, and suddenly it's  constantly polling for my location. Despite the card saying the next update will be at 3:07 (it's now 3:03) I can see it's constantly busy trying to track me down...

**Comment by gcobb321** [comment]
Review the iCloud3 Event Log to see why it is polling for your location. If it had trouble connecting, the location requests will be discarded and the count will be increasing. 

Restart iCloud3 using _Event Log > Actions > Restart iCloud3_ to reset everything.

**Comment by gcobb321** [comment]
The Event Log will tell what is going on. Restarting it at Event Log > Actions > Restart iCloud3 will reset everything and let it reconnect.

**Comment by 26tajeen** [comment]
This is the thing though: iCloud3 HAD just been restarted (because HA had just restarted). It was the restart that caused it to go nuts. It's an edge case I think. Phone off>iCloud3 restarted>Nuts

**Comment by gcobb321** [comment]
When ha restarts and loads icloud3, icloud3 issues a location request to icloud. If it can not connect, it will remain in a not_set state and keep trying. The Event Log should show this. Sometimes, when the phone is turned back on, icloud3 is still not getting the information back from icloud. Restarting on the Event Log usually clears this up,

**Comment by 26tajeen** [comment]
Makes perfect sense and I'm sure the log does show this - I guess I'm just wondering if icloud3 could detect it's going nuts and....stop? For example I'm about to head on holiday out of GSM/WiFi range for a week. If Home Assistant restarts or iCloud3 restarts while I'm gone, iCloud3 is going to do itself a damage ! :-D

**Comment by avd706** [comment]
I've found that sometimes ic3 hand up after a restart of HA, a restart of ic3 via the custom card sets it up working as designedOn Oct 15, 2020 10:29, lancelon <notifications@github.com> wrote:
This is the thing though: iCloud3 HAD just been restarted (because HA had just restarted). It was the restart that caused it to go nuts. It's an edge case I think. Phone off>iCloud3 restarted>Nuts

**Comment by 26tajeen** [comment]
> I've found that sometimes ic3 hand up after a restart of HA, a restart of ic3 via the custom card sets it up working as designed

Cheers fella. Didn't work for me, but thanks! :-)

**Comment by gcobb321** [comment]
I just looked at the code. ic3 looks at the *device_status* returned from icloud. If it is not "online", "pending" or empty, it will retry again in 15-minutes. What is the interval between retries in the Event Log?

**Comment by 26tajeen** [comment]
Retrying about once every 5 seconds

**Comment by gcobb321** [comment]
Can you export your Event Log and email it to me so I can see what it's doing to generate the 5-second poll. Event Log > Actions > Export Event Log. Email the */config/icloud3-event-log.log* file to geekstergary@gmail.com.

**Comment by gcobb321** [comment]
I have solved all issues with starting/restarting HA when the phone is off or can not be accessed by iCloud. If there is no location data returned from iCloud (GPS=(0,0)), iC3 goes into a "Device may be Offline"/retry-to-connect mode where it sets the interval at 15-sec and tries 4 times. If not successful, the interval gets bumped to 1 min, then 5-min, then 15-min, then 30-minutes, retrying 4-times at each interval. If still not successful, the interval gets bumped to the max_interval value (default=4-hrs) and tries that 6 times. After that, polling for that device is paused.

I still have a problem when the phone goes offline after being connected and tracked successfully for a while and will work on that tomorrow. That was a piece that was working at one time so I think I may have broken something dealing with the above issue. I should be posting v2.2.1c after that for your testing to make sure there are no other problems I missed.

**Comment by gcobb321** [comment]
v2.2.1c has just been uploaded to the development directory [here](https://github.com/gcobb321/icloud3/tree/master/development%20area%20-%20v2.2.1) that fixed this problem.

Download and unzip the *development - v2.2.1c.zip* file into the icloud3 directory. and restart HA.

The change log is in the iCloud3 forum [here](https://community.home-assistant.io/t/icloud3-v2-2-device-tracker-advanced-tracking-features-ios-app-monitoring/234311/56)
