### ISSUE TITLE
Feature request: Time format

### ISSUE THREAD

**Issue by mariwing** [gcobb321/icloud3#88]
It would be great if it was possible to specify that one would like 24 hour format for the time in the log and the sensors (like you already enabled the possibility to use km or mi for distance). 

Thank you for all your work and a great component with the most extensive documentation I have seen for any Home Assistant component ever :-)

**Comment by gcobb321** [comment]
Done in v2.2.1e Release Candidate 2. see info [here](https://community.home-assistant.io/t/icloud3-v2-2-device-tracker-advanced-tracking-features-ios-app-monitoring/234311/64).

Use the 'time_format: 24' parameter
