### ISSUE TITLE
Unable to dismiss old authorization request notifications in HA

### ISSUE THREAD

**Issue by bobvmierlo** [gcobb321/icloud3#89]
I'm unable to dismiss excess notifications in HA after re-authorizing my account. Sometimes when it takes me some time to reauthorize there could be multiple notifications in HA (sometimes more than 20).
Those notifications can't be dismissed, and since 0.117 there is a 'dismiss all' button. But when clicking this I get the error below.
Would be great if we could dismiss all those excess notifications.

```
Logger: homeassistant.components.websocket_api.http.connection.140554242874576
Source: core.py:1402
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:25:48 PM (2 occurrences)
Last logged: 9:25:48 PM

required key not provided @ data['notification_id']
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1402, in async_call
    processed_data = handler.schema(service_data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: required key not provided @ data['notification_id']
```

**Comment by gcobb321** [comment]
I have also seen multiple notifications that don't go away, however, when I restarted HA, I was still authenticated and there were no notifications.

**Comment by bobvmierlo** [comment]
Restarting indeed dismisses all the notifications, but it would be better if we could just dismiss them without having to restart HA entirely. Apparently the notifications are missing a 'notification_id', I don't know if you would be able to randomly generate one for every notification so that HA is capable of dismissing them?

**Comment by gcobb321** [comment]
The 2fa issues and verification procedures will be going away soon. I'll start reviewing and incorporating the new 2fa code that lets you use the official 6-digit code from Apple within the next few days. So far, the author verified his iCloud account  5-days ago and has had no problems...yet.

**Comment by gcobb321** [comment]
Closing issue.
