### ISSUE TITLE
No devices to track.

### ISSUE THREAD

**Issue by dominicmcglinn** [gcobb321/icloud3#9]
I'm getting the following error on initial set up with a 2FA enabled phone. installed via HACS community

2019-11-29 10:06:24 ERROR (SyncWorker_13) [custom_components.icloud3.device_tracker] iCloud3 Error: Setup aborted for Group-group1, Username-XXXXX@me.com. No devices to track.

Config is:

device_tracker:
  - platform: icloud3
    username: !secret icloud_username 
    password: !secret icloud_password
    tracking_method: fmf
    track_devices:         
      - XXXphone > XXXXX@me.com, XXX.jpg
      - iPhone > YYY@me.com, YYY.jpg
    unit_of_measurement: km
    waze_region: AU

**Comment by gcobb321** [comment]
iCloud3 can not match up the email address xxxxx@me.com or yyyyy@me.com in the track _devices parameters to any entry in the contacts in the icloud_username account. See item 4 [here in the fmf setup instructions ](https://gcobb321.github.io/icloud3/#/chapters/1-setting-up-icloud-account?id=find-my-friends-fmf) in the iCloud3 documentation.

**Comment by dominicmcglinn** [comment]
I think the issue is that I didnt setup  a new non 2fa account - I switched to tracking_method: iosapp and it seems to be working for now. Pity about the 2fa issue - I doubt many people would a) read instructions properly like me ;) and b) take the time to setup a new icloud account..... maybe I am just lazy
