### ISSUE TITLE
Multiple devices from same account

### ISSUE THREAD

**Issue by broyuken** [gcobb321/icloud3#92]
Hello,

How do I set up iCloud3 so that I can track multiple devices from the same account? I tried doing the below, but only the last device shows up per email address. I have one account setup that I shared my devices and my wifes devices to because of that issue with constant notifications. If there's a better way to set this up I'm all for it. We are already on a family share if that helps. I want to be able to track my apple watch as well as my phone, both of which are under the same apple id.

WORKS
```
platform: icloud3
username: !secret icloud3_username
password: !secret icloud3_password
track_devices:
  - my_iphone > myemailaddress@gmail.com
  - mywifes_iphone > mywifesemailaddress@gmail.com
```

Doesn't work (only tracks last device per email (only our airpods in this case)
```
platform: icloud3
username: !secret icloud3_username
password: !secret icloud3_password
track_devices:
  - my_iphone > myemailaddress@gmail.com
  - my_apple_watch > myemailaddress@gmail.com
  - my_airpods > myemailaddress@gmail.com
  - mywifes_iphone > mywifesemailaddress@gmail.com
  - mywifes_apple_watch > mywifesemailaddress@gmail.com
  - mywifes_airpods > mywifesemailaddress@gmail.com
```

**Comment by gcobb321** [comment]
Have you reviewed the Event Log for information about the tracked and not tracked devices? The ic3 User Manual/2.4 Setting up iCloud3 talks about trouble shooting start up errors [here](https://gcobb321.github.io/icloud3/#/chapters/1-setting-up-icloud3?id=troubleshooting-startup-errors). Select the '?' icon on the Event Log.

**Comment by broyuken** [comment]
Looking at the event log I see the following:

```
  | iCloud3  Error for Brians (brians_iphone) > The email address  `**************@gmail.com` is invalid or is not in the FmF contact list and  will not be tracked.-------------------------
-- | --
```
```
11:40:14a | Verified Device > Briansapple (brians_apple_watch)
-- | --
11:40:14a | iCloud3 Setup Error >  > The iOS App device_tracker entity was not found in the Entity Registry.Device_tracker entities (suffixes) found -
```
However the email address IS valid, and when I comment out my apple watch, the iphone is tracked just fine. It doesn't seem to be possible to track multiple devices on the same account. At least not with the method of tracking I'm using for some reason.

**Comment by gcobb321** [comment]
Go to the *iCloud3 Event Log > Actions > Export Event Log*, select it to create a file with all of the events and mail the */config/icloud3_event_log.log* file to geekstergary@gmail.com. I'll look at what is happening when iCloud3 starts and let you know if I see something.

There are some sample screens in the docs about trouble shooting issues [here](https://gcobb321.github.io/icloud3/#/chapters/1-setting-up-icloud3?id=troubleshooting-startup-errors).

**Comment by gcobb321** [comment]
I just noticed something and reread your original question. When you said’ multiple devices per person’, I just thought multiple people. Sorry for my confusion. 

 The email address is used to tie the device (phone, watch, AirPods) to the device name (my_phone, my_watch, etc) and can only be used once. You can not have more than one device for an email address. When iCloud3 is scanning the iCloud device list, it is not looking at the device type and stops scanning when it finds the first email address match. I’ll look at adding a device type check to the scanning process when I get a chance.

**Comment by broyuken** [comment]
Closed via development code in https://github.com/gcobb321/icloud3/issues/94#issuecomment-724270599
