### ISSUE TITLE
An error was encountered setting up the `pyicloud_ic3.py` module.

### ISSUE THREAD

**Issue by garyt72** [gcobb321/icloud3#95]
I'm getting this error on startup, but have confirmed that the pyicloud_ic3.py module is in the custom_components/icloud3 directory.

I am also not seeing the notification that is described in the log file to complete authentication.

I've turned on debug logging, and attached to this issue.

[icloud3.log](https://github.com/gcobb321/icloud3/files/5505752/icloud3.log)

**Comment by gcobb321** [comment]
This error is displayed if there is a problem loading the pyicloud_ic3.py module. It loads from the same directory as icloud3. If it is in the icloud3 directory, then I would assume there is something wrong with the file. Update this issue and include the pyicloud_ic3.py file that you see so I can look at it. After you attach it to a reply, I would reinstall icloud3 or unzip the pyicloud_ic3.py file from the icloud3.zip file [here](https://github.com/gcobb321/icloud3) and see if it starts.

**Comment by garyt72** [comment]
I've attached the pyicloud_ic3.py file from the icloud3 directory (before making any more changes).   FYI, I updated to the latest version via HACS, and did confirm that the directory was deleted and replaced with "new" files after the update.  I also re-installed the current version with the same result.

[pyicloud_ic3.py.txt](https://github.com/gcobb321/icloud3/files/5507262/pyicloud_ic3.py.txt)

I did do a diff on the file on my system and the one from the zip file, and they appear to be same.  After replacing all files with those in the .zip file and restarting home assistant, I'm continuing to get the same error.

Some more details on my system if it helps: 
OS: Ubuntu 18.04.5 LTS
Python: v3.8.6 (virtual environment)
Home Assistant version: v0.117.4 (core)
IC3: v2.2.1a (from the .zip file linked above)

In order to keep functionality, I have been reverting to v2.1.0 using HACS between testing sessions, then updating to latest version using HACS.

**Comment by gcobb321** [comment]
The file you sent looks fine, and, with the number of downloads and installs from HACS, it’s not the file. I have had problems from time to time where I would make and update and it not get loaded by HA. It’s like it gets reloaded from a cache rather than the file. 

The solution was to power cycle my Pi.

**Comment by garyt72** [comment]
I tried the following tonight:

1. Update from v2.1.0 to v2.2.1 via HACS
2. Update Home Assistant to v0.117.5
3. Rebooted the Ubuntu VM that Home Assistant is running on.  After the reboot continued getting the same error previously reported
4. Uninstall iC3 via HACS and confirmed the custom_components/icloud3 directory was deleted
5. Restarted HA and confirmed the the integration was "missing" in the logs
6. Installed iC3 v2.2.1 via HACS
7. Restarted HA and continued to get the same error
8. Deleted the __pycache__ directory and restarted HA - continued to get the same error
9. Reinstalled iC3 v2.1.0 via HACS
10. Restarted HA and functionality returned to normal with no iC3 errors

Is there a dependency that I might be missing after updating the Python venv to v3.8.6 that is needed for v2.2.1 but not v2.1.0?  Would the configuration settings from v2.1.0 being used with v2.2.1 be causing the issue?

Edit: Sorry - bumped "Close with comment" by accident - didn't mean to close.

**Comment by gcobb321** [comment]
Both pyicloud_ic3 and iCloud3 import various Python routines when they start. I can’t think off anything that really changed between v2.1 and v2.2. I’m running on hassio and have no knowledge of Linux, ubantu, venv, docker or the other system related stuff. There was one import related to importing device tracker legacy code but can not recall when I made the change. It’s commented out around lines 50-60 or so right at the beginning of iCloud3 (‘#’ as the first character on the line). 

I just uploaded v2.2.2 in the iCloud3 development directory that updates pyicloud_ic3 and device _tracker.py. I wonder if they will install.

**Comment by garyt72** [comment]
I got my development system back up and running with HACS and the latest ic3 version installed via HACS.  I then removed the error handling from around the pyicloud_ic3 imports, and finally got to this error in the HA logs:
`Platform error device_tracker.icloud3 - No module named 'keyring'`

I installed the keyring module in the virtual environment using the following command:
`pip install keyring`

After restarting home assistant, everything seems to have started successfully without any errors and began working as expected on v2.2.1a.

**Comment by gcobb321** [comment]
Interesting. The keyring is one of the utility functions in pyicloud.py that is not used by iCloud3. I’m updating pyicloud_ic3.py right now to support 2fa. I’ll remove the keyring code so your problems will not affect others. Thanks for letting me know you are up and running and what the problem was.
