### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by chrisbl01** [gcobb321/icloud3#97]
Keep getting below and very well may be because the device name is iPhone.  This only occurs when using the app as the tracking method.  Doesn't seem to really break anything that I can tell.  I can get you more logs if you want to look into it further.

Logger: custom_components.icloud3.device_tracker
Source: custom_components/icloud3/device_tracker.py:6038
Integration: icloud3
First occurred: 10:04:50 PM (1 occurrences)
Last logged: 10:04:50 PM

string index out of range
Traceback (most recent call last):
  File "/config/custom_components/icloud3/device_tracker.py", line 6038, in _initialize_device_zone_fields
    first_initial = self.fname.get(devicename)[0].lower()
IndexError: string index out of range

**Comment by gcobb321** [comment]
Fixed in rc7 just released
