### ISSUE TITLE
Driving Flag?

### ISSUE THREAD

**Issue by broyuken** [gcobb321/icloud3#98]
Could you please share what you use to get the driving flag from your sample lovelace cards?

https://gcobb321.github.io/icloud3/#/chapters/3-sample-lovelace

**Comment by gcobb321** [comment]
There is an `input_boolean.gary_driving_flag` that is set to On when the zone_distance > 2. Then it is used in the automation for opening the garage door if it is On. That script sets it back to Off.

See *Set/Clear Driving Flag* [here](https://gcobb321.github.io/icloud3/#/chapters/3-sample-automation-scripts?id=setclear-driving-flags).
See *Arriving Home Automation & Script* [here](https://gcobb321.github.io/icloud3/#/chapters/3-sample-automation-scripts?id=arriving-home-automation-amp-script).

**Comment by broyuken** [comment]
Oh I thought it could detect if your phone was in do not disturb while driving mode. Thanks anyways, this could be useful for something else.

**Comment by avd706** [comment]
Detect if it is moving and chargingOn Dec 3, 2020 21:20, broyuken <notifications@github.com> wrote:
Oh I thought it could detect if your phone was in do not disturb while driving mode. Thanks anyways, this could be useful for something else.
